### ISSUE TITLE
[Development] - npm run bootstrap fails via node 8.11.3

### ISSUE THREAD

**Issue by seanwash** [getinsomnia/insomnia#1043]
Following the setup instructions and having some troubles over here 😅From what I can find via google, it could have something to do with a nan version.

## Details

- Insomnia Version: develop branch
- Operating System: MacOS 10.13.5
- Node V: 8.11.3 / 10.6.0
- Npm V: 5.6.0

```
lerna ERR! execute Error occured with 'insomnia-app' while running 'npm run postinstall'
{ Error: Command failed: npm run postinstall

An unhandled error occurred inside electron-rebuild
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:832:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/seanwash/.electron-gyp/.node-gyp/iojs-3.0.0-beta.2/src/node.h:93:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/seanwash/.electron-gyp/.node-gyp/iojs-3.0.0-beta.2/src/core.h:35:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:847:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/seanwash/.electron-gyp/.node-gyp/iojs-3.0.0-beta.2/src/node.h:86:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/seanwash/.electron-gyp/.node-gyp/iojs-3.0.0-beta.2/src/core.h:35:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:862:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/seanwash/.electron-gyp/.node-gyp/iojs-3.0.0-beta.2/src/node.h:79:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/seanwash/.electron-gyp/.node-gyp/iojs-3.0.0-beta.2/src/core.h:35:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1471:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/seanwash/.electron-gyp/.node-gyp/iojs-3.0.0-beta.2/src/node.h:93:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/seanwash/.electron-gyp/.node-gyp/iojs-3.0.0-beta.2/src/core.h:35:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/seanwash/Sites/insomnia/packages/insomnia-app/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/Users/seanwash/.nvm/versions/node/v8.11.3/bin/node" "/Users/seanwash/Sites/insomnia/packages/insomnia-app/node_modules/.bin/node-gyp" "rebuild" "--target=3.0.0-beta.2" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=fse" "--module_path=/Users/seanwash/Sites/insomnia/packages/insomnia-app/node_modules/fsevents/lib/binding/Release/electron-v3.0-darwin-x64" "--remote_path=./v1.1.3/" "--package_name=fse-v1.1.3-electron-v3.0-darwin-x64.tar.gz" "--host=https://fsevents-binaries.s3-us-west-2.amazonaws.com"
gyp ERR! cwd /Users/seanwash/Sites/insomnia/packages/insomnia-app/node_modules/fsevents
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok

Failed with exit code: 1
```

**Comment by gschier** [comment]
Ah ya, sorry. The `develop` branch is completely broken right now. Try checking out `528a8c3b2b8c9eeb368a1087aa74e76ec1d7e931`

**Comment by gschier** [comment]
FYI, currently trying to update to Electron 3.0 (Node 10) and it's not going so well...

**Comment by seanwash** [comment]
@gschier godspeed!

That commit hash does build, but now I'm running into `node-pre-gyp` not being found on `app-start`. I'll see if I can't figure it out! 

![](https://c.seanwash.com/N02pMMS1FdwH.png)

**Comment by gschier** [comment]
Glad you were able to figure that one out 👍😃
