### ISSUE TITLE
[Bug] Render Failure when repeated requests are made

### ISSUE THREAD

**Issue by f-prime** [getinsomnia/insomnia#1094]
- Insomnia Version: 6.0.1
- Operating System: macOS High Sierra

## Details

This error occurs when I make repeated requests to a Python Flask debugging page. The issue causes Insomnia to become unusable and requires a restart to fix the issue.

```
Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at HTMLElement.loadURL (/Applications/Insomnia.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:390:15)
    at ResponseWebView._setBody (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:100483:19)
    at ResponseWebView.componentDidUpdate (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:100492:10)
    at commitLifeCycles (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:241624:207)
    at R (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:241650:7)
    at G (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:241647:349)
    at x (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:241646:378)
    at n (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:241646:221)
    at B (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:241645:117)
    at v (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:241644:51)
```

**Comment by gschier** [comment]
Woah, that's a strange one. Should be fixable though!
