### ISSUE TITLE
[Question] TypeError: Cannot read property 'split' of undefined when running ` npm run app-start` on windows

### ISSUE THREAD

**Issue by SahandAkbarzadeh** [getinsomnia/insomnia#1126]
- Insomnia Version:  4a3857a
- Operating System: windows 10

## Details

when i try to run `npm run app-start` after successfully running ` npm run bootstrap` on windows i get this error :
output:
```
npm run app-start

> insomnia@1.0.0 app-start C:\Users\****\Documents\GitHub\insomnia
> lerna run start --stream --scope=insomnia-app

lerna info version 2.5.1
lerna info versioning independent
lerna info scope insomnia-app
lerna ERR! EPACKAGES Errored while collecting packages and package graph
lerna ERR! TypeError: Cannot read property 'split' of undefined
lerna ERR!     at Minimatch.match (C:\Users\****\Documents\GitHub\insomnia\node_modules\minimatch\minimatch.js:713:11)
lerna ERR!     at minimatch (C:\Users\****\Documents\GitHub\insomnia\node_modules\minimatch\minimatch.js:107:42)
lerna ERR!     at C:\Users\****\Documents\GitHub\insomnia\node_modules\lerna\lib\PackageUtilities.js:74:38
lerna ERR!     at Array.some (<anonymous>)
lerna ERR!     at filterPackage (C:\Users\****\Documents\GitHub\insomnia\node_modules\lerna\lib\PackageUtilities.js:73:17)
lerna ERR!     at C:\Users\****\Documents\GitHub\insomnia\node_modules\lerna\lib\PackageUtilities.js:213:18
lerna ERR!     at Array.filter (<anonymous>)
lerna ERR!     at Function.filterPackages (C:\Users\****\Documents\GitHub\insomnia\node_modules\lerna\lib\PackageUtilities.js:212:29)
lerna ERR!     at RunCommand.runPreparations (C:\Users\****\Documents\GitHub\insomnia\node_modules\lerna\lib\Command.js:326:60)
(node:4832) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at Minimatch.match (C:\Users\****\Documents\GitHub\insomnia\node_modules\minimatch\minimatch.js:713:11)
    at minimatch (C:\Users\****\Documents\GitHub\insomnia\node_modules\minimatch\minimatch.js:107:42)
    at C:\Users\****\Documents\GitHub\insomnia\node_modules\lerna\lib\PackageUtilities.js:74:38
    at Array.some (<anonymous>)
    at filterPackage (C:\Users\****\Documents\GitHub\insomnia\node_modules\lerna\lib\PackageUtilities.js:73:17)
    at C:\Users\****\Documents\GitHub\insomnia\node_modules\lerna\lib\PackageUtilities.js:213:18
    at Array.filter (<anonymous>)
    at Function.filterPackages (C:\Users\****\Documents\GitHub\insomnia\node_modules\lerna\lib\PackageUtilities.js:212:29)
    at RunCommand.runPreparations (C:\Users\****\Documents\GitHub\insomnia\node_modules\lerna\lib\Command.js:326:60)
    at C:\Users\****\Documents\GitHub\insomnia\node_modules\lerna\lib\Command.js:225:18
(node:4832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sahand100** [comment]
### UPDATE

tried with WSI (ubuntu 16.04 ) : same error

**Comment by gschier** [comment]
What version of NodeJS and NPM are you running?

**Comment by sahand100** [comment]
@gschier sorry for answering late
i don't remember exact versions but i tried node 8, 10 and 6.
