### ISSUE TITLE
[Bug] Insomnia won't start if /tmp is mounted with _noexec_ option on GNU/Linux

### ISSUE THREAD

**Issue by RomainMorlevat** [getinsomnia/insomnia#1133]
- Steps to reproduce :
Mount _/tmp_ like this in _/etc/fstab_
`none /tmp tmpfs defaults,nosuid,nodev,noexec 0 0`

- Insomnia Version: 6.0.2
- Operating System: Archlinux x64

- error message :
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.xF6EtX: failed to map segment from shared object
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:29)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:280:3)
```

- workaround is to remount _/tmp_ with _exec_ option, but it's not optimal for security :
`sudo mount -o remount,exec /tmp`

Plus I don't think _/tmp_ is the right place to execute Insomnia (or rather the Chromium instance of Electron), see [this doc about what is /tmp](http://refspecs.linuxfoundation.org/FHS_2.3/fhs-2.3.html#TMPTEMPORARYFILES)

**Comment by gschier** [comment]
I'm not really sure why this happens (if it's Electron or the package format) but I have a feeling we can't do much about it. For now, here's a temporary _fix_ mentioned on the Signal repo https://github.com/signalapp/Signal-Desktop/issues/2595#issuecomment-411753098
