### ISSUE TITLE
Insomnia-6.0.2 AppImage won't run on RHEL 7 for lack of GLIBCXX_3.4.21

### ISSUE THREAD

**Issue by dhulke** [getinsomnia/insomnia#1149]
- Insomnia Version: 6.0.2
- Operating System: RHEL 7.5

I tried running the AppImage executable but I get the following error message:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.x3N5XR)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_insomnhBdBea/app/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:29)
    at Object.<anonymous> (/tmp/.mount_insomnhBdBea/app/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:280:3)
```

The latest version of libstdc++ I get in the official RHEL 7.5 repositories is libstdc++.so.6.0.19 and the latest version of gcc is 4.8.5. According to [this](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html) documentation, I'd need at least gcc 5.1.0 to get the necessary glibcxx lib.

Given that the AppImage is the only easy way to install this app on redhat and redhat is a pretty common system, would it be possible to downgrade the lib requirements for Insomnia?

**Comment by gchabirand** [comment]
Exact same problem with Bunsen Labs _Hydrogen_ (based on Debian 8).

**Comment by gschier** [comment]
Looks like this is likely due to Insomnia v6 being built on Ubuntu 16.04 instead of Ubuntu 14.04. Will redirect this discussion to the newer issue https://github.com/getinsomnia/insomnia/issues/1208
