### ISSUE TITLE
[Package] Build non-snap release on Ubuntu 14.04 again

### ISSUE THREAD

**Issue by ppazos** [getinsomnia/insomnia#1208]
- Insomnia Version: 6.0.2
- Operating System: Linux Mint 17.3

## Details

Wanted to update from previous version to the latest following https://support.insomnia.rest/article/23-installation#ubuntu

Then when I run insomnia:

```
$ insomnia
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.nzA553)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:29)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:280:3)
```

**Comment by ppazos** [comment]
Got the same error from the insomnia-6.0.2-x86_64.AppImage file.

How can I downgrade to the previous version 5.8.4 that was working OK? Need to give class tomorrow and this doesn't seem to work.

**Comment by ppazos** [comment]
Tested the 5.16.6 AppImage and it works! I think I'll be in the 5.x safe zone :)

**Comment by gschier** [comment]
Version 6 is built on a later version of Ubuntu (16.04 instead of 14.04) in order to make snap packaging work. This is probably what broke things.

I've seen this bug reported a few times now so it's probably worth creating a separate build process for the non-snap release that runs on Ubuntu 14.04.

**Comment by gschier** [comment]
This is now in effect again on v6.2+

**Comment by ppazos** [comment]
@gschier just downloaded 6.3.1 and have the same issue, also tested with 6.2.3. Only workaround is with the AppImage for 5.16.6

**Comment by gschier** [comment]
Hmm, I'm not sure what the issue could be then 😕 

The error says that Chromium is requiring glibc so maybe the issue was actually from upgrading Electron instead.
