### ISSUE TITLE
[Development] npm bootstrap libcurl

### ISSUE THREAD

**Issue by barell** [getinsomnia/insomnia#1362]
So I just installed nodejs version 8.15.0 and cloned this repo. 

Following the steps from readme, when running npm run bootstrap I got this:

```
> insomnia@1.0.0 bootstrap /home/bart/projects/insomnia
> npm install && lerna bootstrap && lerna run bootstrap


> husky@1.0.0-rc.9 install /home/bart/projects/insomnia/node_modules/husky
> node lib/installer/bin install

husky > setting up git hooks
husky > done
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1011 packages from 469 contributors and audited 54269 packages in 8.527s
found 11 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
lerna notice cli v3.4.3
lerna info versioning independent
lerna info Bootstrapping 21 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in 'insomnia-libcurl'
lerna ERR! npm install stdout:

> insomnia-node-libcurl@2.0.0-alpha.0-1 install /home/bart/projects/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl
> node-pre-gyp install --fallback-to-build

Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/bart/projects/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/bart/projects/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)

lerna ERR! npm install stderr:
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.0.0-alpha.0-1/node_libcurl-v2.0.0-alpha.0-1-node-v57-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for insomnia-node-libcurl@2.0.0-alpha.0-1 and node@8.15.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
Could not run curl-config, please make sure libcurl dev package is installed.
Output: /bin/sh: 1: curl-config: not found

gyp: Call to 'node "/home/bart/projects/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/tools/curl-config.js" --cflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-141-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/bart/projects/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/home/bart/projects/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /home/bart/projects/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/bart/projects/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/bart/projects/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/bart/projects/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.4.0-141-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/bart/projects/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/bart/projects/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl
node-pre-gyp ERR! node -v v8.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
npm WARN insomnia-libcurl@0.0.24 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! insomnia-node-libcurl@2.0.0-alpha.0-1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the insomnia-node-libcurl@2.0.0-alpha.0-1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bart/.npm/_logs/2019-01-31T21_17_23_324Z-debug.log

lerna ERR! npm install exited 1 in 'insomnia-libcurl'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! insomnia@1.0.0 bootstrap: `npm install && lerna bootstrap && lerna run bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the insomnia@1.0.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bart/.npm/_logs/2019-01-31T21_17_23_381Z-debug.log
```

Is there anything obvious I'm missing?

I am new to nodejs world so don't know where to look...

**Comment by gschier** [comment]
There's an error message in there if you look hard enough 👍😉

```please make sure libcurl dev package is installed```

**Comment by barell** [comment]
Thank you Gregory. That was obvious, I should spot it...

I have run the command below to fix libcurl issue:
```
$ sudo apt install libcurl4-openssl-dev libssl-dev
```

Then I run again `npm run bootstrap` and had other error:
```
../src/FontManagerLinux.cc:1:35: fatal error: fontconfig/fontconfig.h: No such file or directory
compilation terminated.
```
So I had to install another dependency to fix it:
```
sudo apt-get install libfontconfig1-dev
```

After these steps, `npm run bootstrap` worked fine! Then I run `npm run app-start` and had the error below:
```
> insomnia-app@1.1.0 start /home/bart/projects/insomnia/packages/insomnia-app
> concurrently --kill-others "npm run start:dev-server" "npm run start:electron"

[0] 
[0] > insomnia-app@1.1.0 start:dev-server /home/bart/projects/insomnia/packages/insomnia-app
[0] > webpack-dev-server --config ./webpack/webpack.config.development.babel.js
[0] 
[1] 
[1] > insomnia-app@1.1.0 start:electron /home/bart/projects/insomnia/packages/insomnia-app
[1] > cross-env NODE_ENV=development webpack --config ./webpack/webpack.config.electron.babel.js && electron .
[1] 
[0] ℹ ｢wds｣: Project is running at http://localhost:3333/
[0] ℹ ｢wds｣: webpack output is served from /
[1] Hash: df84e469b8ad3545cd01
[1] Version: webpack 4.20.2
[1] Time: 1140ms
[1] Built at: 2019-02-02 11:26:23
[1]       Asset     Size  Chunks             Chunk Names
[1] main.min.js  796 KiB       0  [emitted]  main
[1] Entrypoint main = main.min.js
[1]  [0] ./common/constants.js 28.8 KiB {0} [built]
[1]  [1] ./common/database.js 20.8 KiB {0} [built]
[1]  [3] ./models/index.js 6.07 KiB {0} [built]
[1]  [4] external "electron" 42 bytes {0} [built]
[1]  [6] ./common/misc.js 13 KiB {0} [built]
[1]  [7] external "path" 42 bytes {0} [built]
[1] [12] external "uuid" 42 bytes {0} [built]
[1] [13] ../package.json 6.25 KiB {0} [built]
[1] [14] ./main/window-utils.js 13.7 KiB {0} [built]
[1] [17] external "electron-squirrel-startup" 42 bytes {0} [built]
[1] [18] ./main/error-handling.js 712 bytes {0} [built]
[1] [19] ./main/updates.js 5.29 KiB {0} [built]
[1] [43] multi ./main.development.js 28 bytes {0} [built]
[1] [44] ./main.development.js 5.21 KiB {0} [built]
[1] [53] external "electron-context-menu" 42 bytes {0} [built]
[1]     + 39 hidden modules
[1] /home/bart/projects/insomnia/packages/insomnia-app/node_modules/electron/index.js:14
[1]     throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
[1]     ^
[1] 
[1] Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
[1]     at getElectronPath (/home/bart/projects/insomnia/packages/insomnia-app/node_modules/electron/index.js:14:11)
[1]     at Object.<anonymous> (/home/bart/projects/insomnia/packages/insomnia-app/node_modules/electron/index.js:18:18)
[1]     at Module._compile (module.js:653:30)
[1]     at Object.Module._extensions..js (module.js:664:10)
[1]     at Module.load (module.js:566:32)
[1]     at tryModuleLoad (module.js:506:12)
[1]     at Function.Module._load (module.js:498:3)
[1]     at Module.require (module.js:597:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/home/bart/projects/insomnia/packages/insomnia-app/node_modules/electron/cli.js:3:16)
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! insomnia-app@1.1.0 start:electron: `cross-env NODE_ENV=development webpack --config ./webpack/webpack.config.electron.babel.js && electron .`
[1] npm ERR! Exit status 1
[1] npm ERR! 
[1] npm ERR! Failed at the insomnia-app@1.1.0 start:electron script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1] 
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/bart/.npm/_logs/2019-02-02T11_26_23_921Z-debug.log
[1] npm run start:electron exited with code 1
--> Sending SIGTERM to other processes..
[0] (node:13706) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
[0] npm run start:dev-server exited with code null

lerna ERR! npm run start stderr:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! insomnia-app@1.1.0 start: `concurrently --kill-others "npm run start:dev-server" "npm run start:electron"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the insomnia-app@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bart/.npm/_logs/2019-02-02T11_26_36_193Z-debug.log

lerna ERR! npm run start exited 1 in 'insomnia-app'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! insomnia@1.0.0 app-start: `lerna run start --stream --scope=insomnia-app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the insomnia@1.0.0 app-start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bart/.npm/_logs/2019-02-02T11_26_36_208Z-debug.log
```

I will try to find a solution but in the meantime would be great if someone had the same issue and knows how to help...

**Comment by barell** [comment]
Success! I realised I was removing wrong node_modules/electron and I was missing electron too (I think). 

Not sure if this was something I needed to do to fix my issues but I had to install electron:
```
$ npm install electron --save-dev
```
I also did it globally (again, not sure if this is needed once you installed with --save-dev)
```
$ npm install electron -g
```

Then remove node_modules from packages/insomnia-app:
```
$  rm -rf packages/insomnia-app/node_modules
```

And run `npm run bootstrap` again. Finally, run:
```
$ npm run app-start
```

And it worked!

**Comment by jasonsemko** [comment]
Thanks @barell this worked for me. I'm on a fresh Ubuntu so it'd be nice to have all of of your suggestions mentioned in the README for Linux users. 

@gschier would you be open to a pull request that adds a little "Linux gotchas" problems/solutions to the README?
