### ISSUE TITLE
[Bug] Library not loaded

### ISSUE THREAD

**Issue by veverkap** [getinsomnia/insomnia#1735]
- Insomnia Version: 7.0.2
- Operating System: MacOS X Mojave

## Details

Just updated and got this error on launch:

```
Uncaught Exception:
Error: dlopen(/var/folders/1_/0s3k9f_15hj1n54w8xnpsd_w0000gp/T/.com.insomnia.app.8VNRlX, 1): Library not loaded: @rpath/libcurl.dylib
  Referenced from: /var/folders/1_/0s3k9f_15hj1n54w8xnpsd_w0000gp/T/.com.insomnia.app.8VNRlX
  Reason: Incompatible library version: .com.insomnia.app.8VNRlX requires version 11.0.0 or later, but libcurl.dylib provides version 10.0.0
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:32)
    at Object.<anonymous> (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:279:3)```

**Comment by shaliniJK** [comment]
I'm having the same issue after updating to the latest version of Insomnia on macOS High Sierra.

**Comment by DamianSam** [comment]
Same here, after updating:

`**A JavaScript error occurred in the main process**
Uncaught Exception:
Error: dlopen(/var/folders/1_/43r30kdx4p9gk0_s8lcd97nm0000gn/T/.com.insomnia.app.3TuEqG, 1): Library not loaded: @rpath/libcurl.dylib
  Referenced from: /var/folders/1_/43r30kdx4p9gk0_s8lcd97nm0000gn/T/.com.insomnia.app.3TuEqG
  Reason: Incompatible library version: .com.insomnia.app.3TuEqG requires version 11.0.0 or later, but libcurl.dylib provides version 10.0.0
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:32)
    at Object.<anonymous> (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:279:3)`

**Comment by KalleVuorjoki** [comment]
I have same issue, temporary fix is to downgrade to older version https://updates.insomnia.rest/downloads/mac/7.0.0

**Comment by toshim45** [comment]
same issue on mac os sierra
```
Uncaught Exception:
Error: dlopen(/var/folders/qn/nyx4mydd3cx7twkbdqs5mw980000gn/T/.com.insomnia.app.roiORO, 1): Library not loaded: @rpath/libcurl.dylib
  Referenced from: /var/folders/qn/nyx4mydd3cx7twkbdqs5mw980000gn/T/.com.insomnia.app.roiORO
  Reason: Incompatible library version: .com.insomnia.app.roiORO requires version 11.0.0 or later, but libcurl.4.dylib provides version 7.0.0
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/artikow/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:32)
    at Object.<anonymous> (/Users/artikow/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:279:3)
```

**Comment by Bucozar** [comment]
I'm on MacOs High Sierra 10.13.4 and got similar `libcurl.dylib` error. The error occurs every time when trying to open the app, and the app does not show UI windows or Menu and has to be force quit to exit. 
Downloading version 7.0.1 fixed the issue. So need for the newer version of `libcurl.dylib` was introduced in 7.0.2

After installing 7.0.1 I had to take out the setting of automatic updates because the non-working version got automatically installed again.

**Comment by sergiofilhowz** [comment]
Happening to me too, I can't open the application.

![Screen Shot 2019-10-18 at 09 09 39](https://user-images.githubusercontent.com/4141723/67093126-4ca0db00-f187-11e9-8518-8f17d089e7f7.png)

**Comment by sergiofilhowz** [comment]
I recommend rolling back to 7.0.1 (the app is broken on 7.0.2).
Link below or you can go to releases and find the URL for the platform/bundle you want

DMG file: https://github.com/getinsomnia/insomnia/releases/download/v7.0.1/Insomnia-7.0.1.dmg

Releases: https://github.com/getinsomnia/insomnia/releases

**Comment by UkiahSmith** [comment]
I, also, am having the same issue after updating to the latest version of Insomnia on macOS High Sierra.

macOS version: 10.13.6 (17G8037)

There is no issue with Insomnia version 7.0.1 (7.0.1.3041).

**Comment by gschier** [comment]
I just pulled 7.0.2 so no one else gets the update. Working on a fix now. I think this was related to the fact that the last build used GitHub Actions instead of TravisCI which runs in a newer macOS environment.

Going to defer to this issue for future discussion #1739
