### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by elemanhillary** [getinsomnia/insomnia#1736]
- Insomnia Version: Fresh install from https://insomnia.rest/graphql/
- Operating System: MacOs(catalina)

```
Uncaught Exception:
Error: dlopen(/var/folders/_h/m8nl21w96p961zjhpj0nzx0h0000gn/T/.com.insomnia.app.GYwrEc, 1): Library not loaded: @rpath/libcurl.dylib
  Referenced from: /var/folders/_h/m8nl21w96p961zjhpj0nzx0h0000gn/T/.com.insomnia.app.GYwrEc
  Reason: Incompatible library version: .com.insomnia.app.GYwrEc requires version 11.0.0 or later, but libcurl.dylib provides version 10.0.0
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:32)
    at Object.<anonymous> (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:279:3)
```

**Comment by sergiofilhowz** [comment]
It's happening to me again. I can't open the application.

![Screen Shot 2019-10-18 at 09 09 39](https://user-images.githubusercontent.com/4141723/67093005-09df0300-f187-11e9-8af1-f326f459ea4a.png)

**Comment by neontuna** [comment]
Same issue here, happened after allowing app to update to 7.0.1

```
Uncaught Exception:
Error: dlopen(/var/folders/j7/j8dysv297g19qtv1v6yjx_cc0000gn/T/.com.insomnia.app.ozsTkG, 1): Library not loaded: @rpath/libcurl.dylib
  Referenced from: /var/folders/j7/j8dysv297g19qtv1v6yjx_cc0000gn/T/.com.insomnia.app.ozsTkG
  Reason: Incompatible library version: .com.insomnia.app.ozsTkG requires version 11.0.0 or later, but libcurl.dylib provides version 10.0.0
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:32)
    at Object.<anonymous> (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:279:3)
```

**Comment by sergiofilhowz** [comment]
I recommend rolling back to 7.0.1 (the app is broken on 7.0.2).
Link below or you can go to releases and find the URL for the platform/bundle you want

DMG file: https://github.com/getinsomnia/insomnia/releases/download/v7.0.1/Insomnia-7.0.1.dmg

Releases: https://github.com/getinsomnia/insomnia/releases

**Comment by gschier** [comment]
I just pulled 7.0.2 so no one else gets the update. Working on a fix now. I think this was related to the fact that the last build used GitHub Actions instead of TravisCI which runs in a newer macOS environment.

Going to defer to #1739 for further discussion
