### ISSUE TITLE
Setting up development

### ISSUE THREAD

**Issue by elemanhillary** [getinsomnia/insomnia#1775]
When i run `npm run bootstrap`, i get the following error
```
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/12.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/xxxxxxxxxxx/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/Users/xxxxxxxxxx/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/lib/binding" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/xxxxxxxx/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/12.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/xxxxxxxxxx/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/Users/xxxxxxxx/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/lib/binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/xxxxxxxx/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 19.0.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/12.8.0/bin/node" "/Users/xxxxxxxxx/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/xxxxxxxxxx/insomnia/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl
node-pre-gyp ERR! node -v v12.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
npm WARN insomnia-libcurl@0.0.30 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! insomnia-node-libcurl@2.0.0-alpha.0-1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the insomnia-node-libcurl@2.0.0-alpha.0-1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxxxxxxxx/.npm/_logs/2019-11-11T13_20_34_655Z-debug.log

lerna ERR! npm install exited 1 in 'insomnia-libcurl'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! insomnia@1.0.0 bootstrap: `npm install && lerna bootstrap && lerna run --parallel --stream bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the insomnia@1.0.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by gschier** [comment]
Please ensure you are running Node 10.x. I recommend using NVM for this and there is an `.nvmrc` in the project if you'd like to use it :)
