### ISSUE TITLE
[Bug] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string.

### ISSUE THREAD

**Issue by patrickmaciel** [getinsomnia/insomnia#1908]
**Describe the bug**

This errors occurs when I import a Postman collection with some multipart-formdata field of file type.

```text
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
at assertPath (path.js:39:11)
at basename (path.js:751:5)
at FileInputButton.render (file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:60864:75)
at Qg (file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:236595:192)
at Og (file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:236594:264)
at Tg (file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:236602:30)
at bi (file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:236654:22)
at ci (file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:236655:284)
at Di (file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:236671:348)
at Yh (file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:236670:144)
at Xh (file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:236667:332)
at qf (file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:236665:86)
at Ji (file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:236675:14)
at Ki (file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:236675:92)
at Pi.module.exports.Pi.render (file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:236683:109)
at file:///C:/Users/patri/AppData/Local/insomnia/app-7.0.6/resources/app.asar/bundle.js:236686:395
```

**To Reproduce**
1. Import a Postman collection with multipart-formdata endpoint + file type field
2. Click on the endpoint
3. See error

**Expected behavior**
Open the endpoint without error and ignore the invalid path  / reference

**Screenshots**
![image](https://user-images.githubusercontent.com/671670/72954800-5fbfda00-3d78-11ea-967b-4f4b5ad6f817.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (latest stable build)
 - Installation Method: EXE
 - App Version v7.0.6

**Additional context**
Nope.

**Comment by lukik** [comment]
Same case. Imported a collection from Postman and I get the same exact error when I click on a Request that has `form data`

Only way out is to Quit Insomnia as it brings up a blank pane that doesn't exit.

App Versions:

- OS: MacOS
- Installation Method: dmg
- App Version: V7.1.1


**Error Image**
<img width="763" alt="image" src="https://user-images.githubusercontent.com/3744924/75605996-843a6f00-5af9-11ea-814c-ff3a6a2bbae9.png">


**Blank Pane After the above Error**
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/3744924/75606001-99170280-5af9-11ea-8908-a5c416483fea.png">

**Comment by TristanWiley** [comment]
Same issue when trying to install a plugin, occurs on both my Mac and Linux machine. Works on my Windows machine

**Comment by valdineifer** [comment]
I also got a similar message when I try to "Copy as cURL":

> The "path" argument must be of type string. Received
an instance of Array

![image](https://user-images.githubusercontent.com/9989376/216363889-c57c2fd4-ca6a-47b8-bd21-1f7a75ca6f5c.png)

The similarities continue once that I also have my Insomnia project created by a Postman collection.

For me, Insomnia should convert empty fields (mine is `Array` when has no path) to null (or empty String, don't know) in import feature. That is the solution for this issue.
