### ISSUE TITLE
Clicking on the Tags of an OpenAPI document produces an Application Error

### ISSUE THREAD

**Issue by mdaniel** [getinsomnia/insomnia#2086]
**Describe the bug**
Clicking on the Tags of an OpenAPI document produces an `indexOf` error in `swagger-ui-react`

```
TypeError: Cannot read property 'indexOf' of undefined
    at value (webpack-internal:///../node_modules/swagger-ui-react/swagger-ui.js:8:71522)
    at eval (webpack-internal:///../node_modules/swagger-ui-react/swagger-ui.js:1:60457)
    at Connect.configureFinalMapState (webpack-internal:///../node_modules/swagger-ui-react/node_modules/react-redux/lib/components/connect.js:155:27)
    at Connect.configureFinalMapState (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js:708:25)
    at Connect.computeStateProps (webpack-internal:///../node_modules/swagger-ui-react/node_modules/react-redux/lib/components/connect.js:142:23)
    at Connect.computeStateProps (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js:708:25)
    at Connect.updateStatePropsIfNeeded (webpack-internal:///../node_modules/swagger-ui-react/node_modules/react-redux/lib/components/connect.js:204:35)
    at Connect.updateStatePropsIfNeeded (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js:708:25)
    at Connect.render (webpack-internal:///../node_modules/swagger-ui-react/node_modules/react-redux/lib/components/connect.js:340:40)
    at finishClassComponent (webpack-internal:///../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:14742:31)
    at updateClassComponent (webpack-internal:///../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:14697:24)
    at beginWork (webpack-internal:///../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:15645:16)
    at performUnitOfWork (webpack-internal:///../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:19313:12)
    at workLoop (webpack-internal:///../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:19353:24)
    at renderRoot (webpack-internal:///../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:19436:7)
    at performWorkOnRoot (webpack-internal:///../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:20343:7)
```

**To Reproduce**
1. `npm run app-start`
1. Click on "Petstore Example"
1. Click "Submit" (using the predefined URL)
1. Click Ok
1. Click on the "Swagger Petstore 1.0.2" box
1. Click on the top tag, labeled "pet (everything about your Pets)"
1. Receive the Application Error cited above

**Expected behavior**
Not producing an Application Error

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6, and also on Ubuntu 19.10
 - Installation Method: `git clone && git checkout designer && nvm use && npm run bootstrap && npm run app-start`
 - App Version: 03e5df69

**Additional context**

**Comment by develohpanda** [comment]
Thanks for your time in reporting this! If you pull the latest `develop`, it will contain https://github.com/Kong/insomnia/commit/0e7b96c868087c9a10ccfd3514152de193173a67 - this fixes what you are seeing. See #2061, the steps in there seem to line up with what you are seeing.

Closing as resolved! 🎉 😄

**Comment by mdaniel** [comment]
My apologies for the dupe, I tried searching for "indexOf" in the issues but regrettably didn't think to search for "petstore". Thanks for your quick response!

**Comment by develohpanda** [comment]
No worries! I must admit the original report ~is~ was... poorly named too. Guilty as charged. 🤣
