### ISSUE TITLE
Insomnia Designer, Documentation: Github token and scopes not documented

### ISSUE THREAD

**Issue by rmharrison** [getinsomnia/insomnia#2087]
**Describe the bug**
https://support.insomnia.rest/article/96-git-sync 
(Accessed 29 April 2020 22:17 ET)
should include sub-sections for major git providers: Savannah, Github, GitLab, BitBucket, etc.

_GitHub_
- Specify that you need to a ["Personal Access Token" ](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token)
- The required scope is `repo > public_repo`

**Root cause resolution**
I couldn't find your support docs hosted in github. Host them in a repo alongside the code, so the support and code are better able to remain in sync.

**Comment by nijikokun** [comment]
Thank you for raising this 🙌

**Comment by wdawson** [comment]
Sorry folks! This Issue was converted to Discussions by mistake as a Feature Request. I've moved it back here now where discussions can continue.

**Comment by wdawson** [comment]
@brookmg wrote in the Discussion:
> Is this fixed? I am getting different types of errors for different tokens

No, I don't believe we've updated the documentation yet. What types of issues are you seeing?

**Comment by brookmg** [comment]
Well I am currently getting 
```
[ErrorModal] TypeError: Cannot read property 'request' of undefined
    at Object.request (file:///C:/Users/hp/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:155876:27)
    at async Function.discover (C:\Users\hp\AppData\Local\insomnia\app-2021.4.1\resources\app.asar\node_modules\isomorphic-git\index.cjs:6514:13)
    at async _fetch (C:\Users\hp\AppData\Local\insomnia\app-2021.4.1\resources\app.asar\node_modules\isomorphic-git\index.cjs:7206:22)
    at async _clone (C:\Users\hp\AppData\Local\insomnia\app-2021.4.1\resources\app.asar\node_modules\isomorphic-git\index.cjs:7614:42)
    at async Object.clone (C:\Users\hp\AppData\Local\insomnia\app-2021.4.1\resources\app.asar\node_modules\isomorphic-git\index.cjs:7740:12)
    at async Object.shallowClone (file:///C:/Users/hp/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:285992:5)
    at async GitRepositorySettingsModal.onSubmitEdits [as _onSubmitEdits] (file:///C:/Users/hp/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:157596:25)
```
this is when I passed a token with all the permissions that seemed necessary. Previously I was getting a 501 error ( not implemented )

**Comment by brookmg** [comment]
I should also add that I'm trying to access an organization repo that belongs to me. It would be really good if you defined what permissions you need and the reasons with some scenarios to cover the usecase

**Comment by develohpanda** [comment]
Hi @brookmg, the issue you're seeing might be resolved by https://github.com/Kong/insomnia/pull/4097, which should be released with a new version of Insomnia soon.

Regarding the docs themselves, we've now moved our docs to an open-source repository, and there is a PR up to document the authentication scopes: https://github.com/Kong/insomnia-docs/pull/44. As such, I'll close this issue. 🎉
