### ISSUE TITLE
Error installing plugin on Insomnia Designer

### ISSUE THREAD

**Issue by aaronhmiller** [getinsomnia/insomnia#2117]
**Describe the bug**
Error when installing `insomnia-plugin-os` into Insomnia Designer

**To Reproduce**
1. go to Insomnia Designer menu, select Preferences
2. go to Plugins tab
3. enter "insomnia-plugin-os" into npm-package-name field
4. click "Install Plugin"
error results

**Expected behavior**
A working plugin is installed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Installation Method: dmg
 - App Version: Version 2020.1.3 (2020.1.3.3486)

**Additional context**
Here is the error returned:

```
insomnia-plugin-os install error: Command failed: /Applications/Insomnia\ Designer.app/Contents/Frameworks/Insomnia\ Designer\ Helper.app/Contents/MacOS/Insomnia\ Designer\ Helper --no-deprecation /Applications/Insomnia\ Designer.app/Contents/Resources/bin/yarn-standalone.js add insomnia-plugin-os --modules-folder /var/folders/z9/w9hpng594d34tftlkkf7_r_c0000gn/T/insomnia_2020.1.3/insomnia-plugin-os-1588698337000 --cwd /var/folders/z9/w9hpng594d34tftlkkf7_r_c0000gn/T/insomnia_2020.1.3/insomnia-plugin-os-1588698337000 --no-lockfile --production --no-progress
error /var/folders/z9/w9hpng594d34tftlkkf7_r_c0000gn/T/insomnia_2020.1.3/insomnia-plugin-os-1588698337000/jsonpath: Command failed.
Exit code: 1
Command: node lib/aesprim.js > generated/aesprim-browser.js
Arguments: 
Directory: /var/folders/z9/w9hpng594d34tftlkkf7_r_c0000gn/T/insomnia_2020.1.3/insomnia-plugin-os-1588698337000/jsonpath
Output:
internal/modules/cjs/loader.js:604
    throw err;
    ^

Error: Cannot find module 'esprima'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.<anonymous> (/private/var/folders/z9/w9hpng594d34tftlkkf7_r_c0000gn/T/insomnia_2020.1.3/insomnia-plugin-os-1588698337000/jsonpath/lib/aesprim.js:4:20)
    at Object.<anonymous> (/private/var/folders/z9/w9hpng594d34tftlkkf7_r_c0000gn/T/insomnia_2020.1.3/insomnia-plugin-os-1588698337000/jsonpath/lib/aesprim.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)```

**Comment by nijikokun** [comment]
Thanks for the report @aaronhmiller 🙏 

If you install twice does it happen both times? Sometimes npm can fail when installing a module, not the best error message to debug either! Going to try locally.

---

Looks like I can replicate, and attempting to install multiple time triggers the same error, definitely something going on with the package.

![image](https://user-images.githubusercontent.com/198276/81137847-eb6b0a00-8f14-11ea-950e-0b60bdccba2d.png)

**Comment by aaronhmiller** [comment]
tried this w/ Insomnia Designer 2020.2.0 and same results:

```
insomnia-plugin-os install error: Command failed: /Applications/Insomnia\ Designer.app/Contents/Frameworks/Insomnia\ Designer\ Helper.app/Contents/MacOS/Insomnia\ Designer\ Helper --no-deprecation /Applications/Insomnia\ Designer.app/Contents/Resources/bin/yarn-standalone.js add insomnia-plugin-os --modules-folder /var/folders/z9/w9hpng594d34tftlkkf7_r_c0000gn/T/insomnia_2020.2.0/insomnia-plugin-os-1591295303640 --cwd /var/folders/z9/w9hpng594d34tftlkkf7_r_c0000gn/T/insomnia_2020.2.0/insomnia-plugin-os-1591295303640 --no-lockfile --production --no-progress
error /var/folders/z9/w9hpng594d34tftlkkf7_r_c0000gn/T/insomnia_2020.2.0/insomnia-plugin-os-1591295303640/jsonpath: Command failed.
Exit code: 1
Command: node lib/aesprim.js > generated/aesprim-browser.js
Arguments: 
Directory: /var/folders/z9/w9hpng594d34tftlkkf7_r_c0000gn/T/insomnia_2020.2.0/insomnia-plugin-os-1591295303640/jsonpath
Output:
internal/modules/cjs/loader.js:604
    throw err;
    ^

Error: Cannot find module 'esprima'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.<anonymous> (/private/var/folders/z9/w9hpng594d34tftlkkf7_r_c0000gn/T/insomnia_2020.2.0/insomnia-plugin-os-1591295303640/jsonpath/lib/aesprim.js:4:20)
    at Object.<anonymous> (/private/var/folders/z9/w9hpng594d34tftlkkf7_r_c0000gn/T/insomnia_2020.2.0/insomnia-plugin-os-1591295303640/jsonpath/lib/aesprim.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
```

**Comment by nijikokun** [comment]
@aaronhmiller it's an issue with the plugin itself :(

**Comment by filfreire** [comment]
This has since been fixed, and should be working in [latest Insomnia stable release](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2).


<img width="782" alt="image" src="https://user-images.githubusercontent.com/11976836/180804546-0a713e10-fea9-4e8d-ae84-0cd8e8da6499.png">
