### ISSUE TITLE
Error message: Failed to render - send this error

### ISSUE THREAD

**Issue by Csardelacal** [getinsomnia/insomnia#2213]
Hey there,

I added a 'servers' entry to my openapi doc and insomnia designer is crashing with the following error:

```
TypeError: Cannot read property 'get' of null
    at t.value (file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:404546:118804)
    at Vh (file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:268061:198)
    at Zh (file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:268065:182)
    at file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:268095:268
    at Object.module.exports.exports.unstable_runWithPriority (file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:268151:163)
    at Fi (file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:268095:203)
    at Di (file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:268094:383)
    at Yh (file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:268093:144)
    at Gi (file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:268095:420)
    at Object.notify (file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:134807:7)
    at Subscription.notifyNestedSubs (file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:134849:20)
    at Provider.notifySubscribers (file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:268234:29)
    at Subscription.handleChangeWrapper (file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:134854:12)
    at dispatch (file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:53829:7)
    at file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:267519:16
    at file:///opt/Insomnia%20Designer/resources/app.asar/bundle.js:54071:12
```

I cannot open or export the YAML I've been writing on for the last 3 hours. 

**To Reproduce**
Open the document, duplicating it does the same

**Expected behavior**
The document should be displayed, at least the YAML

**Screenshots**
![Screenshot from 2020-05-25 16-58-06](https://user-images.githubusercontent.com/1152823/82824118-03e19b00-9ea9-11ea-96e0-45cb5eabfc1b.png)
![Screenshot from 2020-05-25 16-58-06](https://user-images.githubusercontent.com/1152823/82824175-24a9f080-9ea9-11ea-9864-78d8dd01477a.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Installation Method: RPM
 - App Version 2020.1.2

**Additional context**

**Comment by Csardelacal** [comment]
I would need help recovering at least the YAML file from designer. I cannot copy it out, edit it or try to recover the bug on my own.

**Comment by develohpanda** [comment]
Hi @Csardelacal - **your data should be safe**, from my experience this is only a render bug. The next release of Designer (potentially in the next week or so) will include #2131 which address this issue. The component used to preview the specification can be unstable in specific cases while writing a document, so this PR adds an error boundary around it to catch any errors.

If you need to extract that document earlier, feel free to ping me on [Slack](https://chat.insomnia.rest/). 🤗

**Comment by gschier** [comment]
You can view Insomnia's app data directory from Help > Show App Data Folder. Your specification will be contained within the `insomnia.ApiSpec.db` file if you want to fish it out for now. In the meantime, we're working on getting an update out ASAP.

**Comment by develohpanda** [comment]
[Designer v2020.2.0](https://github.com/Kong/insomnia/releases/tag/designer%402020.2.0) has now been released, which contains the fix for this. 😄
