### ISSUE TITLE
robotjs problem with glibc

### ISSUE THREAD

**Issue by ali2560** [getinsomnia/insomnia#2521]
I've been install robotjs on ubuntu 20.04 and require it my nodejs application. Also i've been install glibc 2.31 version. but when i want to run my application, i watch error below:

internal/modules/cjs/loader.js:1187
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by /lib/x86_64-linux-gnu/libX11.so.6)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/Project/node_modules/robotjs/index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)

**Comment by nijikokun** [comment]
Welcome @ali2560 

I think you may have submitted the issue to the wrong repository as this is the `insomnia` repository, not the [`robotjs` repository](https://github.com/octalmage/robotjs).
