### ISSUE TITLE
Installing Plugins fails with npm error

### ISSUE THREAD

**Issue by dschulten** [getinsomnia/insomnia#2656]
**Describe the bug**
I try to install insomnia-plugin-run-folder from Preferences-Plugins (or any other plugin).
I have entered proxy configuration to be able to access the internet. Insomnia can update just fine via the proxy.
The proxy configuration includes no_proxy settings for localhost, 127.0.0.1 and my local domain.

**To Reproduce**

Behind a corporate proxy (squid without credentials):

1. Go to 'Preferences-Plugins'
2. Enter "insomnia-plugin-run-folder"
2. Click on 'Install Plugin'

**Expected behavior**
Plugin works

**Screenshots**
None

**Error**
```
Error: Yarn error {"type":"error","data":"Received invalid response from npm."}

    at file:///C:/Users/Schulten/AppData/Local/insomnia/app-2020.4.0/resources/app.asar/bundle.js:99476:16
    at ChildProcess.exithandler (child_process.js:295:7)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Desktop (please complete the following information):**
 - OS: Win 10
 - Installation Method: Download and execute
 - App Version 2020.4.0

**Additional context**
I have also tried to install from the plugin hub. I get the same error message.
Moreover I have tried several plugins, always the same result.

**Comment by develohpanda** [comment]
Because we are using a version of `yarn` bundled within Insomnia to enable plugin installation, it does not respect the proxy settings. You can however, go directly into the plugins directory and install your plugin, if you have your global installation of npm or yarn following proxy rules - see https://github.com/Kong/insomnia/issues/1613#issuecomment-695949299.

**Comment by elenigen** [comment]
I also have this issue with version `2021.7.0`

**Comment by byjrack** [comment]
Add another to the repro list. 

Couple ways to mitigate I have found:

- If a user has NPM installed and https-proxy configured Insomnia client/yarn seemed to use that to do the install from the UI.
  - Not 100% on that, but it's the biggest correlated difference when comparing those who work and those who don't.  
- npm install in /plugins will work
  - some users don't have NPM installed so it can get more complicated for them.  And downloading the tarball won't work since the dependencies won't be pulled in.
    - I used an archive created by someone with NPM to do the install, but thats not a great option long term.

**Comment by txd458** [comment]
I was able to find success by instructing Yarn to use my system CA file by running the following:
_node /opt/Insomnia/resources/bin/yarn-standalone.js config set cafile "/path-to-your-ca-file"_
