### ISSUE TITLE
Error when importing Swagger 2.0 json file

### ISSUE THREAD

**Issue by anno1985** [getinsomnia/insomnia#2780]
**Describe the bug**
When trying to import a Swagger 2.0 json file, I get the following error:

> The file does not contain a valid specification.

StackTrace
```
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type undefined
    at Hash.update (internal/crypto/hash.js:70:11)
    at importFolderItem (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/src/importers/swagger2.js:161:6)
    at /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/src/importers/swagger2.js:129:12
    at Array.map (<anonymous>)
    at parseEndpoints (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/src/importers/swagger2.js:128:46)
    at Object.module.exports.convert (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/src/importers/swagger2.js:68:21)
    at async module.exports.convert (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/index.js:19:23)
    at async importRaw (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:42846:15)
    at async Object.importUri (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:42808:18)
    at async file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:79047:24
```

**Expected behavior**
File should import without issues.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - App Version: 2020.4.1

**Additional context**
- The Swagger Editor does find several warnings, but no errors, so the file should parse.
- The file is in JSON format, not YAML.

**Comment by jceb** [comment]
Same issue here with a YAML file. I was able to import the very same file into swagger.io without any issues.

Version: Insomnia Core 2020.4.2
Release date: 10/21/2020
OS: Linux x64 5.4.72-1-lts
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libssh2/1.9.0 nghttp2/1.41.0

The import still works with version 2020.3.3.

**Comment by reynolek** [comment]
Hi @jceb, thanks for the bug report! is it possible to provide the swagger file in question? Or perhaps a swagger file that allows us to reproduce the error?

```
The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type undefined
```

The stack trace providing this error message is pretty tough to make assumptions about where the issue may lie, other than in some key `data`.

**Comment by jceb** [comment]
Here you go: https://0bin.net/paste/UYLRsCQJ#sDTz4VgqF1zP315VNTLRYUAESUh5wfhc5o9UpgHCDvR

**Comment by zbuc** [comment]
I am having the same problem. There is no `data` key in my Swagger 2.0 file but it's (AFAIK) a valid file; other parsers like the one Connexion uses work on my API definition.

Minimal example:

```yaml
swagger: '2.0'
info:
  title: Test API
  version: "1.0"
consumes:
  - application/json
produces:
  - application/json
basePath: /v1.0
schemes: [http]

# PATHS
paths:
  /health:
    get:
      summary: Get API health
      responses:
        200:
          description: Return JSON with API health information
          schema:
            $ref: '#/definitions/response_health'

definitions:
  response_health:
    type: object
    required:
      - status
    properties:
      status:
        type: string
        description: whether query succeeded
    example:
        status: "OK"
```

**Comment by johnbillion** [comment]
I'm seeing this problem too. Notably I can get around it by creating a blank document and then pasting the schema into the main editor, instead of trying to import the schema.

**Comment by avevlad** [comment]
Workaround:

1. open http://editor.swagger.io/
2. paste existing swagger2 test -input file
3. (transform JSON->YAML when asked, if necessary)
4. Edit > Convert to OpenAPI 3
5. export (as JSON or YAML, depending on existing test)

**Comment by little-fish** [comment]
up!

**Comment by thewheat** [comment]
Saving the test file in https://github.com/Kong/insomnia/issues/2780#issuecomment-731863171 I am able to import without errors

I'm not familiar enough with how Insomnia imports Swagger files to know if it has fully imported everything though


![image](https://user-images.githubusercontent.com/892961/136546010-12daa996-c143-45ce-96ee-af501a52126e.png)

**Imported Design Doc**
![image](https://user-images.githubusercontent.com/892961/136546039-07532e2e-f6c8-4573-8258-3d67389b2937.png)

**Imported Request Collection**
![image](https://user-images.githubusercontent.com/892961/136545972-74e3cfd4-c4dc-4ced-8f1f-cd9cc328ce77.png)

**Comment by jceb** [comment]
Same here, the error got solved.
