### ISSUE TITLE
JSON Path Filter Expression caused Insomnia to throw and exception

### ISSUE THREAD

**Issue by mobsoftware** [getinsomnia/insomnia#2945]
I was editing an array condition (e.g. `$..Items[?(@.Property == 'value1'` <trying to use multiple conditions but didn't work and got an exception while trying

```js
> )]..ChildItems

TypeError: Cannot read property 'lastIndexOf' of undefined
    at findOpening (file:///C:/Users/UserName/AppData/Local/insomnia/app-2020.5.2/resources/app.asar/bundle.js:212749:43)
    at Array.<anonymous> (file:///C:/Users/[UserName]/AppData/Local/insomnia/app-2020.5.2/resources/app.asar/bundle.js:212763:51)
    at file:///C:/Users/[username]/AppData/Local/insomnia/app-2020.5.2/resources/app.asar/bundle.js:132464:27
    at getRange (file:///C:/Users/[UserName]/AppData/Local/insomnia/app-2020.5.2/resources/app.asar/bundle.js:132359:19)
    at doFold (file:///C:/Users/[UserName]/AppData/Local/insomnia/app-2020.5.2/resources/app.asar/bundle.js:132372:17)
    at CodeMirror.foldCode (file:///C:/Users/[UserName]/AppData/Local/insomnia/app-2020.5.2/resources/app.asar/bundle.js:132420:5)
    at CodeEditor._restoreState (file:///C:/Users/[UserName]/AppData/Local/insomnia/app-2020.5.2/resources/app.asar/bundle.js:34075:23)
    at CodeEditor.componentDidUpdate (file:///C:/Users/[UserName]/AppData/Local/insomnia/app-2020.5.2/resources/app.asar/bundle.js:33848:12)
    at Ji (file:///C:/Users/[UserName]/AppData/Local/insomnia/app-2020.5.2/resources/app.asar/bundle.js:206155:231)
    at Sj (file:///C:/Users/[UserName]/AppData/Local/insomnia/app-2020.5.2/resources/app.asar/bundle.js:206198:229)```

**Comment by develohpanda** [comment]
It's great to see some reproduction steps for this - I _believe_ it is fixed by #2840 and was reported in #2805. That fix should be out with the next release likely early 2021, so I'll leave this open for now.

If you are able to consistently reproduce this, I'd be happy to create an alpha build for you to validate, since this has been difficult to reproduce on my end.
