### ISSUE TITLE
Error rendering request pane

### ISSUE THREAD

**Issue by willtj** [getinsomnia/insomnia#3084]
**Describe the bug**
The app reported an error in rendering the request pane after pasting a Curl request.

**To Reproduce**
I haven't been able to reproduce this following the same steps, but the original steps were:
1. Go to an existing request
2. Select the whole URL and paste a full curl request in its place
3. Repeat step 2 to work around #3002 
```
TypeError: Cannot read property 'lastIndexOf' of undefined
at findOpening (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:212749:43)
at Array.<anonymous> (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:212763:51)
at file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:132464:27
at getRange (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:132359:19)
at doFold (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:132372:17)
at CodeMirror.foldCode (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:132420:5)
at CodeEditor._restoreState (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:34075:23)
at setup (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:34184:12)
at CodeEditor._handleInitTextarea (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:34191:7)
at Sj (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:206198:383)
```

**Expected behavior**
The curl request should have been imported without any exception.

**Screenshots**
I didn't get one, sorry.

**Desktop (please complete the following information):**
 - OS: macOS 11.2
 - Installation Method: dmg
 - App Version Insomnia Core 2020.5.2

**Comment by filfreire** [comment]
HI @willtj I'm not able to reproduce this in our [latest beta build](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.1). Feel free to reopen this issue if you are still able to reproduce it and have more details on how to reproduce.

In any case, thank you for reporting this and I encourage you also to report any other problem you find!
