### ISSUE TITLE
Git integration does not work

### ISSUE THREAD

**Issue by sebastianbuechler** [getinsomnia/insomnia#3185]
**I migrated to the new Insomnia and Git integration does not work anymore**
I have a git repo with insomnia files arleady in there. When I add it to the new insomnia client (fresh installaion) it seems to work, but I can not pull any branch, although I see all the branches under "Branches".

**To Reproduce**
1. Open Insomnia
2. Select the default project
3. Click on Add Git Sync
4. Fill out credentials
5. Select dev branch
6. Pull
7. Error: Could not expand reference "dev".

**Expected behavior**
The dev branch should show up and I should be able to push the new configuration.

**Desktop (please complete the following information):**
 - OS: Win 10 Pro, latest
 - Installation Method: Windows Installer, taken today
 - App Version: Insomnia 2021.1.1

**Additional context**
Stack trace of the error:
```
ExpandRefError: Could not expand reference "dev".
    at Function.expand (C:\Users\SB\AppData\Local\insomnia\app-2021.1.1\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:2199:11)
    at async merge (C:\Users\SB\AppData\Local\insomnia\app-2021.1.1\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:9590:12)
    at async Object.pull (C:\Users\SB\AppData\Local\insomnia\app-2021.1.1\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:9913:5)
    at async GitSyncDropdown._handlePull (file:///C:/Users/SB/AppData/Local/insomnia/app-2021.1.1/resources/app.asar/bundle.js:203367:7)

```

**Comment by nijikokun** [comment]
This is one of the items at the top of our backlog at the moment which is currently blocked from being worked on by #3111 being merged.

**Comment by wongstein** [comment]
Hi, we've recently done some more work on git sync.  Can you still reproduce this error with the latest version?

**Comment by sebastianbuechler** [comment]
@wongstein Hi, sorry we already switched to another solution.
