### ISSUE TITLE
Failed to render RequestPane

### ISSUE THREAD

**Issue by vaibhavkapoor27** [getinsomnia/insomnia#3302]
i was following instructions as listed here.
https://github.com/ryanprior/conjur-api-insomnia

i was able to reproduce this bug again.

TypeError: Cannot read property 'type' of null
at RequestPane.render (file:///C:/Users/Administrator/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:191998:114)
at gi (file:///C:/Users/Administrator/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:205694:192)
at fi (file:///C:/Users/Administrator/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:205693:224)
at Rj (file:///C:/Users/Administrator/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:205775:490)
at Qj (file:///C:/Users/Administrator/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:205758:199)
at Kj (file:///C:/Users/Administrator/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:205758:128)
at yj (file:///C:/Users/Administrator/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:205751:172)
at file:///C:/Users/Administrator/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:205635:115
at module.exports.exports.unstable_runWithPriority (file:///C:/Users/Administrator/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:205842:467)
at cg (file:///C:/Users/Administrator/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:205634:325)

**Comment by filfreire** [comment]
Hi @vaibhavkapoor27, apologies for not replying sooner.

I am also able to reproduce this one, even on the latest Insomnia build (e.g. `2022.4.0-beta.0`).

Importing via URL (https://raw.githubusercontent.com/ryanprior/conjur-api-insomnia/master/Conjur.org.json )

Stacktrace:
```
TypeError: Cannot read properties of null (reading 'type')
    at jbt (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.dc0fa857.js:4923:10830)
    at w5 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.dc0fa857.js:30:53297)
    at Eoe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.dc0fa857.js:34:8857)
    at yoe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.dc0fa857.js:34:964)
    at $xe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.dc0fa857.js:34:887)
    at VA (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.dc0fa857.js:34:737)
    at EL (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.dc0fa857.js:32:10947)
    at am (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.dc0fa857.js:32:8466)
    at PI (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.dc0fa857.js:34:15965)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.dc0fa857.js:34:17629
```
<img width="772" alt="Screen Shot 2022-05-10 at 07 48 59" src="https://user-images.githubusercontent.com/11976836/167565685-c94d690a-6a26-406d-9fa1-8e51d65b688a.png">
<img width="726" alt="Screen Shot 2022-05-10 at 07 49 06" src="https://user-images.githubusercontent.com/11976836/167565700-899a76bd-5e83-43c3-81e6-5692199104d4.png">
