### ISSUE TITLE
[Error] Auto update  to latest version 

### ISSUE THREAD

**Issue by usuresh80** [getinsomnia/insomnia#345]
right now I have v 5.3.6 ,  earlier version used to get update automatically , but these days I see below error and version is not getting updated 

<details>
<summary>Debug Log</summary>

```
2017-07-05 11:43:14> Program: Starting Squirrel Updater: --processStart Insomnia.exe
2017-07-05 11:43:14> Program: Want to launch 'C:\Users\suppala\AppData\Local\insomnia\app-5.3.6\Insomnia.exe'
2017-07-05 11:43:14> Program: About to launch: 'C:\Users\suppala\AppData\Local\insomnia\app-5.3.6\Insomnia.exe': 
2017-07-05 11:43:15> Program: Starting Squirrel Updater: --download https://updates.insomnia.rest/updates/win?v=5.3.6
2017-07-05 11:43:15> Program: Fetching update information, downloading from https://updates.insomnia.rest/updates/win?v=5.3.6
2017-07-05 11:43:15> CheckForUpdateImpl: Using existing staging user ID: f6a39e6e-4e04-5ec4-a80b-b5db26cd73f7
2017-07-05 11:43:15> CheckForUpdateImpl: Downloading RELEASES file from https://updates.insomnia.rest/updates/win?v=5.3.6
2017-07-05 11:43:15> FileDownloader: Downloading url: https://updates.insomnia.rest/updates/win/RELEASES?v=5.3.6&id=insomnia&localVersion=5.3.6&arch=amd64
2017-07-05 11:43:18> IEnableLogger: Failed to download url: https://updates.insomnia.rest/updates/win/RELEASES?v=5.3.6&id=insomnia&localVersion=5.3.6&arch=amd64: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2017-07-05 11:43:18> FileDownloader: Downloading url: https://updates.insomnia.rest/updates/win/releases?v=5.3.6&id=insomnia&localversion=5.3.6&arch=amd64
2017-07-05 11:43:18> IEnableLogger: Failed to download url: https://updates.insomnia.rest/updates/win/releases?v=5.3.6&id=insomnia&localversion=5.3.6&arch=amd64: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2017-07-05 11:43:18> CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-07-05 11:43:18> FileDownloader: Downloading url: https://updates.insomnia.rest/updates/win/RELEASES?v=5.3.6&id=insomnia&localVersion=5.3.6&arch=amd64
2017-07-05 11:43:18> IEnableLogger: Failed to download url: https://updates.insomnia.rest/updates/win/RELEASES?v=5.3.6&id=insomnia&localVersion=5.3.6&arch=amd64: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2017-07-05 11:43:18> FileDownloader: Downloading url: https://updates.insomnia.rest/updates/win/releases?v=5.3.6&id=insomnia&localversion=5.3.6&arch=amd64
2017-07-05 11:43:18> IEnableLogger: Failed to download url: https://updates.insomnia.rest/updates/win/releases?v=5.3.6&id=insomnia&localversion=5.3.6&arch=amd64: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2017-07-05 11:43:18> CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-07-05 11:43:18> FileDownloader: Downloading url: https://updates.insomnia.rest/updates/win/RELEASES?v=5.3.6&id=insomnia&localVersion=5.3.6&arch=amd64
2017-07-05 11:43:18> IEnableLogger: Failed to download url: https://updates.insomnia.rest/updates/win/RELEASES?v=5.3.6&id=insomnia&localVersion=5.3.6&arch=amd64: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2017-07-05 11:43:18> FileDownloader: Downloading url: https://updates.insomnia.rest/updates/win/releases?v=5.3.6&id=insomnia&localversion=5.3.6&arch=amd64
2017-07-05 11:43:18> IEnableLogger: Failed to download url: https://updates.insomnia.rest/updates/win/releases?v=5.3.6&id=insomnia&localversion=5.3.6&arch=amd64: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2017-07-05 11:43:18> CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

</details>

**Comment by gschier** [comment]
Hey @usuresh80, thanks for the report. I can't seem to reproduce this on my Windows 10 VM. Here is my update log going from 5.2.0 to 5.5.2.

```
2017-07-05 11:48:18> Program: Starting Squirrel Updater: --download https://updates.insomnia.rest/updates/win?v=5.2.0
2017-07-05 11:48:18> Program: Fetching update information, downloading from https://updates.insomnia.rest/updates/win?v=5.2.0
2017-07-05 11:48:18> CheckForUpdateImpl: Using existing staging user ID: 0d7a2b17-2136-56f1-9345-be7783df1498
2017-07-05 11:48:18> CheckForUpdateImpl: Downloading RELEASES file from https://updates.insomnia.rest/updates/win?v=5.2.0
2017-07-05 11:48:19> FileDownloader: Downloading url: https://updates.insomnia.rest/updates/win/RELEASES?v=5.2.0&id=insomnia&localVersion=5.2.0&arch=amd64
2017-07-05 11:48:20> FileDownloader: Downloading file: https://updates.insomnia.rest/updates/win/insomnia-5.5.2-full.nupkg
```

Your log states that it is failing to download `https://updates.insomnia.rest/updates/win/RELEASES` because `Could not create SSL/TLS secure channel`. Are you able to download this file from your web browser successfully?

**Comment by gschier** [comment]
I suggest reinstalling the app from the [website](https://insomnia.rest/download/) if you can't get it working (your data won't be deleted).

If other people seem to be having the same problem I might take a closer look, but this error is originating from the Squirrel auto-update framework which Insomnia does not control 😢
