### ISSUE TITLE
I can't make any requests, I get this error

### ISSUE THREAD

**Issue by leonardo-bispoo** [getinsomnia/insomnia#3790]
```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ig (file:///opt/Insomnia/resources/app.asar/bundle.js:206438:46)
    at Object.enqueueSetState (file:///opt/Insomnia/resources/app.asar/bundle.js:206340:237)
    at ResponseTimer.module.exports.F.setState (file:///opt/Insomnia/resources/app.asar/bundle.js:206188:369)
    at ResponseTimer._handleUpdateElapsedTime (file:///opt/Insomnia/resources/app.asar/bundle.js:123912:10)
    at ResponseTimer.componentDidUpdate (file:///opt/Insomnia/resources/app.asar/bundle.js:123931:10)
    at Ji (file:///opt/Insomnia/resources/app.asar/bundle.js:206420:231)
    at Sj (file:///opt/Insomnia/resources/app.asar/bundle.js:206463:229)
    at module.exports.exports.unstable_runWithPriority (file:///opt/Insomnia/resources/app.asar/bundle.js:206538:467)
    at cg (file:///opt/Insomnia/resources/app.asar/bundle.js:206330:325)
    at Jj (file:///opt/Insomnia/resources/app.asar/bundle.js:206456:370) 
```

**Expected behavior**
I wait for the response from the route, tested it with other applications and it worked

**Desktop (please complete the following information):**
 - OS: Debian 10 Buster
 - Installation Method: Snap
 - App Version: 2021.3.0

**Comment by dimitropoulos** [comment]
With the information above it's hard to say what we do next.  Do you have any ideas on how we might reproduce this?

**Comment by leonardo-bispoo** [comment]
I have no idea how to reproduce the same error, I didn't change any settings, I was just making the requests.
On the same day I saw that my application was out of date, and I upgraded to version 2021.4.0 and the error no longer occurred.

**Comment by dimitropoulos** [comment]
now THERE is something I can relate to. haha.  I totally understand.  If you find this happening again or something changes please don't hesitate to ping us again.  We're here.
