### ISSUE TITLE
Cannot read property 'lastIndexOf' of undefined

### ISSUE THREAD

**Issue by vasudevk** [getinsomnia/insomnia#3805]
`TypeError: Cannot read property 'lastIndexOf' of undefined
    at findOpening (file:///C:/Users/Vasu/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:198791:43)
    at Array.<anonymous> (file:///C:/Users/Vasu/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:198805:20)
    at file:///C:/Users/Vasu/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:122288:27
    at getRange (file:///C:/Users/Vasu/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:122183:19)
    at doFold (file:///C:/Users/Vasu/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:122196:17)
    at CodeMirror.foldCode (file:///C:/Users/Vasu/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:122244:5)
    at CodeEditor._restoreState (file:///C:/Users/Vasu/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:43700:29)
    at CodeEditor.componentDidUpdate (file:///C:/Users/Vasu/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:43484:18)
    at Ji (file:///C:/Users/Vasu/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:184043:231)
    at Sj (file:///C:/Users/Vasu/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:184086:229)`

**Comment by roguib** [comment]
With that information is difficult to understand what's happening. Can you elaborate on what you're doing when you encountered that error?

**Comment by filfreire** [comment]
Hi @vasudevk, thanks for reporting. Same as @roguib it would be good to know what was happening when the error occurred. In any case, I see this is for last years version of Insomnia, and we have since done a lot of changes that fixed similar TypeErrors.

Feel free to open a new issue with more details if you still notice any problems.
