### ISSUE TITLE
"HTTP Error: 500 handshakefailed" during Setup of Git Sync

### ISSUE THREAD

**Issue by higgs01** [getinsomnia/insomnia#3944]
**Describe the bug**
While configuring Git Sync for a Design Document i get following error: 
```
HTTP Error: 500 handshakefailed

HttpError: HTTP Error: 500 handshakefailed
    at Function.discover (C:\Users\AXLWU01\AppData\Local\insomnia\app-2021.4.1\resources\app.asar\node_modules\isomorphic-git\index.cjs:6556:13)
    at async _fetch (C:\Users\AXLWU01\AppData\Local\insomnia\app-2021.4.1\resources\app.asar\node_modules\isomorphic-git\index.cjs:7206:22)
    at async _clone (C:\Users\AXLWU01\AppData\Local\insomnia\app-2021.4.1\resources\app.asar\node_modules\isomorphic-git\index.cjs:7614:42)
    at async Object.clone (C:\Users\AXLWU01\AppData\Local\insomnia\app-2021.4.1\resources\app.asar\node_modules\isomorphic-git\index.cjs:7740:12)
    at async Object.shallowClone (file:///C:/Users/AXLWU01/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:285992:5)
    at async GitRepositorySettingsModal.onSubmitEdits [as _onSubmitEdits] (file:///C:/Users/AXLWU01/AppData/Local/insomnia/app-2021.4.1/resources/app.asar/bundle.js:157596:25)
```

**To Reproduce**
1. Open a Design Document
2. Click "Setup Git Sync"
3. Fill in credentials and git url
4. click "Done"

**Screenshot**
![image](https://user-images.githubusercontent.com/6546697/130778683-f62f4c28-916b-4f76-a7b3-ae8a6dfe7e59.png)
![image](https://user-images.githubusercontent.com/6546697/130778757-07721aa0-4af1-4dc6-a3ac-db08f3ed7919.png)

**Expected behavior**
Git Sync is setup sucessfully

**Desktop (please complete the following information):**
 - OS: Windows 10 10.0.17763
 - Installation Method: installer
 - App Version: 2021.4.1 and 2021.5.0-alpha.2

**Additional context**
We're using a selfhosted GitLab and the connection to gitlab from my client is through a SSL-Terminating proxy. Normal git-operations using git-cli, git-fork or visual studio code are successful. My local git installation is configured to use this proxy and the proxy is configured in Insomnia aswell (HTTP-Requests using Insomnia work).

**Comment by filfreire** [comment]
Hi @higgs01, thank you for reporting this!

We will need to investigate this further, but are you by any chance still able to reproduce this using latest [Insomnia release](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0)?

**Comment by gatzjames** [comment]
Closing as Git should respect the system proxy settings in the latest version
