### ISSUE TITLE
Render Failure: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by godwinrob** [getinsomnia/insomnia#3986]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 20H2

### Installation method

Windows install

### Expected Behavior

When swapping between gRPC and REST calls I expect them to render properly.

### Actual Behavior

The entire section fails to render until insomnia is restarted

### Reproduction Steps

I am having issues reproducing this after first opening insomnia but am running into it constantly as I work moving old rest calls into gRPC calls 

1. Open an existing collection with post REST calls and gRPC calls
2. Use software for a little while
3. Right click collection and Create a new gRPC request
4. Name Request and click create
4. select proto file and click save
5. Click on a separate POST or GET request in the collection and error will pop up

### Additional Information

![insomniaerror](https://user-images.githubusercontent.com/17951154/131551876-f625ab53-daa2-458b-888a-030ec2ff49ed.PNG)

**Comment by dimitropoulos** [comment]
I was unable to reproduce.  Does this happen if you try with a brand new collection?  I used https://raw.githubusercontent.com/moul/pb/master/hello/hello.proto, as an aside.

If it is reproducible for you, is it possible for you to share an export of this collection?

When you open your console, could you please share the stack trace for this error?  This is 3rd party code that's erroring, so I wasn't able (with the information provided in the error) find anything in our code that is likely to be causing this.

**Comment by godwinrob** [comment]
Thanks for the follow up. I'll try to play around with hello.proto and see if I have any luck with reproduction

**Comment by polaroi8d** [comment]
I got the same error, with proto files. 

```
Version: Insomnia 2022.2.0
Release date: 3/17/2022
OS: Darwin arm64 21.3.0
Electron: 17.1.0
Node: 16.13.0
V8: 9.8.177.11-electron.0
Architecture: arm64
```

**Comment by gabrielrra** [comment]
I found a way to reproduce this bug.
Import [this JSON](https://gist.github.com/gabrielrra/6f4c4de1cc72504c2037ac6d7d6b0303) to insomnia and you will have 4 things:

- 2 proto files (file_1.proto and file_2.proto) that are exactly the same
- A grpc request
- An http request

Steps to reproduce:

1. Choose the gRPC request and click on the select box to select the proto file
2. Select the proto file and click on the box again to select the method
3. Repeat the steps before but choosing the **other** proto file
4. Select the http request and you should get an error

If you don't get the error keep changing the proto file and method several times in a row before changing to http request.

**Comment by gabrielrra** [comment]
When debugging I found the following error:
```
[app] 09:21:03.348 › The above error occurred in the <Tooltip> component:
[app]     in Tooltip (created by GrpcMethodDropdownButton)
[app]     in button (created by Context.Consumer)
[app]     in StyledComponent (created by StyledButton)
[app]     in StyledButton (created by Button)
[app]     in Button (created by GrpcMethodDropdownButton)
[app]     in GrpcMethodDropdownButton (created by GrpcMethodDropdown)
[app]     in div (created by Context.Consumer)
[app]     in StyledComponent (created by StyledDropdown)
[app]     in StyledDropdown (created by Dropdown)
[app]     in Dropdown (created by GrpcMethodDropdown)
[app]     in GrpcMethodDropdown (created by GrpcRequestPane)
[app]     in div (created by Context.Consumer)
[app]     in StyledComponent (created by styled.div)
[app]     in styled.div (created by GrpcRequestPane)
[app]     in div (created by Context.Consumer)
[app]     in StyledComponent (created by styled.div)
[app]     in styled.div (created by GrpcRequestPane)
[app]     in header (created by PaneHeader)
[app]     in PaneHeader (created by GrpcRequestPane)
[app]     in section (created by Pane)
[app]     in Pane (created by GrpcRequestPane)
[app]     in KeydownBinder (created by GrpcRequestPane)
[app]     in GrpcRequestPane (created by PageLayout)
[app]     in SingleErrorBoundary (created by ErrorBoundary)
[app]     in ErrorBoundary (created by PageLayout)
[app]     in section (created by ForwardRef(Pane))
[app]     in ForwardRef(Pane) (created by PageLayout)
[app]     in SingleErrorBoundary (created by ErrorBoundary)
[app]     in ErrorBoundary (created by PageLayout)
[app]     in div (created by PageLayout)
[app]     in PageLayout (created by UnconnectedWrapperDebug)
[app]     in UnconnectedWrapperDebug (created by Connect(UnconnectedWrapperDebug))
[app]     in Connect(UnconnectedWrapperDebug) (created by Wrapper)
[app]     in Wrapper (created by App)
[app]     in SingleErrorBoundary (created by ErrorBoundary)
[app]     in ErrorBoundary (created by App)
[app]     in div (created by App)
[app]     in NunjucksEnabledProvider (created by App)
[app]     in GrpcProvider (created by App)
[app]     in KeydownBinder (created by App)
[app]     in App (created by DragDropContext(App))
[app]     in DragDropContext(App) (created by Connect(DragDropContext(App)))
[app]     in Connect(DragDropContext(App))
[app]     in Provider
[app] 
[app] React will try to recreate this component tree from scratch using the error boundary you provided, SingleErrorBoundary.
[app] 09:21:03.354 › [ErrorModal] Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
[app]     at Tooltip._removeBubbleFromBody (webpack-internal:///../../insomnia-components/dist/index.js:8922:40)
[app]     at Tooltip.componentWillUnmount (webpack-internal:///../../insomnia-components/dist/index.js:8941:14)
[app]     at callComponentWillUnmountWithTimer (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:19580:12)
[app]     at HTMLUnknownElement.callCallback (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:188:14)
[app]     at Object.invokeGuardedCallbackDev (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:237:16)
[app]     at invokeGuardedCallback (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:292:31)
[app]     at safelyCallComponentWillUnmount (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:19587:5)
[app]     at commitUnmount (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:20109:11)
[app]     at commitNestedUnmounts (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:20163:5)
[app]     at unmountHostComponents (webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js:20443:7)
[app] 09:21:03.422 › Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
[app]     in RenderedQueryString (created by RequestPane)
[app]     in SingleErrorBoundary (created by ErrorBoundary)
[app]     in ErrorBoundary (created by RequestPane)
[app]     in code (created by RequestPane)
[app]     in div (created by RequestPane)
[app]     in div (created by TabPanel)
[app]     in TabPanel (created by RequestPane)
[app]     in div (created by UncontrolledTabs)
[app]     in UncontrolledTabs (created by Tabs)
[app]     in Tabs (created by RequestPane)
[app]     in section (created by Pane)
[app]     in Pane (created by RequestPane)
[app]     in RequestPane (created by PageLayout)
[app] 09:21:03.476 › Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
[app]     in KeyValueEditor (created by RequestHeadersEditor)
[app]     in div (created by RequestHeadersEditor)
[app]     in div (created by RequestHeadersEditor)
[app]     in RequestHeadersEditor (created by RequestPane)
[app]     in SingleErrorBoundary (created by ErrorBoundary)
[app]     in ErrorBoundary (created by RequestPane)
[app]     in div (created by TabPanel)
[app]     in TabPanel (created by RequestPane)
[app]     in div (created by UncontrolledTabs)
[app]     in UncontrolledTabs (created by Tabs)
[app]     in Tabs (created by RequestPane)
[app]     in section (created by Pane)
[app]     in Pane (created by RequestPane)
[app]     in RequestPane (created by PageLayout)
```

**Comment by victorradael** [comment]
This error occurs to me several times a day.
