### ISSUE TITLE
[Development] npm run dev doesn't work

### ISSUE THREAD

**Issue by elcergey** [getinsomnia/insomnia#408]
When building the app using "npm run build", it runs correctly. When trying to run command "npm run dev", it launches the app but stays forever like "Waiting for build server. The initial build can take over a minute on slower hardware". What could be wrong ?

I have the following log output. One thing that bothers me is message "compiled with warnings".

<details>
<summary>Console Output</summary>

```
> insomnia@1.0.0 dev C:\CODE\JS\insomnia
> concurrently --kill-others "npm run hot-server" "npm run start-hot"

[1] 
[1] > insomnia@1.0.0 start-hot C:\CODE\JS\insomnia
[1] > npm run build-main && cross-env HOT=1 INSOMNIA_ENV=development electron app
[1] 
[0] 
[0] > insomnia@1.0.0 hot-server C:\CODE\JS\insomnia
[0] > webpack-dev-server --config ./webpack/webpack.config.development.babel.js
[0] 
[1] 
[1] > insomnia@1.0.0 build-main C:\CODE\JS\insomnia
[1] > cross-env NODE_ENV=development webpack --config ./webpack/webpack.config.electron.babel.js
[1] 
[0] Project is running at http://localhost:3333/
[0] webpack output is served from http://localhost:3333/
[1] Hash: 8a15006ebffb32139561
[1] Version: webpack 2.7.0
[1] Time: 2746ms
[1]       Asset    Size  Chunks             Chunk Names
[1] main.min.js  155 kB       0  [emitted]  main
[1]    [1] ./common/constants.js 26.7 kB {0} [built]
[1]    [4] ./main.development.js 3.21 kB {0} [built]
[1]    [5] ./package.json 823 bytes {0} [built]
[1]    [6] ./common/local-storage.js 1.94 kB {0} [built]
[1]    [7] ./main/error-handling.js 332 bytes {0} [built]
[1]    [8] ./main/updates.js 2.96 kB {0} [built]
[1]    [9] ./main/window-utils.js 12.3 kB {0} [built]
[1]   [14] multi ./main.development.js 28 bytes {0} [built]
[1]     + 7 hidden modules
[1] 
[1] [localstorage] Initialized at C:\Users\1\AppData\Roaming\Insomnia\localStorage
[1] Installed Extension: React Developer Tools
[1] Installed Extension: Redux DevTools
[0] webpack: wait until bundle finished: /bundle.js
[0] (node:31824) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
[0] parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
[0] Hash: 1af1a1d2e652d858a8d1
[0] Version: webpack 2.7.0
[0] Time: 68056ms
[0]                          Asset     Size  Chunks                    Chunk Names
[0]          OpenSans-Italic.woff2  56.7 kB          [emitted]         
[0]                  renderer.html  1.87 kB          [emitted]         
[0]            OpenSans-Bold.woff2  46.7 kB          [emitted]         
[0]      OpenSans-BoldItalic.woff2  54.5 kB          [emitted]         
[0]       OpenSans-ExtraBold.woff2  52.7 kB          [emitted]         
[0] OpenSans-ExtraBoldItalic.woff2  53.1 kB          [emitted]         
[0]      fontawesome-webfont.woff2  71.9 kB          [emitted]         
[0]           OpenSans-Light.woff2  45.9 kB          [emitted]         
[0]     OpenSans-LightItalic.woff2  56.5 kB          [emitted]         
[0]         OpenSans-Regular.woff2    47 kB          [emitted]         
[0]        OpenSans-Semibold.woff2  63.7 kB          [emitted]         
[0]  OpenSans-SemiboldItalic.woff2  56.7 kB          [emitted]         
[0]                      bundle.js  24.4 MB       0  [emitted]  [big]  main
[0] chunk    {0} bundle.js (main) 8.39 MB [entry] [rendered]
[0]  [../node_modules/loglevel/lib/loglevel.js] ./~/loglevel/lib/loglevel.js 6.74 kB {0} [built]
[0]  [../node_modules/react-hot-loader/lib/patch.js] ./~/react-hot-loader/lib/patch.js 209 bytes {0} [built]
[0]  [../node_modules/react-hot-loader/patch.js] ./~/react-hot-loader/patch.js 41 bytes {0} [built]
[0]  [../node_modules/strip-ansi/index.js] ./~/strip-ansi/index.js 161 bytes {0} [built]
[0]  [../node_modules/webpack-dev-server/client/index.js?http:/localhost:3333] (webpack)-dev-server/client?http://localhost:3333 5.83 kB {0} [built]
[0]  [../node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.6 kB {0} [built]
[0]  [../node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
[0]  [../node_modules/webpack/hot ^\.\/log$] (webpack)/hot nonrecursive ^\.\/log$ 160 bytes {0} [built]
[0]  [../node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {0} [built]
[0]  [../node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.02 kB {0} [built]
[0]  [../node_modules/webpack/hot/only-dev-server.js] (webpack)/hot/only-dev-server.js 2.29 kB {0} [built]
[0]  [./renderer.html] ./app/renderer.html 59 bytes {0} [built]
[0]  [./renderer.js] ./app/renderer.js 120 bytes {0} [built]
[0]  [./ui/index.js] ./app/ui/index.js 1.64 kB {0} [built]
[0]    [34] multi (webpack)-dev-server/client?http://localhost:3333 webpack/hot/only-dev-server react-hot-loader/patch ./renderer.js ./renderer.html 76 bytes {0} [built]
[0]      + 1320 hidden modules
[0] 
[0] WARNING in ./~/graphql-language-service-interface/dist/GraphQLLanguageService.js.flow
[0] Module parse failed: C:\CODE\JS\insomnia\node_modules\graphql-language-service-interface\dist\GraphQLLanguageService.js.flow Unexpected token (11:12)
[0] You may need an appropriate loader to handle this file type.
[0] |  */
[0] | 
[0] | import type {
[0] |   DocumentNode,
[0] |   FragmentSpreadNode,
[0]  @ ./~/graphql-language-service-interface/dist ^.*$
[0]  @ ./~/graphql-language-service-interface/dist/GraphQLLanguageService.js
[0]  @ ./~/graphql-language-service-interface/dist/index.js
[0]  @ ./~/codemirror-graphql/hint.js
[0]  @ ./app/ui/components/codemirror/base-imports.js
[0]  @ ./app/ui/components/codemirror/code-editor.js
[0]  @ ./app/ui/components/modals/generate-code-modal.js
[0]  @ ./app/ui/containers/app.js
[0]  @ ./app/ui/index.js
[0]  @ ./app/renderer.js
[0]  @ multi (webpack)-dev-server/client?http://localhost:3333 webpack/hot/only-dev-server react-hot-loader/patch ./renderer.js ./renderer.html
[0] 
[0] WARNING in ./~/graphql-language-service-interface/dist/autocompleteUtils.js.flow
[0] Module parse failed: C:\CODE\JS\insomnia\node_modules\graphql-language-service-interface\dist\autocompleteUtils.js.flow Unexpected token (11:12)
[0] You may need an appropriate loader to handle this file type.
[0] |  */
[0] | 
[0] | import type {GraphQLField, GraphQLSchema, GraphQLType} from 'graphql';
[0] | import {isCompositeType} from 'graphql';
[0] | import {
[0]  @ ./~/graphql-language-service-interface/dist ^.*$
[0]  @ ./~/graphql-language-service-interface/dist/GraphQLLanguageService.js
[0]  @ ./~/graphql-language-service-interface/dist/index.js
[0]  @ ./~/codemirror-graphql/hint.js
[0]  @ ./app/ui/components/codemirror/base-imports.js
[0]  @ ./app/ui/components/codemirror/code-editor.js
[0]  @ ./app/ui/components/modals/generate-code-modal.js
[0]  @ ./app/ui/containers/app.js
[0]  @ ./app/ui/index.js
[0]  @ ./app/renderer.js
[0]  @ multi (webpack)-dev-server/client?http://localhost:3333 webpack/hot/only-dev-server react-hot-loader/patch ./renderer.js ./renderer.html
[0] 
[0] WARNING in ./~/graphql-language-service-interface/dist/getAutocompleteSuggestions.js.flow
[0] Module parse failed: C:\CODE\JS\insomnia\node_modules\graphql-language-service-interface\dist\getAutocompleteSuggestions.js.flow Unexpected token (11:12)
[0] You may need an appropriate loader to handle this file type.
[0] |  */
[0] | 
[0] | import type {
[0] |   FragmentDefinitionNode,
[0] |   GraphQLDirective,
[0]  @ ./~/graphql-language-service-interface/dist ^.*$
[0]  @ ./~/graphql-language-service-interface/dist/GraphQLLanguageService.js
[0]  @ ./~/graphql-language-service-interface/dist/index.js
[0]  @ ./~/codemirror-graphql/hint.js
[0]  @ ./app/ui/components/codemirror/base-imports.js
[0]  @ ./app/ui/components/codemirror/code-editor.js
[0]  @ ./app/ui/components/modals/generate-code-modal.js
[0]  @ ./app/ui/containers/app.js
[0]  @ ./app/ui/index.js
[0]  @ ./app/renderer.js
[0]  @ multi (webpack)-dev-server/client?http://localhost:3333 webpack/hot/only-dev-server react-hot-loader/patch ./renderer.js ./renderer.html
[0] 
[0] WARNING in ./~/graphql-language-service-interface/dist/getDiagnostics.js.flow
[0] Module parse failed: C:\CODE\JS\insomnia\node_modules\graphql-language-service-interface\dist\getDiagnostics.js.flow Unexpected token (11:12)
[0] You may need an appropriate loader to handle this file type.
[0] |  */
[0] | 
[0] | import type {
[0] |   ASTNode,
[0] |   GraphQLError,
[0]  @ ./~/graphql-language-service-interface/dist ^.*$
[0]  @ ./~/graphql-language-service-interface/dist/GraphQLLanguageService.js
[0]  @ ./~/graphql-language-service-interface/dist/index.js
[0]  @ ./~/codemirror-graphql/hint.js
[0]  @ ./app/ui/components/codemirror/base-imports.js
[0]  @ ./app/ui/components/codemirror/code-editor.js
[0]  @ ./app/ui/components/modals/generate-code-modal.js
[0]  @ ./app/ui/containers/app.js
[0]  @ ./app/ui/index.js
[0]  @ ./app/renderer.js
[0]  @ multi (webpack)-dev-server/client?http://localhost:3333 webpack/hot/only-dev-server react-hot-loader/patch ./renderer.js ./renderer.html
[0] 
[0] WARNING in ./~/graphql-language-service-interface/dist/getDefinition.js.flow
[0] Module parse failed: C:\CODE\JS\insomnia\node_modules\graphql-language-service-interface\dist\getDefinition.js.flow Unexpected token (11:12)
[0] You may need an appropriate loader to handle this file type.
[0] |  */
[0] | 
[0] | import type {
[0] |   ASTNode,
[0] |   FragmentSpreadNode,
[0]  @ ./~/graphql-language-service-interface/dist ^.*$
[0]  @ ./~/graphql-language-service-interface/dist/GraphQLLanguageService.js
[0]  @ ./~/graphql-language-service-interface/dist/index.js
[0]  @ ./~/codemirror-graphql/hint.js
[0]  @ ./app/ui/components/codemirror/base-imports.js
[0]  @ ./app/ui/components/codemirror/code-editor.js
[0]  @ ./app/ui/components/modals/generate-code-modal.js
[0]  @ ./app/ui/containers/app.js
[0]  @ ./app/ui/index.js
[0]  @ ./app/renderer.js
[0]  @ multi (webpack)-dev-server/client?http://localhost:3333 webpack/hot/only-dev-server react-hot-loader/patch ./renderer.js ./renderer.html
[0] 
[0] WARNING in ./~/graphql-language-service-interface/dist/getOutline.js.flow
[0] Module parse failed: C:\CODE\JS\insomnia\node_modules\graphql-language-service-interface\dist\getOutline.js.flow Unexpected token (11:12)
[0] You may need an appropriate loader to handle this file type.
[0] |  */
[0] | 
[0] | import type {
[0] |   Outline,
[0] |   TextToken,
[0]  @ ./~/graphql-language-service-interface/dist ^.*$
[0]  @ ./~/graphql-language-service-interface/dist/GraphQLLanguageService.js
[0]  @ ./~/graphql-language-service-interface/dist/index.js
[0]  @ ./~/codemirror-graphql/hint.js
[0]  @ ./app/ui/components/codemirror/base-imports.js
[0]  @ ./app/ui/components/codemirror/code-editor.js
[0]  @ ./app/ui/components/modals/generate-code-modal.js
[0]  @ ./app/ui/containers/app.js
[0]  @ ./app/ui/index.js
[0]  @ ./app/renderer.js
[0]  @ multi (webpack)-dev-server/client?http://localhost:3333 webpack/hot/only-dev-server react-hot-loader/patch ./renderer.js ./renderer.html
[0] webpack: Compiled with warnings.

```

</details>

**Comment by gschier** [comment]
Hi @elcergey. Do you have any errors in the Devtools console?

**Comment by elcergey** [comment]
@gschier 
Yes, this:
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
```
\\?\C:\CODE\JS\insomnia\app\node_modules\node-libcurl\lib\binding\node_libcurl.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\CODE\JS\insomnia\app\node_modules\node-libcurl\lib\Easy.js:40:29)
    at Object.<anonymous> (C:\CODE\JS\insomnia\app\node_modules\node-libcurl\lib\Easy.js:280:3)
```

The file in question (which is windows library) is there. Reinstalling and building it from source (with different options) didn't help. My OS is Win 10 x64.

**Comment by gschier** [comment]
Hmm, can you try running `npm install` and then `npm run rebuild` again?

**Comment by elcergey** [comment]
It doesn't help. Will try to investigate the cause.

**Comment by ajagnanan** [comment]
make sure you have node8, then

```
npm install --save-dev electron-rebuild
./node_modules/.bin/electron-rebuild
```

**Comment by elcergey** [comment]
It worked with Node 8.4 (not 8.2 though, at least on my machine).
