### ISSUE TITLE
gRPC: Not able to parse protoc-gen-validate defintions

### ISSUE THREAD

**Issue by loeffel-io** [getinsomnia/insomnia#4084]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.3

### What operating system are you using?

macOS

### Operating System Version

11.6 (20G165)

### Installation method

from website

### Expected Behavior

Should parse this proto file without any problems: 

```proto
syntax = "proto3";
package place;

option go_package = ".;protobuf";

import "validate/validate.proto";

message AutocompleteRequest {
  string value = 1 [(validate.rules).string.min_len = 3];
  string token = 2 [(validate.rules).string.uuid = true];
  string language = 3 [(validate.rules).string = {in: ["de", "en"]}];
}

message AutocompleteResponseItem {
  string id = 1;
  string description = 2;
}

message AutocompleteResponse {
  repeated AutocompleteResponseItem autocompleteResponseItems = 1;
}

message DetailRequest{
  string value = 1 [(validate.rules).string.min_len = 3];
  string token = 2 [(validate.rules).string.uuid = true];
  string language = 3 [(validate.rules).string = {in: ["de", "en"]}];
}

message DetailResponse{
  string Name = 1;
  string Street = 2;
  string StreetNumber = 3;
  uint64 Zip = 4;
  string City = 5;
  string Country = 6;
}

service PlaceService {
  rpc Autocomplete(AutocompleteRequest) returns (AutocompleteResponse) {}
  rpc Detail(DetailRequest) returns (DetailResponse) {}
}
```

### Actual Behavior

```
Error: illegal value '[' (/Users/lucasloffel/go/src/github.com/ranked-de/ranked-place-grpc/protobuf/place.proto, line 11)
    at illegal (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:254947:16)
    at readValue (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:254986:19)
    at parseOptionValue (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:255432:33)
    at parseOption (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:255411:27)
    at parseInlineOptions (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:255464:17)
    at parseField_line (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:255231:13)
    at ifBlock (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:255145:17)
    at parseField (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:255221:9)
    at parseType_block (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:255193:21)
    at ifBlock (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:255141:17)
```

**Comment by zcong1993** [comment]
Any updates?

**Comment by filfreire** [comment]
Hi @loeffel-io, I am also able to reproduce this in Insomnia's latest stable version:


![Image](https://user-images.githubusercontent.com/11976836/181058796-1ef3f3a6-8e5e-485c-a028-0c5d09aa5d60.png)

We'll try to update you here as soon as there's any news or a potential fix. If anyone bumps into this issue and think they found a solution feel free to contribute a PR.

**Comment by filfreire** [comment]
@loeffel-io you should be able to use gRPC server reflection in latest Insomnia version which might help with these cases
https://github.com/Kong/insomnia/releases/tag/core%402022.7.5

**Comment by 06kellyjac** [comment]
protoc-gen-validate is being replaced with https://github.com/bufbuild/protovalidate

https://buf.build/blog/protoc-gen-validate-v1-and-v2/
