### ISSUE TITLE
UI not loading

### ISSUE THREAD

**Issue by erwinw** [getinsomnia/insomnia#4673]
### Expected Behavior

When opening Insomnia, I would expect to be able to, well, use it.

### Actual Behavior

The main window opens, without any content whatsoever:
![2022-04-05 at 17 21](https://user-images.githubusercontent.com/54856303/161788347-a3e2ed45-9612-4b6d-8ec2-00ad304d745e.png)

### Reproduction Steps

Not sure why this happened on my machine, but well, on my machine it's just opening the app.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Opening the log files, the `render.log` file contains the following error:

```
[2022-04-04 09:50:13.903] [error] Unhandled Promise {
message: "Can't insert key env_b9f6a0b882c4388cc6c3739c14faf92c789effba, it violates the unique constraint",
stack: "Error: Can't insert key env_b9f6a0b882c4388cc6c3739c14faf92c789effba, it violates the unique constraint\n" +
' at _AVLTree.insert (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/binary-search-tree/lib/avltree.js:273:19)\n' +
' at AVLTree.insert (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/binary-search-tree/lib/avltree.js:307:27)\n' +
' at Index.insert (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nedb/lib/indexes.js:77:15)\n' +
' at Datastore.addToIndexes (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nedb/lib/datastore.js:180:29)\n' +
' at Datastore._insertInCache (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nedb/lib/datastore.js:402:10)\n' +
' at Datastore._insert (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nedb/lib/datastore.js:348:10)\n' +
' at /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nedb/lib/executor.js:40:13\n' +
' at Immediate.process (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:731:21)\n' +
' at processImmediate (node:internal/timers:464:21)'
}
```

### Insomnia Version

2022.2.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.1

### Installation method

Download from insomnia.rest

**Comment by filfreire** [comment]
@erwinw thank you for reporting this issue!

- Did you recently upgrade Insomnia to 2022.2.1? (Any idea what was your previous version before the upgrade?)

- In order to help us debug, could you kindly check in your Insomnia Data folder (e.g. `open ~/Library/Application\ Support/Insomnia`) if there's any single file (e.g. `insomnia.Environment.db` that has that key `env_b9f6a0b882c4388cc6c3739c14faf92c789effba` duplicate, and share a bit more information?

**Comment by MohamedRagabAnas** [comment]
I have the same issue!

**Comment by kevinonyoh** [comment]
![api](https://user-images.githubusercontent.com/72035411/210862263-0480d8cb-bbf2-4fc4-9b31-d38f45351763.PNG)

**Comment by nikolayandr** [comment]
The same issue. After uploading new project I can't open old ones

**Comment by kamaliamirthalingam1** [comment]
How to resolve the above unique constraint error like the above one and to recover the existing curls.

**Comment by htuzel** [comment]
+1

**Comment by m175u0** [comment]
+1

**Comment by TerrenceLJones** [comment]
I'm experiencing the same thing on version:
```
Version: Insomnia 2023.2.2
Build date: 5/17/2023
OS: Darwin arm64 21.6.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64
```
<img width="1109" alt="Screen Shot 2023-06-07 at 11 29 25" src="https://github.com/Kong/insomnia/assets/7111256/740ced7f-baef-4af3-a01d-cfbbbfb004e3">


I was able to address (not fix) the issue by downgrading the application to a version that a coworker was using (and not having issues with); version: 2022.7.5.
