### ISSUE TITLE
`Maximum call stack size exceeded` when importing OpenAPI spec

### ISSUE THREAD

**Issue by ghost** [getinsomnia/insomnia#4700]
### Expected Behavior

I downloaded an odata service document from the provider.

I used [odata-openapi](https://www.npmjs.com/package/odata-openapi) to convert it to an OpenAPI JSON spec.

I import the file and expect to have a collection of usable requests.

A zipped version of the generated JSON is attached.
[ln_openapi_from_odata.zip](https://github.com/Kong/insomnia/files/8497160/ln_openapi_from_odata.zip)

For what it is worth, Postman is able to import this file.  
(edit: I am able to export from postman and use [postman2openapi](https://kevinswiber.github.io/postman2openapi/) to create a yaml that insomnia will import)

### Actual Behavior

I import the file and get a crash report:

```
RangeError: Maximum call stack size exceeded
    at generateParameterExample (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:399:34)
    at object (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:415:45)
    at generateParameterExample (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:452:16)
    at array (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:423:27)
    at generateParameterExample (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:452:16)
    at object (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:415:45)
    at generateParameterExample (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:452:16)
    at array (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:423:27)
    at generateParameterExample (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:452:16)
    at object (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/insomnia-importers/dist/src/importers/openapi-3.js:415:45)
```

### Reproduction Steps

1. unzip the json file
2. import into insomnia

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 2022.2.1
Release date: 3/21/2022
OS: Darwin arm64 21.4.0
Electron: 17.1.0
Node: 16.13.0
V8: 9.8.177.11-electron.0
Architecture: arm64

### Insomnia Version

2022.2.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.3.1 (21E258)  (m1)

### Installation method

download from insomnia.rest

**Comment by rogerluan** [comment]
I'm facing the same issue. macOS 12.3.1. Env:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/8419048/164474972-3044173b-e1a1-4657-b9a3-21e4b76c22a5.png">

https://editor.swagger.io shows no validation warnings/errors with my spec.

**Comment by rogerluan** [comment]
This has been fixed here btw: https://github.com/Kong/insomnia/releases/tag/core%402022.3.0-beta.4

If you use mac, the version to download is this one: [Insomnia.Core-2022.3.0-beta.4.dmg](https://github.com/Kong/insomnia/releases/download/core%402022.3.0-beta.4/Insomnia.Core-2022.3.0-beta.4.dmg)

**Comment by marckong** [comment]
@csprl-nowigence I wonder if @rogerluan 's comment help at all? Would you please be able to verify it?

**Comment by ghost** [comment]
Yes, it works. Thank you for bringing this back to my attention. It takes a long time to load the spec (multiple minutes), and it hangs up the UI while it loads. But, it does successfully complete.

**Comment by marckong** [comment]
@csprl-nowigence we are aware of this issue and currently working on it (also please feel free to share your thoughts too). Thank you for re-surfacing it! We love this collaboration. It only helps us improve!
