### ISSUE TITLE
2022.3 and higher shows infinite loading on commit changes action. 

### ISSUE THREAD

**Issue by rostislav-simonik** [getinsomnia/insomnia#4905]
### Expected Behavior

When I initiate commit action 
<img width="257" alt="image" src="https://user-images.githubusercontent.com/25525736/175883139-01840326-445a-4b74-92cc-0e3dde9aed8d.png">
It should open list of files to be committed.  

### Actual Behavior

It displays a modal with loading status but never displays committed files. It works on version 2022.2 but with version 2022.3 and higher, it doesn't work anymore. 

When I open devtools it displays the following error 
```
Uncaught (in promise) YAMLSyntaxError: All collection items must start at the same column
    at Collection.parse (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:331:24)
    at /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:1605:29
    at CollectionItem.parse (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:92:19)
    at /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:1586:25
    at Collection.parse (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:350:20)
    at /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:1605:29
    at Document.parseContents (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:622:26)
    at Document.parse (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:685:19)
    at Object.parse (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/parse-cst.js:1723:18)
    at parseDocument (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/index.js:43:24)
    at Object.parse (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/yaml/dist/index.js:55:15)
    at g2.stat (index.016df4fc.js:161:5144)
    at async FileSystem.lstat (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:4324:21)
    at async Object.status (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:13077:19)
    at async Bz._refresh (index.016df4fc.js:1896:12487)
    at async Bz.show (index.016df4fc.js:1896:11977)
```
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/25525736/175883794-4391fdb2-d66f-4f82-868d-93255db1f6e3.png">

so i narrowed the issue to yaml parsing of following content 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/25525736/175884387-051276f8-727f-4cc0-9733-9224cbe07150.png">

I prepared small repo with replicable case here 

https://github.com/rostislav-simonik/insomnia-commit-issue

so you can execute by 
`node index.js`

and it displays this error 
```

YAMLParseError: Unexpected scalar at node end at line 26, column 6:

    ",\"variables\":{\"userAccountId\":\"{% response 'body',
    'req_bfbe07ff4…
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at Composer.onError (/Users/rostislav.simonik/Development/repositories/sandbox.insomnia-issue/node_modules/yaml/dist/compose/composer.js:69:34)
    at Object.resolveEnd (/Users/rostislav.simonik/Development/repositories/sandbox.insomnia-issue/node_modules/yaml/dist/compose/resolve-end.js:31:21)
    at Object.resolveFlowScalar (/Users/rostislav.simonik/Development/repositories/sandbox.insomnia-issue/node_modules/yaml/dist/compose/resolve-flow-scalar.js:35:27)
    at Object.composeScalar (/Users/rostislav.simonik/Development/repositories/sandbox.insomnia-issue/node_modules/yaml/dist/compose/compose-scalar.js:11:29)
    at composeNode (/Users/rostislav.simonik/Development/repositories/sandbox.insomnia-issue/node_modules/yaml/dist/compose/compose-node.js:24:34)
    at Object.resolveBlockMap (/Users/rostislav.simonik/Development/repositories/sandbox.insomnia-issue/node_modules/yaml/dist/compose/resolve-block-map.js:79:19)
    at Object.composeCollection (/Users/rostislav.simonik/Development/repositories/sandbox.insomnia-issue/node_modules/yaml/dist/compose/compose-collection.js:13:36)
    at composeNode (/Users/rostislav.simonik/Development/repositories/sandbox.insomnia-issue/node_modules/yaml/dist/compose/compose-node.js:31:38)
    at Object.resolveBlockMap (/Users/rostislav.simonik/Development/repositories/sandbox.insomnia-issue/node_modules/yaml/dist/compose/resolve-block-map.js:79:19)
    at Object.composeCollection (/Users/rostislav.simonik/Development/repositories/sandbox.insomnia-issue/node_modules/yaml/dist/compose/compose-collection.js:13:36) {
  code: 'UNEXPECTED_TOKEN',
  pos: [ 1164, 1420 ],
  linePos: [ { line: 26, col: 6 }, { line: 26, col: 262 } ]
}

```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.3 and higher

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### Installation method

download from insomnia website

### Last Known Working Insomnia version

2022.4.2

**Comment by filfreire** [comment]
Hi @rostislav-simonik, thank for reporting this!

Myself and @kreosus tried reproducing by using an example of a graphql request that uses request chaining to obtain a query variable's value and an authentication header, and we were able to commit and push changes normally, and not able to reproduce your exception.

You can check our example repo here: https://github.com/filfreire/insomnia-4905

On the other hand, when we tried to include the request provided by your example (just by copy pasting into the repo and changing the workspace ids), indeed we saw some form of a  YAML exception:
![image](https://user-images.githubusercontent.com/11976836/175953438-335cd7ca-9d66-401d-84a0-dd2adf81da1d.png)

This is not the same as the one in your example repository though, could be due to us trying to copy paste your request .txt file.

Would you be able to provide us with an Insomnia export of the requests (using export feature of insomnia) that we could try to import and use in a git repo of our own to help us reproduce this better?

**Comment by rostislav-simonik** [comment]
@filfreire attaching requested export
[Insomnia_2022-06-29.json.zip](https://github.com/Kong/insomnia/files/9013715/Insomnia_2022-06-29.json.zip)

**Comment by eddex** [comment]
Experiencing the same issue on:

```
Version: Insomnia 2022.4.2
Build date: 22/06/2022
OS: Windows_NT x64 10.0.19044
Electron: 18.1.0
Node: 16.13.2
V8: 10.0.139.15-electron.0
Architecture: x64
```

As a workaround I used Insomnia 2022.2.1, with this version it worked.

**Comment by eddex** [comment]
> I prepared small repo with replicable case here
>
> https://github.com/rostislav-simonik/insomnia-commit-issue

I had a look at the request in @rostislav-simonik's repo and compared it to my failing request.

When we take the YAML starting with the `body`, and put it into a YAML validator (e.g. https://jsonformatter.org/yaml-validator), we can see that there is a formatting error in the generated YAML.

YAML:
```yaml
body:
  mimeType: application/graphql
  text: "{\"query\":\"query userAccount_pro_skillList($userAccountId: ID!)
    {\\n  userAccount (\\n    where: {\\n    \\tid:
    $userAccountId\\n  \\t}\\n  ) {\\n    id\\n    pro
    {\\n      id\\n      skillList(\\n        take: 2, \\n        where: {
    \\t\\n\\t\\t\\t\\t\\tskill: {\\n\\t          skillCategoryList: { hasSome:
    [TREE] } \\n  \\t        label: {\\n    \\t        contains:
    \\\"react\\\"\\n      \\t      mode:
    insensitive\\n        \\t  }\\n\\t\\t\\t\\t\\t}\\n        } \\n      )
    {\\n        pageInfo
    {\\n          startCursor\\n          hasNextPage\\n          hasNextPage\\\
    n          endCursor\\n        }\\n        nodes
    {\\n          id\\n          skill {
    \\n\\t\\t\\t\\t\\t\\tid\\n\\t\\t\\t\\t\\t\\tkey\\n\\t\\t\\t\\t\\t\\tlabel\\t\
    \\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t}\\n        }\\n      }\\n    }\\n  }\\n}\\
    ",\"variables\":{\"userAccountId\":\"{% response 'body',
    'req_bfbe07ff48a542daa3a39224c12419ed',
    'b64::JC5kYXRhLmNyZWF0ZUF1dGhvcml6YXRpb24udXNlci51c2VyQWNjb3VudC5pZA==::46b\
    ', 'always', 60 %}\"},\"operationName\":\"userAccount_pro_skillList\"}"
```

ERROR:
```
Error : bad indentation of a mapping entry at line 17, column 6:
        ",\"variables\":{\"userAccountId\ ... 
         ^
Line : undefined  undefined
```

The problem is that the `"` at the beginning of the line is not escaped (missing `\`). If we manually add a `\` to the beginning of the line, the YAML is valid.

In my example, the un-escaped `"` was at a different place in the JSON, after the first bracket of the `variables`.
What is consistent is the fact, that the un-escaped `"` is at the beginning of a new line in the `text` part of the YAML.

I'm not sure how to fix this in Insomnia, but I hope this helps.

**Comment by filfreire** [comment]
Thank you @eddex and @rostislav-simonik 

Myself and @kreosus were also able to reproduce this, so there's definitely something problematic around how the YAML is setup and then parsed specific to GraphQL queries when they are git sync'ed it seems.

We'll try to investigate this further!

**Comment by rostislav-simonik** [comment]
@filfreire I'd like to check if there is some progress on this issue or if you need help solving the problem. Thanks in advance for your answer.

**Comment by kbumsik** [comment]
Hi, I have a similar issue here.

I believe it is highly co-related to #4759 as well.

So basically there is possibility that saving GraphQL Requests in YAML format (either export or git sync)  leads to corruption...

**Comment by antoninobonumore** [comment]
This error still exists on the last version.
I can perfectly tell that if one of your requests in your collection contains a dynamic response reference, the error is generated:
In my case is this:
![image](https://user-images.githubusercontent.com/1431493/219957447-9e7067a4-fb65-44b1-93a5-5db8ed2df57d.png)
