### ISSUE TITLE
Adding feature: Invalid hook call

### ISSUE THREAD

**Issue by codeasashu** [getinsomnia/insomnia#5390]
### Expected Behavior

I can add a react feature in form of my package in `packages` folder  without getting the error.

### Actual Behavior

When I add a functionality in `packages/<my-feat>` directory, I am getting
`Error: Invalid hook call. Hooks can only be called inside of the body of a function component` error.

This is happening due to different react instance in `my-feat` folder, causing the above issue on using `useState` method.
Otherwise, it seems to be working fine.

### Reproduction Steps

1. Create a minimal reactjs application into folder `packages/mylib`
2. Add `react`, `react-dom` as dev and peer dependencies
3. Use the package in any `insomnia` UI container, for instance, `wrapper-design`.

Sample Repo: https://github.com/codeasashu/demo-issue-insomnia

Usage example:

```js
// inside src/ui/components/wrapper-design.tsx

import App from 'mylib';

// Put this anywhere in render method
<App />
```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The issue vanishes if I remove any use of `use` hooks such as `useState`, `useContext` etc.
I've tried linking `react`, `react-dom` from `insomnia` package, it didn't worked. 

I am still wondering how `insomnia-components` is working, while my project doesn't?

### Insomnia Version

2022.6.0

### What operating system are you using?

macOS

### Operating System Version

Big Sur(11.6.2)

### Installation method

github

**Comment by nagulv** [comment]
I see the same issue - any new react hook usage seems to result in an error. I tried adding [mui ](https://mui.com/) as a dependency 


lerna add @mui/material --scope insomnia
lerna add @emotion/react --scope insomnia
lerna add @emotion/styled --scope insomnia

and then adding a button to package/insomnia/src/ui/routes/root.tsx and that results in a "Failed to render" error:

`TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (C:\Users\Nagul\Documents\GitHub\insomnia\packages\insomnia\node_modules\react\cjs\react.development.js:1618:21)
    at Button (C:\Users\Nagul\Documents\GitHub\insomnia\packages\insomnia\node_modules\@mui\material\Button\Button.js:229:30)
    at renderWithHooks (http://localhost:3334/@fs/C:/Users/Nagul/Documents/GitHub/insomnia/packages/insomnia/node_modules/.vite/deps/chunk-GRMYNPE5.js?v=7d412a96:11608:26)
    at updateForwardRef (http://localhost:3334/@fs/C:/Users/Nagul/Documents/GitHub/insomnia/packages/insomnia/node_modules/.vite/deps/chunk-GRMYNPE5.js?v=7d412a96:13747:28)
    at beginWork (http://localhost:3334/@fs/C:/Users/Nagul/Documents/GitHub/insomnia/packages/insomnia/node_modules/.vite/deps/chunk-GRMYNPE5.js?v=7d412a96:15260:22)
    at beginWork$1 (http://localhost:3334/@fs/C:/Users/Nagul/Documents/GitHub/insomnia/packages/insomnia/node_modules/.vite/deps/chunk-GRMYNPE5.js?v=7d412a96:19020:22)
    at performUnitOfWork (http://localhost:3334/@fs/C:/Users/Nagul/Documents/GitHub/insomnia/packages/insomnia/node_modules/.vite/deps/chunk-GRMYNPE5.js?v=7d412a96:18465:20)
    at workLoopSync (http://localhost:3334/@fs/C:/Users/Nagul/Documents/GitHub/insomnia/packages/insomnia/node_modules/.vite/deps/chunk-GRMYNPE5.js?v=7d412a96:18404:13)
    at renderRootSync (http://localhost:3334/@fs/C:/Users/Nagul/Documents/GitHub/insomnia/packages/insomnia/node_modules/.vite/deps/chunk-GRMYNPE5.js?v=7d412a96:18383:15)
    at recoverFromConcurrentError (http://localhost:3334/@fs/C:/Users/Nagul/Documents/GitHub/insomnia/packages/insomnia/node_modules/.vite/deps/chunk-GRMYNPE5.js?v=7d412a96:18005:28)
    at performSyncWorkOnRoot (http://localhost:3334/@fs/C:/Users/Nagul/Documents/GitHub/insomnia/packages/insomnia/node_modules/.vite/deps/chunk-GRMYNPE5.js?v=7d412a96:18147:28)
    at flushSyncCallbacks (http://localhost:3334/@fs/C:/Users/Nagul/Documents/GitHub/insomnia/packages/insomnia/node_modules/.vite/deps/chunk-GRMYNPE5.js?v=7d412a96:8652:30)
    at http://localhost:3334/@fs/C:/Users/Nagul/Documents/GitHub/insomnia/packages/insomnia/node_modules/.vite/deps/chunk-GRMYNPE5.js?v=7d412a96:17896:21
`

Curiously, I get the same error even when I create a new standalone project using the insomnia package config as the template - ie without lerna and multiple packages.
