### ISSUE TITLE
v7-beta5 will not start due to GPU error

### ISSUE THREAD

**Issue by jtfidje** [getinsomnia/insomnia#5465]
### Expected Behavior

I expected the application to start

### Actual Behavior

Application crashes with the following error

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.OiqxgJ)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2037)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[25781:1128/102245.891961:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[25793:1128/102245.911959:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.0-beta.5

### What operating system are you using?

Other Linux

### Operating System Version

QubesOS

### Installation method

deb with dpkg

### Last Known Working Insomnia version

2022.6.0

**Comment by filfreire** [comment]
Hi @jtfidje can you confirm is installing these helps starting Insomnia:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-9
sudo apt install libstdc++6
```

From https://askubuntu.com/a/1328208

**Comment by jhonpedro** [comment]
I ran into this too. @filfreire I installed the packages that you have mentioned above but it did not manage to run my insomnia, the same error persists.

The error returned to me:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /run/user/1000/snap.insomnia/.org.chromium.Chromium.NidStU)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snap/insomnia/184/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
```

**Comment by jhonpedro** [comment]
I managed to open my insomnia uninstalling the snap version that I had here, and installing it with the .deb downloaded in download page of [insomnia](https://insomnia.rest/download).

**Comment by damian-pastorini** [comment]
Same issue on the latest version I've got from snap on Ubuntu 21.04.
Also, the only fix was to get the .deb file version from the dowloads page.

**Comment by emil-nasso** [comment]
I also managed to get it started using the deb from the download page. Unfortunately, the settings/my saved requests did not get moved over automatically. I had a somewhat recent export of the settings though—just a warning for anyone else attempting that.

I'm running Linux mint 20.

![image](https://user-images.githubusercontent.com/1119706/210256122-bfd72f59-6d09-4c78-bfdb-ccadaca2ae63.png)

**Comment by willsbit** [comment]
same issue, I'm running Fedora 37

**Comment by VaclavDedik** [comment]
Same issue on ubuntu 22.04

**Comment by RaphaelBatagini** [comment]
+1 for ubuntu 22.04

**Comment by fengkaijia** [comment]
Same here on a fresh-installed Ubuntu 22.04 with Insomnia snap. The whole setup/version was working fine on 20.04 previously.

**Comment by Marcel2508** [comment]
Came across this issue today aswell.
Using the snap version on Ubuntu 22.04 is there any quick fix release planned already?
It worked previously without any problem on the same os last week. Some apt / snap updates might have broken it.

**Comment by kaharlichenko** [comment]
Got the same problem on Ubuntu 22.04, Insomnia snap version 2022.7.0.

> Some apt / snap updates might have broken it.

The whole idea of snap is to provide all the necessary dependencies bundled, so that no matter what you do to apt/rpm/apk packages it "should just work (tm)".

**Comment by filfreire** [comment]
Hi folks, this was related to https://github.com/Kong/insomnia/issues/5637

and should be fixed in the [latest release](https://github.com/Kong/insomnia/releases/tag/core%402022.7.5)
