### ISSUE TITLE
Failed to render yc error when sending a GraphQL endpoint

### ISSUE THREAD

**Issue by michaelalpine** [getinsomnia/insomnia#5578]
### Expected Behavior

When we try to open our workspace and hit our graphql endpoint, we just get a failed to render yc error, and then can't make any reuqests. 

### Actual Behavior

The program errors out and we can't do anything

### Reproduction Steps

Just open it and try to open a GQL query

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Here is what we get upon opening
![image](https://user-images.githubusercontent.com/62606815/209161556-16e03644-b253-45ea-8ae0-ce548648f292.png)

Then going to any other request we just get this
![image](https://user-images.githubusercontent.com/62606815/209161647-28e15f0d-1d94-4fa3-a8bf-9b99219ac347.png)

### Insomnia Version

2022.7.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 & 11

### Installation method

Download from insomnia

### Last Known Working Insomnia version

2022.6.0

**Comment by ajanini** [comment]
I have the same issue.

Stack trace:

```
Error: Type Query must define one or more fields.
    at nR (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:504:12630)
    at y_ (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:506:43944)
    at AK (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:635:356)
    at FK (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:641:211)
    at Object.DTe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:641:147)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:2557
    at x (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:14293)
    at ii.<anonymous> (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:16262)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:407:10355
    at ii.setOption (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:412:1978)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:671:5056
    at mE (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:24458)
    at nh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:42799)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:41058
    at A (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:1648)
    at Immediate.ce [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)
```

**Comment by fluidsonic** [comment]
Same, this is super annoying.

As a workaround to disable all checks and autocompletion:
- Navigate to a query that isn't broken
- Restart Insomnia or reopen the project to load that query
- Click on "schema"
- Disable "Automatic Fetch"
- Click "Load schema from JSON"
- Load an empty file

That will cause an error but also disable all checks and autocompletion.
Now you can fix the query and re-enable "Automatic Fetch".

**Comment by michaelalpine** [comment]
@fluidsonic we ended up rolling back a version so we could have auto complete and what not but that's good to know. Just uninstall and install this version if you want. https://github.com/Kong/insomnia/releases/tag/core%402022.6.0

**Comment by fluidsonic** [comment]
Thanks, I was looking for that one! 🙏

**Comment by filfreire** [comment]
Hi folks, this should be fixed in  https://github.com/Kong/insomnia/pull/5611

A patch release will go out today with the fix. Feel free to report any other thing you find

**Comment by michaelalpine** [comment]
I just updated and it seems to be fixed for me. Thanks!

**Comment by bart-kochanowicz** [comment]
Same here, version 2022.7.0.

I just passed wrong argument to field in variables, without sending request and I got these permanently error - i can not do anything without reinstalling whole app. 

`GraphQLError: Enum "Currency" cannot represent non-string value: 2137.
    at Yl.parseValue (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:502:10673)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:20522)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19879
    at Array.map (<anonymous>)
    at H5 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:20809)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19659)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19335)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19019
    at Array.forEach (<anonymous>)
    at UCe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:18928)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:18866
    at x (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:14293)
    at ii.<anonymous> (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:16262)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:407:10355
    at ii.setOption (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:412:1978)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:671:5056
    at mE (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:24458)
    at nh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:42799)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:41058
    at A (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:1648)
    at Immediate.ce [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)`

Perm error (wong arg which I mentioned above):
<img width="651" alt="Screenshot 2023-01-07 at 13 45 48" src="https://user-images.githubusercontent.com/56134772/211151292-71a8218a-8991-4fbb-8822-4ad1d63ce852.png">
