### ISSUE TITLE
Unable to enter enum values in variables for a graphql query

### ISSUE THREAD

**Issue by goughy000** [getinsomnia/insomnia#5625]
### Expected Behavior

I should be able to type an enum value into the variables panel which can then be used when executing the query without being interrupted mid-typing

### Actual Behavior

Insomnia tries to validate the enum value on each key press which causes a stack trace and prevents me from typing the rest of the value

### Reproduction Steps

1. Create a GraphQL request for an query which contains an enum value
2. Ensure the schema is loaded
3. Wire up the value via the variables
4. Try and change the value by typing.  E.g. if valid enum values were [CAT, DOG, MOUSE]. type the first C of CAT and insomnia is immediately sad

Query:

```graphql
query ($animal: AnimalEnum!) {
   pets(animal: $animal) {
     name
   }
}
```

Variables:

```json
{
   "animal": "C" // I'm typing here, attempting to type CAT
}
```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Stack trace appears and query window is replace with error message, have to restart insomnia to continue working (where it usually does the exact same again when i next open this query)

```
GraphQLError: Value "C" does not exist in "AnimalEnum" enum.
    at Yl.parseValue (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:502:10797)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:20522)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19335)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19019
    at Array.forEach (<anonymous>)
    at UCe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:18928)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:18866
    at x (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:14293)
    at ii.<anonymous> (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:16262)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:407:10355
    at ii.setOption (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:412:1978)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:671:5056
    at mE (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:24458)
    at nh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:42799)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:41058
    at A (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:1648)
    at Immediate.ce [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)
```

### Insomnia Version

2022.7.0

### What operating system are you using?

macOS

### Operating System Version

Darwin x64 22.2.0

### Installation method

download

### Last Known Working Insomnia version

not sure, but it did work before

**Comment by filfreire** [comment]
@goughy000 can you double check if you still face this issue in our latest `2022.7.1` version?

**Comment by goughy000** [comment]
Hey @filfreire - error still present in `2022.7.1` but hopefully #5650 will fix it in the next version release

Thanks!
