### ISSUE TITLE
Error: Name "__1" must not begin with "__", which is reserved by GraphQL introspection.

### ISSUE THREAD

**Issue by lovervoorde** [getinsomnia/insomnia#5672]
I get this error in a popup:

```
Error: Name "__1" must not begin with "__", which is reserved by GraphQL introspection.

Name "__2" must not begin with "__", which is reserved by GraphQL introspection.

Name "__3" must not begin with "__", which is reserved by GraphQL introspection.

Name "__4" must not begin with "__", which is reserved by GraphQL introspection.

Name "__5" must not begin with "__", which is reserved by GraphQL introspection.

Name "__1" must not begin with "__", which is reserved by GraphQL introspection.

Name "__2" must not begin with "__", which is reserved by GraphQL introspection.

Name "__3" must not begin with "__", which is reserved by GraphQL introspection.

Name "__4" must not begin with "__", which is reserved by GraphQL introspection.

Name "__5" must not begin with "__", which is reserved by GraphQL introspection.

Name "__1" must not begin with "__", which is reserved by GraphQL introspection.

Name "__2" must not begin with "__", which is reserved by GraphQL introspection.

Name "__3" must not begin with "__", which is reserved by GraphQL introspection.

Name "__4" must not begin with "__", which is reserved by GraphQL introspection.

Name "__5" must not begin with "__", which is reserved by GraphQL introspection.

Name "__1" must not begin with "__", which is reserved by GraphQL introspection.

Name "__2" must not begin with "__", which is reserved by GraphQL introspection.

Name "__3" must not begin with "__", which is reserved by GraphQL introspection.

Name "__4" must not begin with "__", which is reserved by GraphQL introspection.

Name "__5" must not begin with "__", which is reserved by GraphQL introspection.
    at PO (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:524:12630)
    at t_ (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:526:43944)
    at YV (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:655:356)
    at rK (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:661:211)
    at Object.Lke (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:661:147)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:666:2557
    at x (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:451:14293)
    at Zr.<anonymous> (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:451:16262)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:427:10355
    at Zr.setOption (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:432:1978)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:691:5056
    at eE (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:67:24458)
    at Yp (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:67:42799)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:67:41058
    at I (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:52:1648)
    at Immediate.ue [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)
```

The central panel has a similar error in place of the boxes where you input the query and variables.

**Comment by filfreire** [comment]
@lovervoorde I would suggest a couple of ideas for this issue:

- make sure you have the [lastest insomnia 2022.7.5 installed](https://github.com/Kong/insomnia/releases/tag/core%402022.7.5)
- don't name your graphql queries with underscores `__`

Feel free to reopen the issue if you're still having trouble and let us know what you tried.
