### ISSUE TITLE
Insomnia 2022.7.0 crash on loading introspection

### ISSUE THREAD

**Issue by imitko** [getinsomnia/insomnia#5714]
### Expected Behavior

Earlier version loaded and show documentation about Query fields despite Mutation not defined.

### Actual Behavior

Since 
Version: Insomnia 2022.7.0
Build date: 12/15/2022
OS: Darwin x64 19.6.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

Error: Type Mutation must define one or more fields.
    at nR (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:504:12630)
    at y_ (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:506:43944)
    at AK (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:635:356)
    at FK (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:641:211)
    at Object.DTe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:641:147)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:2557
    at x (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:14293)
    at ii.<anonymous> (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:16262)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:407:10355
    at ii.setOption (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:412:1978)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:671:5056
    at mE (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:24458)
    at nh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:42799)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:41058
    at A (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:1648)
    at Immediate.ce [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)

### Reproduction Steps

1. Create a new GraphQL request
2. Enter endpoint URL which produces introspection JSON document w/o Mutation type defined.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.0

### What operating system are you using?

macOS

### Operating System Version

10.15.7 (19H2026)

### Installation method

Auto-update

**Comment by filfreire** [comment]
@imitko, thanks for reporting this. It is fixed in [latest release](https://github.com/Kong/insomnia/releases/tag/core%402022.7.5)
