### ISSUE TITLE
Create Snapshot menu item sometimes does not work

### ISSUE THREAD

**Issue by DanielRouxSA** [getinsomnia/insomnia#5743]
### Expected Behavior

When clicking Create Snapshot, it is expected that the window for creating a snapshot appears (the window where the user can choose which changes to commit and enter a message describing the commit).

### Actual Behavior

What often happens is the dropdown containing the item disappears as expected, but there is no other response. The snapshot window does not appear, and no progress bar or error message appears. It is currently exhibiting this behavior as I type this, and restarting the application does not fix it.

### Reproduction Steps

1. Click the GitHub sync control at the center top of the screen next to the project name.
2. Click the Create Snapshot option.
3. The snapshot window does not appear.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This does not occur reliably; most of the time the menu item works correctly. Only occasionally does this problem present itself.

### Insomnia Version

2022.7.5

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22H2

### Installation method

Downloaded from insomnia.rest

**Comment by DanielRouxSA** [comment]
Update: this seems to affect all menu items in the Git sync control, not just Create Snapshot. I currently have the app not responding to any of the items, and restarting it has no effect.

**Comment by sghaneka** [comment]
I also have the same issue. Version: 2022.7.5

**Comment by GoodNello** [comment]
Same issue 2023.1

**Comment by jopeek** [comment]
Still an issue in the latest version. Dev Console reveals the following error. Guys, this is vital functionality that has been broken for almost two months now. Quite frankly not acceptable, especially for customers paying for this functionality.

`C:\Users\jpeek\AppData\Local\insomnia\app-2023.2.0-beta0\resources\app.asar\node_modules\@sentry\browser\dist\helpers.js:91 Uncaught Error: Modal SyncStagingModal not found
    at Xr (invariant.ts:14:9)
    at dfe (index.ts:71:13)
    at Bn (index.ts:41:23)
    at onClick (sync-dropdown.tsx:553:17)
    at D (module.js:411:27)
    at I (module.js:148:28)
    at L.onPointerUp (module.js:271:95)
    at Object.zle (react-dom.production.min.js:54:317)
    at Vle (react-dom.production.min.js:54:471)
    at qle (react-dom.production.min.js:55:35)
    at aL (react-dom.production.min.js:105:68)
    at H7 (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at MD (react-dom.production.min.js:274:42)
    at d7 (react-dom.production.min.js:52:375)
    at HS (react-dom.production.min.js:109:469)
    at cD (react-dom.production.min.js:74:59)
    at lce (react-dom.production.min.js:73:73)
    at HTMLBodyElement.sentryWrapped (C:\Users\jpeek\AppData\Local\insomnia\app-2023.2.0-beta0\resources\app.asar\node_modules\@sentry\browser\dist\helpers.js:76:23)
Xr @ invariant.ts:14
dfe @ index.ts:71
Bn @ index.ts:41
onClick @ sync-dropdown.tsx:553
D @ module.js:411
I @ module.js:148
L.onPointerUp @ module.js:271
zle @ react-dom.production.min.js:54
Vle @ react-dom.production.min.js:54
qle @ react-dom.production.min.js:55
aL @ react-dom.production.min.js:105
H7 @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
MD @ react-dom.production.min.js:274
d7 @ react-dom.production.min.js:52
HS @ react-dom.production.min.js:109
cD @ react-dom.production.min.js:74
lce @ react-dom.production.min.js:73
sentryWrapped @ C:\Users\jpeek\AppData\Local\insomnia\app-2023.2.0-beta0\resources\app.asar\node_modules\@sentry\browser\dist\helpers.js:76`

**Comment by hedenberg** [comment]
Same issue 
```
Version: Insomnia 2023.1.0
Build date: 2023-03-09
OS: Windows_NT x64 10.0.19044
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64
```
Would classify it as "sometimes works" rather than "sometimes does not work". 
Uninstalling Insomnia, removing Local and Roaming AppData for Insomnia and reinstalling does not solve the issue. 
Sometimes able to make it work by jumping back to Project-view and in to Collection again.

**Comment by PierreAdam** [comment]
Same here !
However for me it really doesn't work anymore ... which is kind of a pain to share changes with the team.
I dunno if it's cause I have several project group or what but I need to play with the buttons switching between "groups" on the left of the screen becore coming back to have it work. Sometimes even that doesn't do it.

**Comment by mgotfryd** [comment]
@DanielRouxSA @filfreire - there are multiple reports on this thread and there are repo steps on the bug. When will there be a fix for this? It was reported 3 months ago and is still labeled as unverified.

**Comment by mgotfryd** [comment]
> @DanielRouxSA @filfreire - there are multiple reports on this thread and there are repo steps on the bug. When will there be a fix for this? It was reported 3 months ago and is still labeled as unverified.

Bug is also present on V2023.1.0

**Comment by PierreAdam** [comment]
> @DanielRouxSA @filfreire - there are multiple reports on this thread and there are repo steps on the bug. When will there be a fix for this? It was reported 3 months ago and is still labeled as unverified.

Agreed ... it's kinda work breaking when you need to spend 10min trying to get the push or pull to even "show up"

**Comment by bryangateley** [comment]
Same! Just updating in hopes of adding some context. I have all the same issues as mentioned above, in addition sometimes the dropdown appears but im blocked from even executing a pull/create snapshot with the Red Slash Cirlce Icon instead of an arrow not allowing me to even select those options.  I am running a completely raw version of insomnia, no plugins etc... 

Version: Insomnia 2023.2.0
Build date: 4/26/2023
OS: Windows_NT x64 10.0.22621
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Comment by rippo** [comment]
As a paying customer I too am seeing this and going between desktop and laptop is such a pain as I all I can seem to do is to first clone collection from desktop (give it a new name) and then pull new collection of laptop. Seems to work but is a big headache keeping everythin in sync.

**Comment by DanielRouxSA** [comment]
Hi @filfreire @jackkav, would it be possible for us to at least get an acknowledgement as to whether the team is aware of this bug, and if it is currently under active investigation? If the team has other priorities under focus currently that would be understandable, however the current lack of communication regarding this issue is somewhat frustrating.

**Comment by jackkav** [comment]
Improvements to sync features are underway, please take a look at our beta if you'd like to provide early feedback while we're working on an improved sync experience.

**Comment by randallnewman** [comment]
I am not seeing the issue in beta 9 
Looks like the git menu has moved to lower left (took me a minute to find it)
[Release Insomnia 2023.5.0-beta.9](https://github.com/Kong/insomnia/releases/tag/core%402023.5.0-beta.9)
