### ISSUE TITLE
failed postman json import - "The URI does not contain a valid specification"

### ISSUE THREAD

**Issue by peterchibunna** [getinsomnia/insomnia#5762]
### Expected Behavior

This feature used to work, but it looks like Postman changed their exported data structure and broke the import into Insomnia.

### Actual Behavior

We are greeted with the message: **The URI does not contain a valid specification** with the following stack trace:
```js
Error: No importers found for file
    at Jge (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.a1e8765b.js:80:42986)
    at async uI (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.a1e8765b.js:80:43935)
    at async sE (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.a1e8765b.js:80:43397)
    at async Yz (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.a1e8765b.js:125:8948)
```

### Reproduction Steps

1. Click Create button, and then URL or File or Clipboard, depending on the source.
2. Paste the URL of a Postman collection or the contents of the clipboard or select a file, depending on the source too, [just as in .1 above]
3. Click import action button
4. The error appears with nothing imported

### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

There's a closed issue for this, but that one pertains to swagger and has been resolved.

### Insomnia Version

2023.1.0-beta.1

### What operating system are you using?

macOS

### Operating System Version

13.0.1 (Ventura)

### Installation method

Downloaded file

**Comment by tukusejssirs** [comment]
I get the same error (but different lines):

```bash
Error: No importers found for file
    at Xpe (file:///opt/Insomnia/resources/app.asar/index.49db83e9.js:80:42985)
    at async jI (file:///opt/Insomnia/resources/app.asar/index.49db83e9.js:80:43934)
    at async jx (file:///opt/Insomnia/resources/app.asar/index.49db83e9.js:80:43396)
    at async Yj (file:///opt/Insomnia/resources/app.asar/index.49db83e9.js:125:8948)
```

I use Arch Linux. Insomnia info:

```bash
Version: Insomnia 2022.7.5
Build date: 19/01/2023
OS: Linux x64 6.1.11-arch1-1
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64
```

[This file](https://developer.tatrabanka.sk/apihub/img/swagger/premium_api_payments_v1.0.1.yaml) fails to import.

**Comment by quisse** [comment]
Same here. One `wsdl` fails, another doesn't.
