### ISSUE TITLE
failed to compare remote branches - i is not a function

### ISSUE THREAD

**Issue by julianschelker** [getinsomnia/insomnia#5825]
### Expected Behavior

Can create a new snapshot of my api requests in Insomnia Sync with my team.

### Actual Behavior

Nothing happens

### Reproduction Steps

1. Create api changes
2. click on insomnia sync "master" with git branch icon
3. select "create snapshot" in the dropdown

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

<details> 
  <summary>
Logs from renderer.log: (click to open)
  </summary>

```
[2023-03-07 12:53:56.677] [info]  [db] Initialized DB client
[2023-03-07 12:53:56.760] [warn]  The vm module of Node.js is deprecated in the renderer process and will be removed.
[2023-03-07 12:53:56.762] [warn]  The vm module of Node.js is deprecated in the renderer process and will be removed.
[2023-03-07 12:53:56.939] [warn]  The vm module of Node.js is deprecated in the renderer process and will be removed.
[2023-03-07 12:53:56.996] [info]  {
  workspaceData: {
    activeWorkspace: {
      _id: 'wrk_5551f022d2034b1685762ab966db281b',
      type: 'Workspace',
      parentId: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      modified: 1662132494814,
      created: 1626446961153,
      name: 'project-name',
      description: '',
      scope: 'collection'
    },
    activeProject: {
      _id: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      type: 'Project',
      parentId: null,
      modified: 1672323832333,
      created: 1672323832333,
      name: "team-name",
      remoteId: 'team_e42d352df7c5474299be7f74fc5353c7'
    },
    gitRepository: null,
    activeWorkspaceMeta: {
      _id: 'wrkm_37eb0468691e4c03857e617eab0edac0',
      type: 'WorkspaceMeta',
      parentId: 'wrk_5551f022d2034b1685762ab966db281b',
      modified: 1677861760767,
      created: 1662132502634,
      activeActivity: null,
      activeEnvironmentId: 'env_6f9571e94edb474eb5e1e37f7b3549f5',
      activeRequestId: 'req_bc8af552f1564c0b8b8e436b3039fa14',
      activeUnitTestSuiteId: null,
      cachedGitLastAuthor: null,
      cachedGitLastCommitTime: null,
      cachedGitRepositoryBranch: null,
      gitRepositoryId: null,
      hasSeen: true,
      paneHeight: 0.5,
      paneWidth: 0.5,
      sidebarFilter: '',
      sidebarHidden: false,
      sidebarWidth: 19,
      pushSnapshotOnInitialize: false
    }
  }
}
[2023-03-07 12:53:57.044] [info]  [FileSystemDriver] Initialized in "/Users/j/Library/Application Support/Insomnia/version-control"
[2023-03-07 12:53:57.053] [info]  [sync] checking for collections which need to be moved into a remote project
[2023-03-07 12:53:57.055] [info]  [FileSystemDriver] Initialized in "/Users/j/Library/Application Support/Insomnia/version-control"
[2023-03-07 12:53:57.066] [info]  [sync] Activated project prj_2acada4185d44b70bc7131947898d984
[2023-03-07 12:53:57.067] [info]  [sync] Activated project prj_2acada4185d44b70bc7131947898d984
[2023-03-07 12:53:57.888] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:53:58.880] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:54:00.164] [info]  [network] Sending req=req_bc8af552f1564c0b8b8e436b3039fa14 env=env_6f9571e94edb474eb5e1e37f7b3549f5
[2023-03-07 12:54:00.232] [info]  [prompt] Used cached value under cmd_key
[2023-03-07 12:54:00.242] [info]  [response tag] Resending dependency
[2023-03-07 12:54:00.243] [info]  [network] Sending req=req_3478266f2b0a4efd91323656642676fa env=env_6f9571e94edb474eb5e1e37f7b3549f5
[2023-03-07 12:54:00.255] [info]  [prompt] Used cached value under cmd_key
[2023-03-07 12:54:00.263] [info]  [response tag] Preventing recursive render
[2023-03-07 12:54:00.398] [info]  [network] Response succeeded req=req_3478266f2b0a4efd91323656642676fa status=200
[2023-03-07 12:54:05.474] [info]  [network] Response succeeded req=req_bc8af552f1564c0b8b8e436b3039fa14 status=504
[2023-03-07 12:54:10.283] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:54:18.377] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:54:34.958] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:54:38.100] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:54:39.029] [info]  Failed to refresh TypeError: i is not a function
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:6:62204
    at Array.map (<anonymous>)
    at foe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:6:62197)
    at pA (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:6:61787)
    at async jp._runGraphQL (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:179:40416)
    at async jp._queryBranches (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:185:128)
    at async jp.getRemoteBranches (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:179:36105)
    at async callback (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:418:5963)
    at async _v (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:179:30150)
    at async file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:418:5934
[2023-03-07 12:54:39.036] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:54:57.520] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:55:57.544] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:56:09.942] [info]  {
  workspaceData: {
    activeWorkspace: {
      _id: 'wrk_5551f022d2034b1685762ab966db281b',
      type: 'Workspace',
      parentId: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      modified: 1662132494814,
      created: 1626446961153,
      name: 'project-name',
      description: '',
      scope: 'collection'
    },
    activeProject: {
      _id: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      type: 'Project',
      parentId: null,
      modified: 1672323832333,
      created: 1672323832333,
      name: "team-name",
      remoteId: 'team_e42d352df7c5474299be7f74fc5353c7'
    },
    gitRepository: null,
    activeWorkspaceMeta: {
      _id: 'wrkm_37eb0468691e4c03857e617eab0edac0',
      type: 'WorkspaceMeta',
      parentId: 'wrk_5551f022d2034b1685762ab966db281b',
      modified: 1677861760767,
      created: 1662132502634,
      activeActivity: null,
      activeEnvironmentId: 'env_6f9571e94edb474eb5e1e37f7b3549f5',
      activeRequestId: 'req_bc8af552f1564c0b8b8e436b3039fa14',
      activeUnitTestSuiteId: null,
      cachedGitLastAuthor: null,
      cachedGitLastCommitTime: null,
      cachedGitRepositoryBranch: null,
      gitRepositoryId: null,
      hasSeen: true,
      paneHeight: 0.5,
      paneWidth: 0.5,
      sidebarFilter: '',
      sidebarHidden: false,
      sidebarWidth: 19,
      pushSnapshotOnInitialize: false
    }
  }
}
[2023-03-07 12:56:09.964] [info]  {}
[2023-03-07 12:56:10.009] [info]  {}
[2023-03-07 12:56:10.110] [info]  Failed to load projects
[2023-03-07 12:56:10.112] [info]  {}
[2023-03-07 12:56:10.145] [warn]  Failed to load backend projects TypeError: i is not a function
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:6:62204
    at Array.map (<anonymous>)
    at foe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:6:62197)
    at pA (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:6:61787)
    at async jp._runGraphQL (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:179:40416)
    at async jp._queryBackendProjects (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:270:79)
    at async Module.C (file:///Applications/Insomnia.app/Contents/Resources/app.asar/remote-collections.50e3694b.js:1:1008)
    at async Ug (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:107:22846)
    at async Ee (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:107:17954)
[2023-03-07 12:56:10.146] [info]  {}
[2023-03-07 12:56:11.416] [info]  {}
[2023-03-07 12:56:11.435] [info]  {
  workspaceData: {
    activeWorkspace: {
      _id: 'wrk_5551f022d2034b1685762ab966db281b',
      type: 'Workspace',
      parentId: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      modified: 1662132494814,
      created: 1626446961153,
      name: 'project-name',
      description: '',
      scope: 'collection'
    },
    activeProject: {
      _id: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      type: 'Project',
      parentId: null,
      modified: 1672323832333,
      created: 1672323832333,
      name: "team-name",
      remoteId: 'team_e42d352df7c5474299be7f74fc5353c7'
    },
    gitRepository: null,
    activeWorkspaceMeta: {
      _id: 'wrkm_37eb0468691e4c03857e617eab0edac0',
      type: 'WorkspaceMeta',
      parentId: 'wrk_5551f022d2034b1685762ab966db281b',
      modified: 1677861760767,
      created: 1662132502634,
      activeActivity: null,
      activeEnvironmentId: 'env_6f9571e94edb474eb5e1e37f7b3549f5',
      activeRequestId: 'req_bc8af552f1564c0b8b8e436b3039fa14',
      activeUnitTestSuiteId: null,
      cachedGitLastAuthor: null,
      cachedGitLastCommitTime: null,
      cachedGitRepositoryBranch: null,
      gitRepositoryId: null,
      hasSeen: true,
      paneHeight: 0.5,
      paneWidth: 0.5,
      sidebarFilter: '',
      sidebarHidden: false,
      sidebarWidth: 19,
      pushSnapshotOnInitialize: false
    }
  }
}
[2023-03-07 12:56:11.524] [info]  [sync] Activated project prj_2acada4185d44b70bc7131947898d984
[2023-03-07 12:56:11.525] [info]  [sync] Activated project prj_2acada4185d44b70bc7131947898d984
[2023-03-07 12:56:11.603] [info]  Failed to load projects
[2023-03-07 12:56:11.605] [info]  {
  workspaceData: {
    activeWorkspace: {
      _id: 'wrk_5551f022d2034b1685762ab966db281b',
      type: 'Workspace',
      parentId: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      modified: 1662132494814,
      created: 1626446961153,
      name: 'project-name',
      description: '',
      scope: 'collection'
    },
    activeProject: {
      _id: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      type: 'Project',
      parentId: null,
      modified: 1672323832333,
      created: 1672323832333,
      name: "team-name",
      remoteId: 'team_e42d352df7c5474299be7f74fc5353c7'
    },
    gitRepository: null,
    activeWorkspaceMeta: {
      _id: 'wrkm_37eb0468691e4c03857e617eab0edac0',
      type: 'WorkspaceMeta',
      parentId: 'wrk_5551f022d2034b1685762ab966db281b',
      modified: 1677861760767,
      created: 1662132502634,
      activeActivity: null,
      activeEnvironmentId: 'env_6f9571e94edb474eb5e1e37f7b3549f5',
      activeRequestId: 'req_bc8af552f1564c0b8b8e436b3039fa14',
      activeUnitTestSuiteId: null,
      cachedGitLastAuthor: null,
      cachedGitLastCommitTime: null,
      cachedGitRepositoryBranch: null,
      gitRepositoryId: null,
      hasSeen: true,
      paneHeight: 0.5,
      paneWidth: 0.5,
      sidebarFilter: '',
      sidebarHidden: false,
      sidebarWidth: 19,
      pushSnapshotOnInitialize: false
    }
  }
}
[2023-03-07 12:56:11.670] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:56:12.560] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:56:13.555] [info]  Failed to refresh TypeError: i is not a function
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:6:62204
    at Array.map (<anonymous>)
    at foe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:6:62197)
    at pA (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:6:61787)
    at async jp._runGraphQL (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:179:40416)
    at async jp._queryBranches (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:185:128)
    at async jp.getRemoteBranches (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:179:36105)
    at async callback (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:418:5963)
    at async _v (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:179:30150)
    at async file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:418:5934
[2023-03-07 12:56:13.558] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:56:17.329] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:56:36.043] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:57:11.227] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:57:11.679] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:57:16.318] [info]  {
  workspaceData: {
    activeWorkspace: {
      _id: 'wrk_5551f022d2034b1685762ab966db281b',
      type: 'Workspace',
      parentId: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      modified: 1662132494814,
      created: 1626446961153,
      name: 'project-name',
      description: '',
      scope: 'collection'
    },
    activeProject: {
      _id: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      type: 'Project',
      parentId: null,
      modified: 1672323832333,
      created: 1672323832333,
      name: "team-name",
      remoteId: 'team_e42d352df7c5474299be7f74fc5353c7'
    },
    gitRepository: null,
    activeWorkspaceMeta: {
      _id: 'wrkm_37eb0468691e4c03857e617eab0edac0',
      type: 'WorkspaceMeta',
      parentId: 'wrk_5551f022d2034b1685762ab966db281b',
      modified: 1677861760767,
      created: 1662132502634,
      activeActivity: null,
      activeEnvironmentId: 'env_6f9571e94edb474eb5e1e37f7b3549f5',
      activeRequestId: 'req_bc8af552f1564c0b8b8e436b3039fa14',
      activeUnitTestSuiteId: null,
      cachedGitLastAuthor: null,
      cachedGitLastCommitTime: null,
      cachedGitRepositoryBranch: null,
      gitRepositoryId: null,
      hasSeen: true,
      paneHeight: 0.5,
      paneWidth: 0.5,
      sidebarFilter: '',
      sidebarHidden: false,
      sidebarWidth: 19,
      pushSnapshotOnInitialize: false
    }
  }
}
[2023-03-07 12:57:16.330] [info]  {
  workspaceData: {
    activeWorkspace: {
      _id: 'wrk_5551f022d2034b1685762ab966db281b',
      type: 'Workspace',
      parentId: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      modified: 1662132494814,
      created: 1626446961153,
      name: 'project-name',
      description: '',
      scope: 'collection'
    },
    activeProject: {
      _id: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      type: 'Project',
      parentId: null,
      modified: 1672323832333,
      created: 1672323832333,
      name: "team-name",
      remoteId: 'team_e42d352df7c5474299be7f74fc5353c7'
    },
    gitRepository: null,
    activeWorkspaceMeta: {
      _id: 'wrkm_37eb0468691e4c03857e617eab0edac0',
      type: 'WorkspaceMeta',
      parentId: 'wrk_5551f022d2034b1685762ab966db281b',
      modified: 1677861760767,
      created: 1662132502634,
      activeActivity: null,
      activeEnvironmentId: 'env_6f9571e94edb474eb5e1e37f7b3549f5',
      activeRequestId: 'req_bc8af552f1564c0b8b8e436b3039fa14',
      activeUnitTestSuiteId: null,
      cachedGitLastAuthor: null,
      cachedGitLastCommitTime: null,
      cachedGitRepositoryBranch: null,
      gitRepositoryId: null,
      hasSeen: true,
      paneHeight: 0.5,
      paneWidth: 0.5,
      sidebarFilter: '',
      sidebarHidden: false,
      sidebarWidth: 19,
      pushSnapshotOnInitialize: false
    }
  }
}
[2023-03-07 12:57:16.340] [info]  {}
[2023-03-07 12:57:16.353] [info]  {}
[2023-03-07 12:57:16.490] [info]  Failed to load projects
[2023-03-07 12:57:16.492] [info]  {}
[2023-03-07 12:57:16.500] [warn]  Failed to load backend projects TypeError: i is not a function
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:6:62204
    at Array.map (<anonymous>)
    at foe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:6:62197)
    at pA (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:6:61787)
    at async jp._runGraphQL (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:179:40416)
    at async jp._queryBackendProjects (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:270:79)
    at async Module.C (file:///Applications/Insomnia.app/Contents/Resources/app.asar/remote-collections.50e3694b.js:1:1008)
    at async Ug (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:107:22846)
    at async Ee (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.0216f33a.js:107:17954)
[2023-03-07 12:57:16.501] [info]  {}
[2023-03-07 12:57:17.800] [info]  {}
[2023-03-07 12:57:17.814] [info]  {
  workspaceData: {
    activeWorkspace: {
      _id: 'wrk_5551f022d2034b1685762ab966db281b',
      type: 'Workspace',
      parentId: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      modified: 1662132494814,
      created: 1626446961153,
      name: 'project-name',
      description: '',
      scope: 'collection'
    },
    activeProject: {
      _id: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      type: 'Project',
      parentId: null,
      modified: 1672323832333,
      created: 1672323832333,
      name: "team-name",
      remoteId: 'team_e42d352df7c5474299be7f74fc5353c7'
    },
    gitRepository: null,
    activeWorkspaceMeta: {
      _id: 'wrkm_37eb0468691e4c03857e617eab0edac0',
      type: 'WorkspaceMeta',
      parentId: 'wrk_5551f022d2034b1685762ab966db281b',
      modified: 1677861760767,
      created: 1662132502634,
      activeActivity: null,
      activeEnvironmentId: 'env_6f9571e94edb474eb5e1e37f7b3549f5',
      activeRequestId: 'req_bc8af552f1564c0b8b8e436b3039fa14',
      activeUnitTestSuiteId: null,
      cachedGitLastAuthor: null,
      cachedGitLastCommitTime: null,
      cachedGitRepositoryBranch: null,
      gitRepositoryId: null,
      hasSeen: true,
      paneHeight: 0.5,
      paneWidth: 0.5,
      sidebarFilter: '',
      sidebarHidden: false,
      sidebarWidth: 19,
      pushSnapshotOnInitialize: false
    }
  }
}
[2023-03-07 12:57:17.892] [info]  [sync] Activated project prj_2acada4185d44b70bc7131947898d984
[2023-03-07 12:57:17.892] [info]  [sync] Activated project prj_2acada4185d44b70bc7131947898d984
[2023-03-07 12:57:17.980] [info]  Failed to load projects
[2023-03-07 12:57:17.982] [info]  {
  workspaceData: {
    activeWorkspace: {
      _id: 'wrk_5551f022d2034b1685762ab966db281b',
      type: 'Workspace',
      parentId: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      modified: 1662132494814,
      created: 1626446961153,
      name: 'project-name',
      description: '',
      scope: 'collection'
    },
    activeProject: {
      _id: 'proj_team_e42d352df7c5474299be7f74fc5353c7',
      type: 'Project',
      parentId: null,
      modified: 1672323832333,
      created: 1672323832333,
      name: "team-name",
      remoteId: 'team_e42d352df7c5474299be7f74fc5353c7'
    },
    gitRepository: null,
    activeWorkspaceMeta: {
      _id: 'wrkm_37eb0468691e4c03857e617eab0edac0',
      type: 'WorkspaceMeta',
      parentId: 'wrk_5551f022d2034b1685762ab966db281b',
      modified: 1677861760767,
      created: 1662132502634,
      activeActivity: null,
      activeEnvironmentId: 'env_6f9571e94edb474eb5e1e37f7b3549f5',
      activeRequestId: 'req_bc8af552f1564c0b8b8e436b3039fa14',
      activeUnitTestSuiteId: null,
      cachedGitLastAuthor: null,
      cachedGitLastCommitTime: null,
      cachedGitRepositoryBranch: null,
      gitRepositoryId: null,
      hasSeen: true,
      paneHeight: 0.5,
      paneWidth: 0.5,
      sidebarFilter: '',
      sidebarHidden: false,
      sidebarWidth: 19,
      pushSnapshotOnInitialize: false
    }
  }
}
[2023-03-07 12:57:18.032] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:58:18.069] [info]  Failed to compare remote branches i is not a function
[2023-03-07 12:59:18.062] [info]  Failed to compare remote branches i is not a function
[2023-03-07 13:00:18.057] [info]  Failed to compare remote branches i is not a function
[2023-03-07 13:01:18.049] [info]  Failed to compare remote branches i is not a function
[2023-03-07 13:02:18.074] [info]  Failed to compare remote branches i is not a function
[2023-03-07 13:03:18.078] [info]  Failed to compare remote branches i is not a function
[2023-03-07 13:04:18.060] [info]  Failed to compare remote branches i is not a function
[2023-03-07 13:05:18.063] [info]  Failed to compare remote branches i is not a function
[2023-03-07 13:05:28.157] [info]  Failed to compare remote branches i is not a function
[2023-03-07 13:06:03.430] [info]  Failed to compare remote branches i is not a function
[2023-03-07 13:06:18.073] [info]  Failed to compare remote branches i is not a function
[2023-03-07 13:07:18.067] [info]  Failed to compare remote branches i is not a function
[2023-03-07 13:08:18.058] [info]  Failed to compare remote branches i is not a function
[2023-03-07 13:09:10.288] [info]  Failed to compare remote branches i is not a function
[2023-03-07 13:09:18.059] [info]  Failed to compare remote branches i is not a function

```

</details> 

About Insomnia:
```
Version: Insomnia 2022.7.5 Build date: 1/19/2023 OS: Darwin arm64 21.6.0 Electron: 22.0.0 Node: 16.17.1 V8: 10.8.168.20-electron.0 Architecture: arm64
```

### Insomnia Version

2022.7.5 / 2023.2.2

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6 / Ventura 13.4.1 (22F82)

### Installation method

Download dmg, dropped app into programs

**Comment by julianschelker** [comment]
I still can't push or pull any change from my team, not with reinstall or anything. See screenshot of the branches view.
Hovering over "create snapshot / pull snapshots / push snapshots" shows forbidden mousepointer and clicking on them does nothing.

![grafik](https://github.com/Kong/insomnia/assets/101803738/37906373-af5e-4ca6-a6d9-c707a410c2cc)

![grafik](https://github.com/Kong/insomnia/assets/101803738/ca675b45-ec5a-4475-8ad3-175f720f6c8c)
