### ISSUE TITLE
Failed to render cc

### ISSUE THREAD

**Issue by dave-amato** [getinsomnia/insomnia#5841]
### Expected Behavior

App does not start up correctly

### Actual Behavior

Stack trace
`TypeError: Cannot read properties of null (reading 'url')
    at x (file:///C:/Users/xxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/debug.93612eab.js:34:20412)
    at Array.map (<anonymous>)
    at Jr (file:///C:/Users/xxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/debug.93612eab.js:34:22049)
    at CD (file:///C:/Users/xxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:65:19571)
    at z9 (file:///C:/Users/xxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:44475)
    at U9 (file:///C:/Users/xxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:40098)
    at Eue (file:///C:/Users/xxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:40024)
    at t1 (file:///C:/Users/xxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:39875)
    at RC (file:///C:/Users/xxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:36205)
    at F9 (file:///C:/Users/xxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:35149)
    at D (file:///C:/Users/xxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:52:1648)
    at Immediate.ue [as _onImmediate] (file:///C:/Users/xxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)`

### Reproduction Steps

On app start up

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 2023.1.0
Build date: 2023/03/09
OS: Windows_NT x64 10.0.19045
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

### Insomnia Version

2023.1.0

### What operating system are you using?

Windows

### Operating System Version

 Windows_NT x64 10.0.19045

### Installation method

Downloaded from insomnia

### Last Known Working Insomnia version

NA

**Comment by brandonhein** [comment]
I was getting that too.  Appeared to be an issue on one of the Debug HTTP requests.  Once I got this error, it couldn't Debug any other request.

I choose another HTTP request that I have saved, toggled to the 'Design' tab up top, then back to 'Debug'... and it cleared this error.  But as soon as I selected the bottom request (which appeared to be the one that caused it), the error showed again.

I just recreated that request, did the 'Design'/'Debug' toggle... and I don't have the issue anymore.

**Comment by ldvtlucas** [comment]
I was having the same issue, it wasn't all requests, just certain ones. 

While testing I discovered a workarroud, if I duplicate the request and leave the collection while the new one is selected, I am able to use it normally, but when I click on a jammed one, it breaks everyone of them.

I duplicated all the broken requests, and deleted them and now everything works as it should.

**Comment by leoferreiralima** [comment]
@ldvtlucas your solution works for me too
