### ISSUE TITLE
Fail to render cc when trying to select a json path from the history

### ISSUE THREAD

**Issue by Totalus** [getinsomnia/insomnia#5846]
### Actual Behavior

This is happening with only one of my queries.

In the response section, when I click on the little clock icon. I get the list of last jsonpath queries used :

![image](https://user-images.githubusercontent.com/34516402/225089191-c5076b80-1b14-405b-af34-cc08dd7876e2.png)

As soon as I hover any of them with my mouse (without clicking), I get the following Application Error that pops up:

```
Error: Failed to execute 'querySelector' on 'Element': '[data-key="$.*.catalog[?(@.type="network")].endpoints[?(@.interface="public" && @.region_id="UK")]"]' is not a valid selector.
    at file:///C:/Users/<User>/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:80:112908
    at Vx (file:///C:/Users/<User>/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:24458)
    at Vp (file:///C:/Users/<User>/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:42799)
    at file:///C:/Users/<User>/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:41058
    at D (file:///C:/Users/<User>/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:52:1648)
    at Immediate.ue [as _onImmediate] (file:///C:/Users/<User>/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)
```

### Reproduction Steps

I don't know a way currently to reproduce this systematically. As stated, it only happens with one of my queries right now.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Hovering the items in the list should highlight the items and clicking on one should promote it as the current jsonpath query.

### Insomnia Version

2023.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Family version 21H2

### Installation method

Chocolatey

**Comment by drakiula** [comment]
I am encountering a similar issue:
Stacktrace:
```
Error: Failed to execute 'querySelector' on 'Element': '[data-key="$[?(@.skillCategory.startsWith("Io"))]"]' is not a valid selector.
    at file:///opt/Insomnia/resources/app.asar/index.f53f8b5a.js:80:120040
    at ME (file:///opt/Insomnia/resources/app.asar/index.f53f8b5a.js:67:24458)
    at ch (file:///opt/Insomnia/resources/app.asar/index.f53f8b5a.js:67:42799)
    at file:///opt/Insomnia/resources/app.asar/index.f53f8b5a.js:67:41058
    at N (file:///opt/Insomnia/resources/app.asar/index.f53f8b5a.js:52:1615)
    at Immediate.le [as _onImmediate] (file:///opt/Insomnia/resources/app.asar/index.f53f8b5a.js:52:1987)
    at process.processImmediate (node:internal/timers:466:21)
```
I started seeing this issue today after upgrading to version below:

- Version: Insomnia 2023.2.2
- Build date: 5/17/2023
- OS: Linux x64 6.2.0-10007-tuxedo
- Electron: 22.0.0
- Node: 16.17.1
- V8: 10.8.168.20-electron.0
- Architecture: x64

**Comment by iNaD** [comment]
Stumbled over this error when the returned data changed and I needed a history entry. When hovering an entry with an invalid selector (e.g. the json "node" does not exist anymore in the current response) it throws the error.

```
Error: Failed to execute 'querySelector' on 'Element': '[data-key="$.dataExports[?(@.attributes.stateCode != "XXX")]"]' is not a valid selector.
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.72ff2971.js:80:119910
    at PE (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.72ff2971.js:67:24458)
    at uh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.72ff2971.js:67:42799)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.72ff2971.js:67:41058
    at N (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.72ff2971.js:52:1615)
    at Immediate.ce [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.72ff2971.js:52:1987)
    at process.processImmediate (node:internal/timers:466:21)
```

- Version: Insomnia 2023.3.0
- Build date: 6/27/2023
- OS: Darwin arm64 22.5.0
- Electron: 22.3.11
- Node: 16.17.1
- V8: 10.8.168.25-electron.0
- Architecture: arm64

**Comment by wfahnestock** [comment]
Just ran into this as well. Seems the problem is worse now than all the previous comments as now even opening the query history window, this problem will occur.

```
Error: Failed to execute 'querySelector' on 'Element': '[data-key="$.tables[?(@.name=="campus")]"]' is not a valid selector.
    at file:///C:/Users/wfahnestock/AppData/Local/insomnia/app-2023.4.0/resources/app.asar/index.70d0495f.js:80:119955
    at RE (file:///C:/Users/wfahnestock/AppData/Local/insomnia/app-2023.4.0/resources/app.asar/index.70d0495f.js:67:24458)
    at ch (file:///C:/Users/wfahnestock/AppData/Local/insomnia/app-2023.4.0/resources/app.asar/index.70d0495f.js:67:42799)
    at file:///C:/Users/wfahnestock/AppData/Local/insomnia/app-2023.4.0/resources/app.asar/index.70d0495f.js:67:41058
    at N (file:///C:/Users/wfahnestock/AppData/Local/insomnia/app-2023.4.0/resources/app.asar/index.70d0495f.js:52:1615)
    at Immediate.ce [as _onImmediate] (file:///C:/Users/wfahnestock/AppData/Local/insomnia/app-2023.4.0/resources/app.asar/index.70d0495f.js:52:1987)
    at process.processImmediate (node:internal/timers:471:21)
```

Version: Insomnia 2023.4.0
Build date: 7/4/2023
OS: Windows_NT x64 10.0.19045
Electron: 23.3.9
Node: 18.12.1
V8: 11.0.226.20-electron.0
Architecture: x64

**Comment by foxt** [comment]
Seems to occur anytime you have a JSONPath with a `"` in it.
