### ISSUE TITLE
Insomnia REST client fails to start after upgrade on Debian 10

### ISSUE THREAD

**Issue by anishcorratech** [getinsomnia/insomnia#5847]
### Expected Behavior

I expect to see Insomnia REST client to work normally after a update.
I am using Debian GNU/Linux 10 (Buster), Very recently I received a software upgrade for Insomnia REST client.

```
insomnia_2023.1.0_amd64.deb 
```

After upgrading to insomnia_2023.1.0 the application is not launching and have become unusable.

### Actual Behavior

Insomnia is not working properly. The UI does not show up.
When I tried to ran from console, I see this:

```
CORRA\corra-151@COK-LAP-008:~$ insomnia
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.UWAWqp)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
```

### Reproduction Steps

1. Go To Linux Bash Terninal
2. Launch Insomnia REST client
3. Insomnia REST client is not launching
4. It also emits some `Uncaught Exception` in terminal.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.VdtvfI)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.1.0

### What operating system are you using?

Other Linux

### Operating System Version

Debian GNU/Linux 10

### Installation method

apt package manager

**Comment by santosalan** [comment]
The problem persists.

**Comment by anishcorratech** [comment]
I have rolled back to `Insomnia.Core-2022.6.0.deb`

https://github.com/Kong/insomnia/releases/tag/core%402022.6.0

This version of Insomnia is working fine on Debian 10.

For now I will stay on this version.

Thanks,
Anish
