### ISSUE TITLE
Failed to render cc

### ISSUE THREAD

**Issue by leilaturki** [getinsomnia/insomnia#5876]
### Expected Behavior

expected behaviour is to be able so launch request from insomnia like I usually do. i am blocked with this error application message. here is the stack trace
TypeError: Cannot read properties of null (reading 'url')
    at x (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/debug.93612eab.js:34:20412)
    at Array.map (<anonymous>)
    at Jr (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/debug.93612eab.js:34:22049)
    at CD (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:65:19571)
    at z9 (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:44475)
    at U9 (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:40098)
    at Eue (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:40024)
    at t1 (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:39875)
    at RC (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:36205)
    at F9 (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:35149)
    at D (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:52:1648)
    at Immediate.ue [as _onImmediate] (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)

### Actual Behavior

TypeError: Cannot read properties of null (reading 'url')
    at x (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/debug.93612eab.js:34:20412)
    at Array.map (<anonymous>)
    at Jr (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/debug.93612eab.js:34:22049)
    at CD (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:65:19571)
    at z9 (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:44475)
    at U9 (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:40098)
    at Eue (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:40024)
    at t1 (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:39875)
    at RC (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:36205)
    at F9 (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:35149)
    at D (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:52:1648)
    at Immediate.ue [as _onImmediate] (file:///C:/Users/lturki/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)
![image](https://user-images.githubusercontent.com/129766203/229538246-de866971-ced4-420a-b4bf-742d690839ca.png)

### Reproduction Steps

1- open insomnia 
2 - get the application error box
3 - I try to close it and launch a request
4 - send a request : nothing happen and in core response I have : Render Failure : Cannot read properties of null ( reading 'url') 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I happened on all my HTTP requests, I am not able to send any request. even by adding new ones, it seems that the problem is at the start of the application

### Insomnia Version

2023.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

download insomnia.exe

### Last Known Working Insomnia version

2023.03.31

**Comment by annagomez-infotrack** [comment]
having the same issue

Stack trace
```
TypeError: Cannot read properties of null (reading 'url')
    at x (file:///C:/Users/anna.gomez/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/debug.93612eab.js:34:20412)
    at Array.map (<anonymous>)
    at Jr (file:///C:/Users/anna.gomez/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/debug.93612eab.js:34:22049)
    at CD (file:///C:/Users/anna.gomez/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:65:19571)
    at z9 (file:///C:/Users/anna.gomez/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:44475)
    at U9 (file:///C:/Users/anna.gomez/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:40098)
    at Eue (file:///C:/Users/anna.gomez/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:40024)
    at t1 (file:///C:/Users/anna.gomez/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:39875)
    at RC (file:///C:/Users/anna.gomez/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:36205)
    at F9 (file:///C:/Users/anna.gomez/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:35149)
    at D (file:///C:/Users/anna.gomez/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:52:1648)
    at Immediate.ue [as _onImmediate] (file:///C:/Users/anna.gomez/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)
```

Version 2023.1.0
Operating System: Windows 11

**Comment by dragonhades** [comment]
having the same issue
OS win11

Version: Insomnia 2023.1.0
Build date: 2023/3/9
OS: Windows_NT x64 10.0.22000
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

Stack trace
TypeError: Cannot read properties of null (reading 'url')
    at x (file:///C:/Users/xxxxxxxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/debug.93612eab.js:34:20412)
    at Array.map (<anonymous>)
    at Jr (file:///C:/Users/xxxxxxxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/debug.93612eab.js:34:21810)
    at CD (file:///C:/Users/xxxxxxxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:65:19571)
    at z9 (file:///C:/Users/xxxxxxxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:44475)
    at U9 (file:///C:/Users/xxxxxxxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:40098)
    at Eue (file:///C:/Users/xxxxxxxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:40024)
    at t1 (file:///C:/Users/xxxxxxxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:39875)
    at RC (file:///C:/Users/xxxxxxxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:36205)
    at LL (file:///C:/Users/xxxxxxxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:37019)
    at nf (file:///C:/Users/xxxxxxxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:65:3288)
    at file:///C:/Users/xxxxxxxx/AppData/Local/insomnia/app-2023.1.0/resources/app.asar/index.6916a4f6.js:67:34511
