### ISSUE TITLE
Change of a request in a tag within the environment editor does not persist

### ISSUE THREAD

**Issue by irobin591** [getinsomnia/insomnia#6163]
### Expected Behavior

When updating the environment variables and changing the selected request within a tag, this should be saved and used for all future requests.

### Actual Behavior

The new request seems to be saved until the environment editor gets closed.
After on running subsequent requests using the environment variable, the data is still the old data and does not reflect the changes.
After re-opening the environment editor, the request has changed back to the old state.

```
Uncaught (in promise) Error: TypeError: context.context.getEnvironmentId is not a function
    at index.ts:85:26
    at environment.js:20:5
    at RawTask.call (browser-asap.js:48:1)
    at MutationObserver.flush (browser-raw.js:52:1)
```

### Reproduction Steps

1. Create a new collection
2. Create a request to `https://www.google.com`
3. Open the environment editor
4. Add a tag with "Response → Raw Body"
5. Select the previously created request
6. Press 'Done'. Note that the environment variable seems to be set correctly
7. Observe the error in the console
8. Close and reopen the environment editor
9. Observe the red response tag without the selected request

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This happens on three different MacBooks on different versions of Insomnia.

### Insomnia Version

2023.5.0-beta.2 & 2023.4.0 & 2023.2.2

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.4.1 (M1) & macOS Ventura 13.4.1 (c) (Intel) & macOS Ventura 13.4.1 (Intel)

### Installation method

insomnia.rest

**Comment by kyle-miller** [comment]
I am running in to the same issue. I found a potential work around. Changing the tag and clicking Done will cause the noted error, as will clicking Close on the environment window, however, changing to another Base or Sub Environment does not seem to show the same error and the Tag value appears to persist.

Version: Insomnia 2023.4.0
Build date: 7/4/2023
OS: Darwin arm64 21.3.0
Electron: 23.3.9
Node: 18.12.1
V8: 11.0.226.20-electron.0
Architecture: arm64

**Comment by kyle-miller** [comment]
I have a Windows user seeing the same issue and the workaround that I described above does not allow them to persist the changes as it does on the Mac.

Version: Insomnia 2023.4.0
Build date: 7/4/2023
OS: Windows_NT x64 10.0.19045
Electron: 23.3.9
Node: 18.12.1
V8: 11.0.226.20-electron.0
Architecture: x64
