### ISSUE TITLE
Can't export collection, render failure error

### ISSUE THREAD

**Issue by mnemyx** [getinsomnia/insomnia#6294]
### Expected Behavior

I get an export of the collection

### Actual Behavior

I get the following error & am unable to see my collections until I force quit and restart Insomnia

`Render Failure: Cannot destructure property 'requestTree' of 'Nr(...)' as it is undefined`

Stacktrace:
```
TypeError: Cannot destructure property 'requestTree' of 'Nr(...)' as it is undefined.
    at sH (file:///C:/Users/40000715/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:193:6824)
    at XA (file:///C:/Users/40000715/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:116:19553)
    at H7 (file:///C:/Users/40000715/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:44101)
    at U7 (file:///C:/Users/40000715/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:39819)
    at Vge (file:///C:/Users/40000715/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:39745)
    at ax (file:///C:/Users/40000715/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:39596)
    at QC (file:///C:/Users/40000715/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:35959)
    at rL (file:///C:/Users/40000715/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:36764)
    at qu (file:///C:/Users/40000715/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:116:3288)
    at file:///C:/Users/40000715/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:34286
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
```

Screenshots - 
![image](https://github.com/Kong/insomnia/assets/770706/3406ba27-5c63-464d-87f7-496140ac3c46)

![image](https://github.com/Kong/insomnia/assets/770706/42db1d7f-b135-4388-b859-7d6435cf7352)

### Reproduction Steps

1. Click the triple dots on a collection
2. Select 'Export'

![image](https://github.com/Kong/insomnia/assets/770706/4702d649-f7b0-430b-999b-1efad67d0514)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise Version 21H2

### Installation method

Download from insomnia.rest

**Comment by jackkav** [comment]
@mnemyx Thanks for the thorough report, we'll add a fix into the next minor release.

**Comment by mnemyx** [comment]
It doesn't error out in the latest minor version, but it is just an empty screen now - 
![image](https://github.com/Kong/insomnia/assets/770706/550f681b-8a50-40ef-b57e-b9678f9f496c)

**Comment by jackkav** [comment]
Tracked in #6307
