### ISSUE TITLE
Insomnia lagging, high CPU usage and very slow in general

### ISSUE THREAD

**Issue by Jozefwl** [getinsomnia/insomnia#6297]
### Expected Behavior

Expected behavior is that i should be able to open folders under a second, send requests, export my workspace and open my workspace.

### Actual Behavior

Folders take about 10 seconds to open, requests send after waiting for around 15s, exporting a workspace results in an error, opening a workspace does absolutely nothing at all.

### Reproduction Steps

1. Open random workspace
2. Open folder
3. Send request
4. Try to export workspace

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information
**This error arises after i try to export the workspace:**

TypeError: Cannot destructure property 'requestTree' of 'Nr(...)' as it is undefined.
    at sH (file:///C:/Users/Jozef/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:193:6824)
    at XA (file:///C:/Users/Jozef/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:116:19553)
    at H7 (file:///C:/Users/Jozef/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:44101)
    at U7 (file:///C:/Users/Jozef/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:39819)
    at Vge (file:///C:/Users/Jozef/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:39745)
    at ax (file:///C:/Users/Jozef/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:39596)
    at QC (file:///C:/Users/Jozef/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:35959)
    at rL (file:///C:/Users/Jozef/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:36764)
    at qu (file:///C:/Users/Jozef/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:116:3288)
    at file:///C:/Users/Jozef/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:118:34286
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)

### Insomnia Version

2023.5.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 22H2 19045.3324

### Installation method

downloaded from official insomnia website

### Last Known Working Insomnia version

2023.4.0

### Current workaround
Disable automatic update in insomnia
Roll back to version 2023.4.0:
https://github.com/Kong/insomnia/releases/tag/core%402023.4.0

**Comment by Juuldamen** [comment]
Seeing similar behavior since updating to 2023.5.2.

https://github.com/Kong/insomnia/assets/31408341/e997b3ee-491a-484e-afec-8a7aa88bc78b

![image](https://github.com/Kong/insomnia/assets/31408341/0023a232-d74a-40b0-b525-5a43df76f16b)

![image](https://github.com/Kong/insomnia/assets/31408341/0c1c7a7a-a109-41cf-af02-17b54c5ac731)

**Comment by jackkav** [comment]
Thanks for the report, we are aware of this and will have it figured out in an upcoming minor dot release.

**Comment by filfreire** [comment]
@Jozefwl @Juuldamen you should see better performance in [latest patch release 2023.5.4](https://github.com/Kong/insomnia/releases/tag/core%402023.5.4)

**Comment by Jozefwl** [comment]
> @Jozefwl @Juuldamen you should see better performance in [latest patch release 2023.5.4](https://github.com/Kong/insomnia/releases/tag/core%402023.5.4)

Hello, I've updated to 5.4 and even though it says 'fixed issue with export being blank' etc. issues with my Insomnia client still persist, I've confirmed this with a colleague and he has the same issue: Workspace document won't open and export is still blank.

**Comment by filfreire** [comment]
@Jozefwl for the export double check you are on the latest version. Check in About Insomnia menu option which version you have


![image](https://github.com/Kong/insomnia/assets/11976836/1ade718b-04a2-49dc-a0eb-6672b22cf206)

You should see requests on the export menu:

![image](https://github.com/Kong/insomnia/assets/11976836/0b14a214-f295-43d5-bf6e-61107d122eac)
