### ISSUE TITLE
JSONPath history is broken

### ISSUE THREAD

**Issue by foxt** [getinsomnia/insomnia#6374]
### Expected Behavior

You can select previously used JSONPath queries

### Actual Behavior

The application crashes whenever you hover over a more complex JSONPath.
```
Failed to render hc. Please report the error to [our Github Issues](https://github.com/Kong/insomnia/issues)

Stack trace
Error: Failed to execute 'querySelector' on 'Element': '[data-key="$.value[?(@.name == "Foo")]"]' is not a valid selector.
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:118:78623
    at vh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:118:24296)
    at s6 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:118:42448)
    at qbe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:118:41270)
    at Dc (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:118:40309)
    at H_ (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:118:36912)
    at dc (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:116:3288)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:118:34286
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
```

### Reproduction Steps

Hover over a complex JSONPath in the history, for example, `$.value[?(@.name == "Foo")]`

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.6

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6.8 (21G725)

### Installation method

download from insomnia.rest

**Comment by foxt** [comment]
dupe of #5846
