### ISSUE TITLE
[Bug] After upgrading to version 5.12.3, "Generate code" not working

### ISSUE THREAD

**Issue by amig** [getinsomnia/insomnia#640]
- Insomnia Version: 5.12.3
- Operating System: Ubuntu 16.04.3

## Details
After upgrading to version 5.12.3 the Generate code is coming blank. 
![screenshot from 2017-11-30 10-52-52](https://user-images.githubusercontent.com/203434/33421986-acfe0402-d5bc-11e7-98e9-be9f3e86f9fd.png)

**Comment by gschier** [comment]
I can't seem to reproduce this on my end. Do you see any errors in View > Toggle DevTools > Console?

**Comment by amig** [comment]
These are the console errors:
bundle.js:52404 Uncaught (in promise) TypeError: form.pipe is not a function
    at HTTPSnippet.module.exports.HTTPSnippet.prepare (file:///opt/Insomnia/resources/app.asar/bundle.js:52404:14)
    at file:///opt/Insomnia/resources/app.asar/bundle.js:52335:31
    at validator (file:///opt/Insomnia/resources/app.asar/bundle.js:87252:12)
    at Object.request (file:///opt/Insomnia/resources/app.asar/bundle.js:87307:10)
    at file:///opt/Insomnia/resources/app.asar/bundle.js:52330:14
    at Array.forEach (native)
    at new HTTPSnippet (file:///opt/Insomnia/resources/app.asar/bundle.js:52317:11)
    at GenerateCodeModal._generateCode (file:///opt/Insomnia/resources/app.asar/bundle.js:59327:21)
    at <anonymous>
