### ISSUE TITLE
'GLIBC_2.32 not found'  on Debian 11

### ISSUE THREAD

**Issue by bflorat** [getinsomnia/insomnia#6445]
### Expected Behavior

Insomnia runs on Debian 11.

### Actual Behavior

A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.org.chromium.Chromium.UHsSi0)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Insomnia 2023.5.7 crashes under Debian 11 due to GLIBC 2.32 requirement. 

Debian 11 comes with GLIBC 2.31.

### Insomnia Version

2023.5.7

### What operating system are you using?

Other Linux

### Operating System Version

Debian 11

### Installation method

Reproduced with AppImage and .deb

### Last Known Working Insomnia version

2022.7.5

**Comment by jackkav** [comment]
#6133

**Comment by Jictyvoo** [comment]
@jackkav I'm having this same problem when trying to run using Flatpak, to being able to run Insomnia again, I've installed the debian package. But this is broken in flatpak

Command: `flatpak run rest.insomnia.Insomnia`
Output:
```bash
[2:0906/090520.408426:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /run/user/1000/app/rest.insomnia.Insomnia/.org.chromium.Chromium.EelGCQ)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/main/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
Gtk-Message: 09:05:20.946: Failed to load module "appmenu-gtk-module"
Gtk-Message: 09:05:20.975: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:05:20.976: Failed to load module "canberra-gtk-module"
[2:0906/090520.984226:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0906/090520.984249:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```
