### ISSUE TITLE
Application Error: Failed to render - s.spec.info.version.startsWith is not a function

### ISSUE THREAD

**Issue by webdeveloperjon** [getinsomnia/insomnia#6465]
### Expected Behavior

Being able to open Insomnia and access a project or the project selection screen

### Actual Behavior

When opening Insomnia, I instantly get an Application Error "Failed to render . Please report the error to [our Github Issues](https://github.com/Kong/insomnia/issues)". 

![image](https://github.com/Kong/insomnia/assets/32771994/e9ec0de0-7cc4-437e-9116-4228359d4152)

I notice the TypeError Text also occurs in the left hand panel as you can see on the screenshot below: 

![image](https://github.com/Kong/insomnia/assets/32771994/0ebc953e-e321-4ab4-a478-a02143457ef1)

Full stack trace:

```
TypeError: s.spec.info.version.startsWith is not a function
    at children (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/project-a967a15a.js:1:28833)
    at file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9275
    at Object.useMemo (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:116:25888)
    at h2.useMemo (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:9:6238)
    at dl (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9182)
    at kMe (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9613)
    at MMe (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9989)
    at tu (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9737)
    at QMe (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:24100)
    at jS (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:116:19553)
    at w_ (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:1575)
    at rj (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:46077)
    at ej (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:39819)
    at Kbe (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:39745)
    at Kd (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:39596)
    at Ax (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:35959)
    at XB (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:34906)
    at T (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:103:1591)
    at Immediate.he [as _onImmediate] (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:103:1957)
    at process.processImmediate (node:internal/timers:476:21)

```

### Reproduction Steps

1. I open the application

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The application is now unusable because I can't access projects. 
I've also tried going to preferences and exporting the data to JSON but after selecting the export file name it just closes the window and does nothing (I guess, because it wasn't able to load the projects in the first place). 
I use Insomnia reasonably frequently, and this issue has only been occuring the last few days. Definitely with 2023.5.7 and 2023.5.8. 

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro

### Installation method

Download (then auto-updated)

### Last Known Working Insomnia version

2023.5.6 (not 100% sure)

**Comment by cutcas** [comment]
I have the same problem

![image](https://github.com/Kong/insomnia/assets/33638044/6323182b-f046-49b8-8aeb-81de4507bc44)

![image](https://github.com/Kong/insomnia/assets/33638044/2588c56b-a59e-4ef0-9c31-c38984b0fd0b)
