### ISSUE TITLE
Insomnia does not start

### ISSUE THREAD

**Issue by vali-m** [getinsomnia/insomnia#6526]
### Expected Behavior

Start the application and show the collections

### Actual Behavior

I get an the following error:
`Application error: Failed to render . Please report the error to [our Github Issues](https://github.com/Kong/insomnia/issues)`

### Reproduction Steps

I just open the program and it doesn't work

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

`Application Error

Failed to render . Please report the error to [our Github Issues](https://github.com/Kong/insomnia/issues)

Stack trace
TypeError: s.spec.info.version.startsWith is not a function
    at children (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/project-a967a15a.js:1:28833)
    at file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9275
    at Object.useMemo (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:116:25888)
    at h2.useMemo (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:9:6238)
    at dl (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9182)
    at kMe (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9613)
    at MMe (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9989)
    at tu (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9737)
    at QMe (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:24100)
    at jS (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:116:19553)
    at w_ (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:1575)
    at rj (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:46077)
    at ej (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:39819)
    at Kbe (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:39745)
    at Kd (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:39596)
    at Ax (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:35959)
    at XB (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:34906)
    at T (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:103:1591)
    at Immediate.he [as _onImmediate] (file:///C:/Users/vali/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:103:1957)
    at process.processImmediate (node:internal/timers:476:21)
Ok
Login
[Sign Up](https://app.insomnia.rest/app/signup/)

Personal Projects

Personal Projects
PROJECTS (1)
Filter

Render Failure: s.spec.info.version.startsWith is not a function
Preferences
[Made withby Kong](https://konghq.com/)`

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Installed from website

### Last Known Working Insomnia version

The previous version worked

**Comment by webdeveloperjon** [comment]
Hi @vali-m 
This issue was raised here
https://github.com/Kong/insomnia/issues/6465 
and someone has kindly fixed it:
https://github.com/Kong/insomnia/pull/6493
Hopefully we'll see it sorted in the next patch release soon!
Jon
