### ISSUE TITLE
can not work on virtalbox

### ISSUE THREAD

**Issue by nullNullNone** [getinsomnia/insomnia#6566]
### Expected Behavior

A JavaScript error occurred in the main process
cli show this
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.org.chromium.Chromium.HynHWX)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/tmp/.mount_Insomn1k7sx1/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

no  ANY gui launch out

I using Virtualbox.no have gpu card.

### Actual Behavior

show like this
/Insomnia.Core-2023.5.8.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.org.chromium.Chromium.HynHWX)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/tmp/.mount_Insomn1k7sx1/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

### Reproduction Steps

./Insomnia.Core-2023.5.8.AppImage

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

Other Linux

### Operating System Version

parrot os 5.3

### Installation method

./Insomnia.Core-2023.5.8.AppImage

**Comment by filfreire** [comment]
Related to https://github.com/Kong/insomnia/issues/6133 https://github.com/Kong/insomnia/issues/6445
