### ISSUE TITLE
Issue when import from old version(unknown) exported insomnia json file to latest version 8.x.x

### ISSUE THREAD

**Issue by ittrongduc** [getinsomnia/insomnia#6602]
### Expected Behavior

Import successful

### Actual Behavior

Met this error:

Error: Project not found. at a2 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-334620de.js:17:108051) at Module.l (file:///Applications/Insomnia.app/Contents/Resources/app.asar/import-9dfc1356.js:1:906) at async d8 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-334620de.js:31:3691) at async Be (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-334620de.js:30:18468)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.0.0

### What operating system are you using?

macOS

### Operating System Version

MacOS 13.5

### Installation method

Homebrew

### Last Known Working Insomnia version

Previous version of 8.0.0

**Comment by ittrongduc** [comment]
Latest version 8.1.0 is working normally
