### ISSUE TITLE
Clicking on default "Insomnia" project leads to error

### ISSUE THREAD

**Issue by colorando-de** [getinsomnia/insomnia#6665]
### Expected Behavior

The collections in the "Insomnia" default project should show up.

### Actual Behavior

Error occurs: "Render failure: s.spec.info.version.startsWith is not a function" and no collections are shown.

Stack Trace:

TypeError: s.spec.info.version.startsWith is not a function
    at children (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/project-a967a15a.js:1:28833)
    at file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9275
    at Object.TB [as useMemo] (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:116:23938)
    at h2.useMemo (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:9:6238)
    at dl (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9182)
    at kMe (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9613)
    at MMe (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9989)
    at tu (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9737)
    at QMe (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:24100)
    at jS (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:116:19553)
    at w_ (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:1575)
    at rj (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:46077)
    at ej (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:39819)
    at Kbe (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:39745)
    at Kd (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:39596)
    at Ax (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:35959)
    at XB (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:34906)
    at T (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:103:1591)
    at Immediate.he [as _onImmediate] (file:///C:/Users/ColorandoSoftwarel%C3%B6s/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:103:1957)
    at process.processImmediate (node:internal/timers:476:21)

### Reproduction Steps

I cannot reproduce this on a fresh instance. I have the Insomnia project for a long time now, so maybe it's related to older, legacy projects?

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 10.0.22621

### Installation method

Windows Installer

**Comment by filfreire** [comment]
@colorando-de this was fixed form version [8.0.0](https://insomnia.rest/changelog#8.0.0) onwards, feel free to upgrade to latest version of Insomnia.
