### ISSUE TITLE
Render failure when entering DATA tab in preferences after initial installation.

### ISSUE THREAD

**Issue by sky6154** [getinsomnia/insomnia#6700]
### Expected Behavior

Show settings about DATA.

### Actual Behavior

Appears `Failed to render . Please report the error to [our Github Issues](https://github.com/Kong/insomnia/issues)` ui.

Stack trace
```
TypeError: Cannot destructure property 'organizations' of 'Dm(...)' as it is undefined.
    at Pm1 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:1552:24521)
    at xk (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:116:19553)
    at HB (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:118:44101)
    at TB (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:118:39819)
    at vxe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:118:39745)
    at lp (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:118:39596)
    at aw (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:118:35959)
    at hH (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:118:36764)
    at Ls (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:116:3288)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:118:34286
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
```

### Reproduction Steps

1. install insomnia(8.2.0).
2. update insomnia(8.3.0).
3. see `Welcome to Insomnia` UI.(Not logged in yet)
4. enter the `DATA` tab in preferences to import data.
5. appears `failed to render`
6. close preferences window.
7. retry again.
8. the settings window does not appear.

<img width="1270" alt="image" src="https://github.com/Kong/insomnia/assets/8624751/610fbb33-a5b1-4c43-86d8-237cf3855b50">

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Version: Insomnia 8.3.0, Build date: 10/13/2023

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.0

### Installation method

from hompage. https://insomnia.rest/download

**Comment by numanoksas** [comment]
Same issue appears on my end as well. Is there a fix or workaround?
