### ISSUE TITLE
Network connectivity issue: Failed to load Organizations. Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by VernPG** [getinsomnia/insomnia#6746]
### Expected Behavior

Downloaded from site to application folder. Added the app to my desktop. Received the attached error when opening the app. 

<img width="1214" alt="Screenshot 2023-11-01 at 2 37 14 PM" src="https://github.com/Kong/insomnia/assets/140969836/112e37ae-132d-4c21-a682-fb57c2f15489">

### Actual Behavior

After download, attempted to open the app and received "Application Error: Network connectivity issue: Failed to load Organizations. Cannot read properties of undefined (reading 'find')" along with "Error: Network connectivity issue: Failed to load Organizations. Cannot read properties of undefined (reading 'find') at Module.h81 [as indexLoader] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:1255:3621) at async g8 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:31:3691) at async Promise.all (index 2) at async ce (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:30:21936) at async qe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:30:16867) at async we (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-7e64d407.js:30:15043)
"

Attempted deleting account and starting over and rebooting with no luck.

### Reproduction Steps

1. Opened https://insomnia.rest/
2. created free account
3. Selected download for MacOS
4. Downloaded and dragged file into application folder
5. Opened app
6. Received the the application error

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.3.0

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.0

### Installation method

insomnia.rest

**Comment by IBMRob** [comment]
I am hitting the same problems as well

**Comment by joaozarate** [comment]
I'm getting the same message
It was supposed to be fixed https://github.com/Kong/insomnia/issues/6589
```
Version: Insomnia 8.3.0
Build date: 10/13/2023
OS: Linux x64 6.2.0-36-generic
Electron: 25.8.1
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.29-electron.0
Architecture: x64
```
My workaround for this was to downgrade to 8.2.0

```
snap list insomnia --all
Name      Version  Rev  Tracking       Publisher    Notes
insomnia  8.2.0    231  latest/stable  getinsomnia  disabled
insomnia  8.3.0    233  latest/stable  getinsomnia  -

sudo snap revert insomnia --revision 231
```

**Comment by obahareth** [comment]
I am also getting the same:

```
Version: Insomnia 8.3.0
Build date: 10/13/2023
OS: Darwin arm64 22.1.0
Electron: 25.8.1
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.29-electron.0
Architecture: arm64
```

**Comment by bertmeeuws** [comment]
Same here, updated and restarted.

```
Version: Insomnia 8.3.0
Build date: 10/13/2023
OS: Darwin arm64 22.6.0
Electron: 25.8.1
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.29-electron.0
Architecture: arm64
```

**Comment by mehdico** [comment]
Same error on three versions:

```
Version: Insomnia 8.3.0
Build date: 10/13/2023
OS: Darwin x64 23.0.0
Electron: 25.8.1
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.29-electron.0
Architecture: x64
```
AND
```
Version: Insomnia 8.4.5
Build date: 11/23/2023
OS: Darwin x64 23.0.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: x64
```
AND
```
Version: Insomnia 8.2.0
Build date: 10/4/2023
OS: Darwin x64 23.0.0
Electron: 25.8.1
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.29-electron.0
Architecture: x64
```

I don't even know how to export my data!

**Comment by torbjorngelotte** [comment]
Same for me.
I found that switching my Corporate Wifi to my private at home or my mobile-hotspot-wifi then it worked. So something with the corporate network (which I off-course need to use normally)
