### ISSUE TITLE
Application Error: Failed to Render

### ISSUE THREAD

**Issue by ttelford** [getinsomnia/insomnia#6751]
### Expected Behavior

I attempted to import a publicly available OpenAPI Description ([YugabyteDB Anywhere API](https://stoplight.io/api/v1/projects/yugabyte/yugabyte-platform/nodes/api-specs/platform/platform.swagger.json)); I expected Insomnia to be able to import it, or at least report that there was an error.

Instead, I was greeted with an error page and a message to report the Error to Github. So, Here I am.

### Actual Behavior

An error window appears with the message: Application Error, Please report to our Github Issues.

> Error: Can't insert key req_d5c8473d72834b318989027fd0219414, it violates the unique constraint at _AVLTree.insert (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/binary-search-tree/lib/avltree.js:273:19) at AVLTree.insert (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/binary-search-tree/lib/avltree.js:307:27) at Index.insert (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nedb/lib/indexes.js:77:15) at Datastore.addToIndexes (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nedb/lib/datastore.js:180:29) at Datastore._insertInCache (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nedb/lib/datastore.js:402:10) at Datastore._insert (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nedb/lib/datastore.js:348:10) at /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nedb/lib/executor.js:40:13 at Immediate.process (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:731:21) at process.processImmediate (node:internal/timers:476:21)

### Reproduction Steps

1. Load Insomnia
2. Create a new Collection
3. Import from URL: https://stoplight.io/api/v1/projects/yugabyte/yugabyte-platform/nodes/api-specs/platform/platform.swagger.json

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I'm prompted to attempt reloading Insomnia - I do, and there is a partial import - with many empty folders.

### Insomnia Version

8.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.6 (22G120)

### Installation method

Download from insomnia.rest

**Comment by ttelford** [comment]
Additional:  If I do _not_ create a new collection and import, Insomnia DOES import without the message above.

Which is an interesting difference. I get an API Spec - it's riddled with errors & warnings (Which I imagine I can try to fix & send upstream) but it imports, and I can see the swagger preview.

However, the collection list is completely empty - in spite of Insomnia having claimed to have imported a couple hundred calls into the collection.

Note: The swagger is rather large:  close to 1 MiB in size...
