### ISSUE TITLE
Render Failure: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by fabinajm** [getinsomnia/insomnia#6801]
### Expected Behavior

After update i can't open the app.

Render Failure: Cannot read properties of undefined (reading 'match')

### Actual Behavior

After update i can't open the app.

Render Failure: Cannot read properties of undefined (reading 'match')

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

latest

### What operating system are you using?

macOS

### Operating System Version

sonoma 14.0 (23A344)

### Installation method

download site

**Comment by fabinajm** [comment]
![Monosnap Insomnia 2023-11-13 14-25-04](https://github.com/Kong/insomnia/assets/50752922/8b0b1256-f89a-499c-9e01-ed8f27922e1f)

**Comment by MEGApixel23** [comment]
Same here. Started happening after updating to 8.4.1

**Comment by tgomesfork** [comment]
Just got the same issue on 8.4.1
Breaking issues on patch versions, amazing 👏

**Comment by bryangeplant** [comment]
Got the same as well. Reinstalling doesn't work. Even weirder is that I chose *not* to update.

**Comment by sakshamsaxena** [comment]
Each week I regret more and more sticking to insomnia now ...

**Comment by binaryatrocity** [comment]
Seeing this as well immediately after updating today - can't try reinstalling as the Google OpenID and Login By Email Code are both dumping me to error screens!

Anyone got a short term workaround to get back to usability until a fix is in place?

**Comment by danesparza** [comment]
Same here

**Comment by Kendall-H** [comment]
Same here!

**Comment by Houwarnick** [comment]
+1

**Comment by linkinkov** [comment]
same here

**Comment by will-meng** [comment]
I reinstalled 8.4.0 to get back up on macOS

**Comment by dgilperez** [comment]
same here

**Comment by ultrarunner** [comment]
I was able to fix the issue by downloading the latest version from the github releases folder and overriding the update manually. Not sure why that would make a difference though. I went here https://github.com/Kong/insomnia/releases,  download the macos version and installed it.

**Comment by armenak-baburyan** [comment]
It seem it was some kind of server error.

**Comment by danesparza** [comment]
> I was able to fix the issue by downloading the latest version from the github releases folder and overriding the update manually. Not sure why that would make a difference though.

What are the steps to do this?

**Comment by montedonioluiz** [comment]
> I reinstalled 8.4.0 to get back up on macOS

Same. Download your OS's version from https://github.com/Kong/insomnia/releases/tag/core%408.4.0

**Comment by danesparza** [comment]
Yeah -- I think this is a pretty serious issue.  What happens if my internet connection goes down, but I still want to do testing on internal servers?  Will this tool no longer work?

**Comment by subnetmarco** [comment]
Is this error still happening?

**Comment by fabinajm** [comment]
> Is this error still happening?

no, working now.

**Comment by rschreijer** [comment]
i get this error today right after update to 8.4.2.
![Screenshot 2023-11-15 at 11 46 42](https://github.com/Kong/insomnia/assets/1904296/3b0bcaf9-79b1-4deb-800f-d00163f811b4)

Fresh install worked: https://github.com/Kong/insomnia/releases/tag/lib%408.4.2

**Comment by andrewatwood** [comment]
Same issue here, right after update stuck on this error

**Comment by JeanRessouche** [comment]
Same

**Comment by VEBERArnaud** [comment]
same here

![Screenshot 2023-11-15 at 17 09 12](https://github.com/Kong/insomnia/assets/5168814/b5368932-62c5-42a4-ab5c-de7b4ba76e66)
![Screenshot 2023-11-15 at 17 10 50](https://github.com/Kong/insomnia/assets/5168814/cee031db-91fa-4af1-be9f-7dda6980607c)

**Comment by JeanRessouche** [comment]
This should not be closed as the latest update/install pack isn't working.

Downloaded the windows version, starting it: nothing happens.

If i unistall to reinstall completely, will i loose my local collections ?

**Comment by Cajs** [comment]
same here - macos 14.0 with Insomnia 8.4.2

```[2023-11-15 16:08:13.047] [error] TypeError: Cannot read properties of undefined (reading 'match')
    at yI (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-09030ac4.js:659:7762)
    at eJ (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-09030ac4.js:707:774)
    at Ck (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-09030ac4.js:116:19553)
    at Hj (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-09030ac4.js:118:44101)
    at Nj (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-09030ac4.js:118:39819)
    at Uxe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-09030ac4.js:118:39745)
    at cp (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-09030ac4.js:118:39596)
    at ow (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-09030ac4.js:118:35959)
    at zj (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-09030ac4.js:118:34906)
    at N (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-09030ac4.js:103:1615)
    at Immediate.me [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-09030ac4.js:103:1987)
    at process.processImmediate (node:internal/timers:476:21)
```

**Comment by bmilioli** [comment]
Same here 

![image](https://github.com/Kong/insomnia/assets/101820274/6cbe5628-2f8d-4af8-9403-513b96cd4b5b)

**Comment by FelDev** [comment]
Downgrading to previous versions didn't work for me.
Switching to Postman `¯\_(ツ)_/¯`
...and hoping I get my saved queries somehow in the future.

**Comment by lcsmobileqa** [comment]
I got this as well with today's upgrade to 8.4.2.
My about window shows:
Version: Insomnia 8.4.2
Build date: 11/15/2023
OS: Windows_NT x64 10.0.22631
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: x64

**Comment by Dammmien** [comment]
Same here, it seems to be an authentication issue, clearing the Local storage in the dev tools fixes the issue.

```
Version: Insomnia 8.4.2
Build date: 11/15/2023
OS: Darwin arm64 22.4.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: arm64
```

<img width="1516" alt="Capture d’écran 2023-11-15 à 17 20 04" src="https://github.com/Kong/insomnia/assets/3051737/106feae3-5ae0-40c9-b4a0-9081f31bded7">

**Comment by faradayfan** [comment]
I'm experiencing this issue after upgrading as well. I tried removing the app, then reinstalling, this seeing the error.
```
Version: Insomnia 8.4.2
Build date: 11/15/2023
OS: Darwin arm64 23.1.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: arm64
```
[main.log](https://github.com/Kong/insomnia/files/13367170/main.log)

The log shows:
```
[2023-11-15 08:53:38.880] [info]  Running version 8.4.2
[2023-11-15 08:53:38.884] [info]  [electron client protocol] successfully set default protocol 'insomnia://'
[2023-11-15 08:53:39.066] [info]  [fix] Running database repairs
[2023-11-15 08:53:39.211] [info]  [db] Initialized DB at /Users/johnmiller/Library/Application Support/Insomnia/insomnia.$TYPE.db
[2023-11-15 08:53:39.211] [info]  [db] Init responses DB
[2023-11-15 08:53:39.211] [info]  [db] Init websocket-responses DB
[2023-11-15 08:53:39.213] [info]  [localstorage] Initialized at /Users/johnmiller/Library/Application Support/Insomnia/localStorage
[2023-11-15 08:53:39.246] [info]  [main] Loading file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.html
[2023-11-15 08:53:39.324] [info]  [updater] Using url https://updates.insomnia.rest/builds/check/mac?v=8.4.2&app=com.insomnia.app&channel=stable
[2023-11-15 08:53:39.325] [info]  [updater] Checking for updates url=https://updates.insomnia.rest/builds/check/mac?v=8.4.2&app=com.insomnia.app&channel=stable
[2023-11-15 08:53:40.283] [info]  [updater] Not Available
[2023-11-15 08:54:08.619] [info]  Response not OK: 503 for https://api.insomnia.rest/v1/user/profile
[2023-11-15 08:54:09.640] [info]  [main] Window ready, handling command line arguments [ '/Applications/Insomnia.app/Contents/MacOS/Insomnia' ]
[2023-11-15 08:54:09.642] [info]  [main] Checking for newer version than  8.4.2
[2023-11-15 08:54:09.775] [info]  [main] No newer version
[2023-11-15 09:09:20.771] [info]  [main] creating new window for MacOS activate event
[2023-11-15 09:09:20.788] [info]  [main] Loading file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.html
[2023-11-15 09:09:49.003] [info]  Response not OK: 503 for https://api.insomnia.rest/v1/user/profile

```

**Comment by subnetmarco** [comment]
Are these errors happening going from `8.4.1` to `8.4.2`, or are these errors happening going from `8.3.x` to `8.4.x` ?

**Comment by paulmerlyn** [comment]
Like everyone else, I've been freaking out on the sudden loss of Insomnia since permitting the update to 8.4.2. I was about to try deleting local storage (suggested above by Dammien as a possible fix), but was able to get my functionality back instead by simply using File > New Window. I hope that trick works for others.
<img width="1437" alt="Screenshot 2023-11-15 at 9 28 44 AM" src="https://github.com/Kong/insomnia/assets/2975054/7d823b2c-27fc-48b9-af25-4b8bf84887b5">

**Comment by rschreijer** [comment]
@subnetmarco I was on 8.4.1 going to 8.4.2.

**Comment by FelDev** [comment]
99.9% sure this was a temporary server-side error that didn't get handled properly by the front-end. Everything is back to normal now.

**Comment by subnetmarco** [comment]
We have identified the problem on our end. Restarting the application will resolve this problem.

We will be shipping better error handling in 8.4.3 next week to handle this scenario, which absolutely should not be sending the application in this panicking state.

I will keep this ticket open until the error handling is put in place.

**Comment by subnetmarco** [comment]
Hello 👋 Insomnia 8.4.4 has been shipped with important **performance improvements** that brings back a ton of speed in the UI. This issue has also been resolved. 

You can wait for the auto-updater to download it for you, or you can manually download it [here](https://github.com/Kong/insomnia/releases/tag/core%408.4.4).
