### ISSUE TITLE
Collections and documents not loading anymore with 8.4.2

### ISSUE THREAD

**Issue by tberger-plugsurfing** [getinsomnia/insomnia#6819]
### Expected Behavior

Still see all my data (collections etc.) after the update to latest version

### Actual Behavior

Screen is empty, just showing Render Failure: Cannot read properties of undefined (reading 'match')

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 8.4.2
Build date: 11/15/2023
OS: Darwin arm64 23.1.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: arm64

### Insomnia Version

Insomnia 8.4.2

### What operating system are you using?

macOS

### Operating System Version

Darwin arm64 23.1.0

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

8.4.1

**Comment by jmitash** [comment]
I am having the same issue
```
Version: Insomnia 8.4.2
Build date: 11/15/2023
OS: Darwin x64 22.6.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: x64
```
I launch the app, and this is all I see:
![image](https://github.com/Kong/insomnia/assets/1114994/e37b250a-ba81-4983-b422-3af144a1917a)

**Comment by tberger-plugsurfing** [comment]
Exception log (renderer.log):
```
[2023-11-15 16:50:53.390] [info]  [db] Initialized DB client
[2023-11-15 16:51:21.486] [info]  Fetching projects for team org_3e8b9f53-3a03-4b9c-9349-39956d69183e
[2023-11-15 16:51:21.672] [info]  Redirecting to last visited project proj_default-project
[2023-11-15 16:51:21.947] [error] TypeError: Cannot read properties of undefined (reading 'match')
    at gI (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:659:7762)
    at XQ (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:707:774)
    at Ck (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:116:19553)
    at Lj (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:118:44101)
    at Mj (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:118:39819)
    at Fxe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:118:39745)
    at cp (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:118:39596)
    at ow (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:118:35959)
    at kj (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:118:34906)
    at N (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:103:1615)
    at Immediate.me [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:103:1987)
    at process.processImmediate (node:internal/timers:476:21)

```

**Comment by SuprimeKebab** [comment]
same

<img width="272" alt="изображение" src="https://github.com/Kong/insomnia/assets/145693088/65218a7e-d984-4bfc-8c53-c585987c4576">
<img width="472" alt="изображение" src="https://github.com/Kong/insomnia/assets/145693088/e0d2bd2e-1a96-4513-8090-9e2813cefd28">

**Comment by robertol** [comment]
+1

**Comment by leon2402** [comment]
Same problem over here

**Comment by tberger-plugsurfing** [comment]
Could someone successfully rollback to an older version? I tried installing 8.4.1 and 8.4.0 but the error remains.

**Comment by OneComputerGuy** [comment]
+1, One thing to note, there seems to be something else rather than the version.
8.4.1 was working for me yesterday, and I had it running up until around 11PM-EST, so I don't think it was related to version updates (the other Mac I have still has 8.4.1 and has this issue also)

**Comment by robertol** [comment]
Hey guys! I just exported my collections before the downgrade to 8.4.1 so it's working again. I've tried to upgrade again and now it's working on latest version:

Version: Insomnia 8.4.2
Build date: 11/15/2023
OS: Darwin x64 23.1.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: x64

@edit 
I think this bug is real (and very hurt) because since my first post I take this same error when I close and open many times until it turn to work again.

**Comment by SuprimeKebab** [comment]
just restarted and it's already works

**Comment by OneComputerGuy** [comment]
Seems to be working now after a restart, weird that it works now without issue. The code that was failing was related to the avatar while trying to render an icon (?... Not sure is that information is not stored locally and relies on a cloud version of it).

Edit: It does seem to be relying on an icon being generated externally (couple of request to Gravatar are available after completing the loading process)

The stack trace I got is somewhat different from the one posted above, hopefully it can give more pointers:


```
11:25:30.771 › TypeError: Cannot read properties of undefined (reading 'match')
    at gI (avatar.tsx:18:31)
    at XQ (avatar.tsx:128:87)
    at Ck (react-dom.production.min.js:167:137)
    at Lj (react-dom.production.min.js:290:337)
    at Mj (react-dom.production.min.js:280:389)
    at Fxe (react-dom.production.min.js:280:320)
    at cp (react-dom.production.min.js:280:180)
    at ow (react-dom.production.min.js:271:88)
    at kj (react-dom.production.min.js:268:429)
    at N (scheduler.production.min.js:13:203)
    at Immediate.me [as _onImmediate] (scheduler.production.min.js:14:128)
    at process.processImmediate (node:internal/timers:476:21)
```

**Comment by tberger-plugsurfing** [comment]
Ok I can confirm that it works for me as well. I guess it was some incompatible cloud-data sent to the client?

**Comment by vhscom** [comment]
Confirmed resolved after restart, but only after a restart as of now (earlier restarts had no effect).

**Comment by subnetmarco** [comment]
We have identified the problem on our end. Restarting the application will resolve this problem.

We will be shipping better error handling in 8.4.3 next week to handle this scenario, which absolutely should not be sending the application in this panicking state.

I will keep this ticket open until the error handling is put in place.

**Comment by subnetmarco** [comment]
Hello 👋 Insomnia 8.4.4 has been shipped with important **performance improvements** that brings back a ton of speed in the UI. You can wait for the auto-updater to download it for you, or you can manually download it [here](https://github.com/Kong/insomnia/releases/tag/core%408.4.4).
