### ISSUE TITLE
Render failure for Graphql on 8.4.3 and 8.4.4

### ISSUE THREAD

**Issue by prerakathighnoteplatform** [getinsomnia/insomnia#6857]
### Expected Behavior

To Render the Query/Request window to work as is without any rendering issue.

### Actual Behavior

Render failure: e.includes is not a function

![Screenshot 2023-11-22 at 10 59 47 AM](https://github.com/Kong/insomnia/assets/106942029/bfa8b21f-c76b-4d37-9733-5b8cc054d86e)

### Reproduction Steps

1. Upgrade Insomnia to 8.4.3 or 8.4.4
2. Open an Insomnia Project after upgrade (existing one not new)
3. and boom Request/Graphql Query Window throws the below error

![Screenshot 2023-11-22 at 10 57 03 AM](https://github.com/Kong/insomnia/assets/106942029/32593e34-2945-41a8-9773-25a240ce1557)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

```
Version: Insomnia 8.4.4
Build date: 11/22/2023
OS: Darwin arm64 22.6.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: arm64

```

### Insomnia Version

8.4.4

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.6

### Installation method

upgrade to existing one

### Last Known Working Insomnia version

8.4.2

**Comment by prerakathighnoteplatform** [comment]
possible duplicate only difference is the OS version due to the same time issue opening by myself and @camiloclc
. https://github.com/Kong/insomnia/issues/6858.

**Comment by BigVOVA** [comment]
The same issue:

Mac OS version: Sonoma 14.1

Version: Insomnia 8.4.4
Build date: 11/22/2023
OS: Darwin arm64 23.1.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: arm64

**Comment by WallacyFrancis** [comment]
I'm having the same error with GraphQL requests

```
Version: Insomnia 8.4.4
Build date: 22/11/2023
OS: Linux x64 5.15.0-89-generic
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: x64
```

**Comment by RussBrown00** [comment]
Same issue. Repatative, but in text form:

```[2023-11-22 21:01:15.802] [info]  [db] Initialized DB client
[2023-11-22 21:01:15.817] [info]  [plugin] Loaded /Users/rbrown/Library/Application Support/Insomnia/plugins/insomna-photivo-bufferid
[2023-11-22 21:01:15.818] [info]  [plugin] Loaded /Users/rbrown/Library/Application Support/Insomnia/plugins/insomnia-plugin-mpix-token
[2023-11-22 21:01:15.819] [info]  [plugin] Loaded /Users/rbrown/Library/Application Support/Insomnia/plugins/insomnia-plugin-randomnumber
[2023-11-22 21:01:16.554] [info]  Fetching projects for team team_af95bd9b7e2c4a358d4d0d392c89c1af
[2023-11-22 21:01:16.634] [info]  Redirecting to last visited project proj_234bca1ceed04ca4a3c3e87d6371d439
[2023-11-22 21:01:16.859] [info]  [FileSystemDriver] Initialized in "/Users/rbrown/Library/Application Support/Insomnia/version-control"
[2023-11-22 21:01:19.565] [info]  [sync] Activated project prj_0eb2e3ae2ed04fac866d7bc5b61496e9
[2023-11-22 21:01:19.609] [info]  [sync] Activated project prj_0eb2e3ae2ed04fac866d7bc5b61496e9
[2023-11-22 21:01:19.786] [error] TypeError: e.includes is not a function
    at KVe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:470:868)
    at _l (file:///Applications/Insomnia.app/Contents/Resources/app.asar/debug-672b1df6.js:53:34237)
    at FS (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:42:19553)
    at aF (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:44101)
    at tF (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:39819)
    at qpe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:39745)
    at Fd (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:39596)
    at Px (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:35959)
    at QO (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:44:34906)
    at N (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:29:1615)
    at Immediate.me [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-37d8fc4b.js:29:1987)
    at process.processImmediate (node:internal/timers:476:21)
[2023-11-22 21:02:20.946] [info]  [sync] Activated project prj_0eb2e3ae2ed04fac866d7bc5b61496e9
```

**Comment by subnetmarco** [comment]
We found the issue as described here https://github.com/Kong/insomnia/issues/6858#issuecomment-1823647256

**Comment by filfreire** [comment]
Hey folks, update here - we applied a fix for this here: https://github.com/Kong/insomnia/pull/6861

Make sure to download the latest [release 8.4.5](https://github.com/Kong/insomnia/releases/tag/core%408.4.5) that has the fix.

**Comment by prerakathighnoteplatform** [comment]
Confirming [release 8.4.5](https://github.com/Kong/insomnia/releases/tag/core%408.4.5) works for me. Hope it works for everyone else. Thanks for fixing it quickly. Appreciated all @filfreire @gatzjames @ihexxa and @marckong
