### ISSUE TITLE
Duplicate Workspace (non-functional) after setting up cloud sync

### ISSUE THREAD

**Issue by RomeoKilo125** [getinsomnia/insomnia#6880]
### Expected Behavior

After setting up cloud sync, I expected my previous "personal workspace" to be synced

### Actual Behavior

After setting up cloud sync, I have a NEW personal workspace. and my old one throws an error.

I cannot delete this workspace either.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Error: No projects found for this organization. at b2 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:17:108014) at Module.oa (file:///Applications/Insomnia.app/Contents/Resources/app.asar/project-22fbbfed.js:1:22677) at async _8 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:54:3729) at async Promise.all (index 2) at async Ve (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:53:23499) at async q (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:53:21362)

### Insomnia Version

8.4.5

### What operating system are you using?

macOS

### Operating System Version

MacOS 11.7.10

### Installation method

homebrew

**Comment by marckong** [comment]
Hi @RomeoKilo125 it seems that the issue occurred from here - https://github.com/Kong/insomnia/blob/a5d843171a841b9117e2e4b1503a362fca6bcfd0/packages/insomnia/src/ui/routes/project.tsx#L253

I can see a couple of factors here, but to confirm we may need your account id to verify. Can you let us know your email address in our community slack?
