### ISSUE TITLE
List of available calls disappears, apart from the last one used and then a message appears 

### ISSUE THREAD

**Issue by JulianNicholls** [getinsomnia/insomnia#6881]
### Expected Behavior

I should be able to scroll up and down the list of available calls.

### Actual Behavior

The list of available calls disappears, apart from one of the last ones used and, after a short delay, a message appears

```Application error

          Failed to render . Please report the error to [our Github Issues]
```

with the following stack trace

```
TypeError: Cannot read properties of null (reading 'index')
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:119:177794
    at Ch (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:44:24296)
    at D6 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:44:42448)
    at z_ (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:44:36651)
    at Ls (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:42:3288)
    at ehe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:44:41325)
    at sc (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:44:40309)
    at rF (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:44:35758)
    at N (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:29:1615)
    at Immediate.me [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-016b0889.js:29:1987)
    at process.processImmediate (node:internal/timers:476:21)
```

### Reproduction Steps

Scrolling the list of available calls seems to trigger the problem.
It is becoming increasingly less difficult to reproduce, I have had it crash three times in the last two days.

I am using the latest version, and it has only started to happen with this version:

```Version: Insomnia 8.4.5
Build date: 11/23/2023
OS: Darwin arm64 23.1.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: arm64
```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.5

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.1.1

### Installation method

This was from the last automatic update. Originally installed from insomnia.rest

### Last Known Working Insomnia version

8.4.4?

**Comment by marckong** [comment]
Hi @JulianNicholls would you mind elaborating more on this issue. What do you mean by "Calls"? Did you mean the list of requests or the list of request history? Would you be able to share a screenshot with us?
