### ISSUE TITLE
Render Failure: Cannot read properties of null (reading 'index')

### ISSUE THREAD

**Issue by kaden-powell** [getinsomnia/insomnia#7149]
### Expected Behavior

Scrolling up and down in the request menu on the left shows requests and error pop-up not produced.

### Actual Behavior

Usually after having the program open for a bit, if I scroll up or down on my request menu to the left, out-of-view items will not appear. If I continue to scroll, a render error pop-up is displayed. The only way to get the requests back is to close and open a new window.

![Screenshot 2024-03-06 at 3 02 10 PM](https://github.com/Kong/insomnia/assets/113463251/6d43b87d-a647-4f26-b4a4-89ea388693a5)
![Screenshot 2024-03-06 at 3 01 56 PM](https://github.com/Kong/insomnia/assets/113463251/ff13ca0b-4488-4c61-895a-1ac026bc5e53)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Stack trace:
TypeError: Cannot read properties of null (reading 'index')
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:119:69992
    at em (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:44:24296)
    at U6 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:44:42448)
    at DA (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:44:36651)
    at Is (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:42:3288)
    at hve (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:44:41325)
    at mc (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:44:40309)
    at uO (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:44:35758)
    at D (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:29:1614)
    at Immediate.pe [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:29:1985)
    at process.processImmediate (node:internal/timers:476:21)

### Insomnia Version

Version: Insomnia 8.6.1 Build date: 2/5/2024 OS: Darwin arm64 23.3.0 Electron: 28.0.0 Node: 18.18.2 Node ABI: 119 V8: 12.0.267.8-electron.0 Architecture: arm64

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.3.1

### Installation method

https://insomnia.rest/download (I believe with recent updates)

```[tasklist]
### Tasks
```

**Comment by CurryYangxx** [comment]
This error occurs in a third-party package.There is a related issue (https://github.com/adobe/react-spectrum/issues/5817) at their repo.I think we can follow the progress of this issue.

**Comment by fhecorrea** [comment]
![image](https://github.com/Kong/insomnia/assets/22400468/b52b34cc-40a8-4ae3-9877-152de9d75766)
Same issue here.

**Comment by CurryYangxx** [comment]
The related issue(https://github.com/adobe/react-spectrum/issues/5817) has been fixed in this release: 
https://react-spectrum.adobe.com/releases/2024-09-30.html
