### ISSUE TITLE
Error when scroll collection 

### ISSUE THREAD

**Issue by adityarizkyramadhan** [getinsomnia/insomnia#7206]
### Expected Behavior

TypeError: Cannot read properties of null (reading 'index')
    at file:///C:/Users/Aditya%20Rizky%20Ramadha/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:119:69992
    at em (file:///C:/Users/Aditya%20Rizky%20Ramadha/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:44:24296)
    at U6 (file:///C:/Users/Aditya%20Rizky%20Ramadha/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:44:42448)
    at DA (file:///C:/Users/Aditya%20Rizky%20Ramadha/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:44:36651)
    at Is (file:///C:/Users/Aditya%20Rizky%20Ramadha/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:42:3288)
    at hve (file:///C:/Users/Aditya%20Rizky%20Ramadha/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:44:41325)
    at mc (file:///C:/Users/Aditya%20Rizky%20Ramadha/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:44:40309)
    at uO (file:///C:/Users/Aditya%20Rizky%20Ramadha/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:44:35758)
    at D (file:///C:/Users/Aditya%20Rizky%20Ramadha/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:29:1614)
    at Immediate.pe [as _onImmediate] (file:///C:/Users/Aditya%20Rizky%20Ramadha/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:29:1985)
    at process.processImmediate (node:internal/timers:476:21)

### Actual Behavior

![image](https://github.com/Kong/insomnia/assets/90701908/7ffdbee1-329a-41ff-a7ac-1e2babf74834)
error when search http request

### Reproduction Steps

Scroll on folder of http request

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Render Failure: Cannot read properties of null (reading 'index')

### Insomnia Version

8.6.1

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.22631

### Installation method

insomnia.rest

```[tasklist]
### Tasks
```

**Comment by subnetmarco** [comment]
@adityarizkyramadhan Can you try with the latest 9.2?
