### ISSUE TITLE
Unable to use Insomnia 9.1.0 anymore on MacOS

### ISSUE THREAD

**Issue by louis123562** [getinsomnia/insomnia#7363]
### Expected Behavior

smooth and fast action

### Actual Behavior

Very very very slow start behaviour. It takes about two minutes to start insomnia. it also takes two minutes to open a folder. it also takes a while to open a single request. i am unable to use this program anymore.

### Reproduction Steps

1. start the application
2. get a coffee
3. open a project / collection
4. select a folder
5. get a coffee
6. click on a request
7. get a coffee
8. start using insomnia

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 9.1.0
Build date: 4/30/2024
OS: Darwin arm64 23.2.0
Electron: 29.3.0
Node: 20.9.0
Node ABI: 121
V8: 12.2.281.27-electron.0
Architecture: arm64

### Insomnia Version

9.1.0

### What operating system are you using?

macOS

### Operating System Version

MacOS 14.2 (23C64)

### Installation method

download from official website

### Last Known Working Insomnia version

9.0.0

**Comment by chamby** [comment]
For me this was a temporary issue. Perhaps there was a long network timeout for the cloud service or something blocking the UI?

**Comment by ahonore42** [comment]
Was just getting this when accessing settings, also on macOS:

```
TypeError: Cannot destructure property 'organizations' of 'c4e(...)' as it is undefined.
    at tg1 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-5d87552f.js:1537:26331)
    at Ck (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-5d87552f.js:116:19553)
    at Lj (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-5d87552f.js:118:44101)
    at Mj (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-5d87552f.js:118:39819)
    at Fxe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-5d87552f.js:118:39745)
    at cp (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-5d87552f.js:118:39596)
    at ow (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-5d87552f.js:118:35959)
    at xH (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-5d87552f.js:118:36764)
    at _s (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-5d87552f.js:116:3288)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-5d87552f.js:118:34286
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
```
    
    
   To be clear, I wasn't able to login or access any of my request collections locally. Google auth didn't work, Github auth didn't work, Email auth didn't work, and SSO didn't work. All requests were timing out and returning server errors.
   
   The issue seems to be fixed just now though.

**Comment by filfreire** [comment]
See https://github.com/Kong/insomnia/issues/7358#issuecomment-2090962167
