### ISSUE TITLE
[Bug] libcurl-gnutls.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by lovasoa** [getinsomnia/insomnia#742]
- Insomnia Version: 5.14.3
- Operating System: Linux Fedora 27

## Details

After updating to the latest version of insomnia, I get a blank screen on startup, and the following error message in the DevTools panel:

```
Uncaught Error: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/.mount_insomnsplYYw/app/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:29)
    at Object.<anonymous> (/tmp/.mount_insomnsplYYw/app/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:280:3)
```

**Comment by gschier** [comment]
Hmm, I have a feeling this is due to the latest version being built on Ubuntu Xenial. Going to revert back to the old version (Trusty) and try another release.

**Comment by lovasoa** [comment]
Workaround for other affected users:

```
sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4
```

**Comment by gschier** [comment]
Can you check if this is working now in v5.14.6?

**Comment by yoannfleurydev** [comment]
Hi 👋 

I do have this issue with v5.14.3. 

v5.14.6 is working perfectly ✅

**Comment by lovasoa** [comment]
It works

**Comment by gschier** [comment]
Thanks!

**Comment by binki** [comment]
I’m working around this by running `bin_replace_string -r libcurl-gnutls.so.4 libcurl.so.4 node_modules/nodegit/build/Release/nodegit.node`. I don’t want to create random symlinks in `/usr/lib`—that’s managed by my distro’s package manager.

**Comment by zackster** [comment]
@binki Since this seems to be the canonical location for this bug :P ...

I can't get ahold of `bin_replace_string` since it seems to be a gentoo package.

I tried this,

`bbe -e 's/libcurl-gnutls.so.4/libcurl.so.4/' node_modules/nodegit/build/Release/nodegit.node > node_modules/nodegit/build/Release/nodegit.node`

but unfortunately this is leading to a segfault.
