### ISSUE TITLE
[Bug] Blank window

### ISSUE THREAD

**Issue by Djaler** [getinsomnia/insomnia#743]
- Insomnia Version: 5.14.3 (installed from Snap)
- Operating System: elementary OS Loki (based on Ubuntu 16.04)

When I start Insomnia, I see only blank white screen.

![2018-02-07 21 49 12](https://user-images.githubusercontent.com/7964583/35935250-fa664bee-0c50-11e8-800c-0fa9af2efb4f.png)

**Comment by gschier** [comment]
How did you find the snap already? I only published it for the first time yesterday as a test.

To debug, can you go to View > Toggle DevTools and post any errors you see here?

**Comment by Djaler** [comment]
I just monitor new snaps in https://uappexplorer.com/snaps

**Comment by Djaler** [comment]
DevTools looks broken too

![2018-02-08 09 07 53](https://user-images.githubusercontent.com/7964583/35958026-9542bd2e-0caf-11e8-97c6-9b5f468f71d7.png)

**Comment by Djaler** [comment]
Also, when I start this snap, it creates empty folders ~/Desktop, ~/Documents, ~/Pictures, ~/Public and ~/Templates

**Comment by Djaler** [comment]
Same thing on another computer (Debian 9 with KDE 5.8.6).

But DevTools works well.
Error:
```
Uncaught Error: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/snap/insomnia/10/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:29)
    at Object.<anonymous> (/snap/insomnia/10/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:280:3)
```

**Comment by gschier** [comment]
Seems to be related to the app being built on Ubuntu Xenial (used Trusty previously). The same problem occurred with the non-snap version (https://github.com/getinsomnia/insomnia/issues/742).

Made the snap private for now and will take another look at this the next time I have time.

**Comment by Djaler** [comment]
Hey, looks like related bug was fixed. What about snap?

**Comment by gschier** [comment]
Still need to figure out how to build the snap on Trusty. I couldn't get it working before, which is why I upgraded the Xenial.
