### ISSUE TITLE
Requests result in 'Invalid time value' error when scripts are used

### ISSUE THREAD

**Issue by mrohlof-protofy** [getinsomnia/insomnia#7611]
### Expected Behavior

After adding a pre request script, requests performs normally and pre request script is run (`console.log("foo");`). 

### Actual Behavior

Request fails before executing with error "Invalid time value". After exporting the collection, deleting all cookies and importing again it works. I have to use this export/import process because the cookie management page won't render. It seems some cookie has an invalid timestamp format.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Application Error when rendering Cookie Management Page:

```
Error: [object Object] 
at Object.validate (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/tough-cookie/lib/validators.js:91:13) 
at formatDate (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/tough-cookie/lib/cookie.js:322:14) 
at Cookie.toString (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/tough-cookie/lib/cookie.js:952:29) 
at ES1 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CMm8UD2o.js:110:16004) 
at Ze (file:///Applications/Insomnia.app/Contents/Resources/app.asar/workspace-environments-edit-modal-Ca9axMV5.js:1:16292) 
at Ok (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CMm8UD2o.js:43:17033) 
at TK (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CMm8UD2o.js:45:44104) 
at _K (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CMm8UD2o.js:45:39822) 
at J9e (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CMm8UD2o.js:45:39748) 
at Yh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CMm8UD2o.js:45:39598) 
at ME (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CMm8UD2o.js:45:35960) 
at zK (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CMm8UD2o.js:45:34907) 
at L (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CMm8UD2o.js:30:1594) 
at Immediate.oe [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CMm8UD2o.js:30:1965) 
at process.processImmediate (node:internal/timers:478:21)
```

### Insomnia Version

9.3

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.4.1

### Installation method

insomnia.rest

**Comment by gatzjames** [comment]
Thanks for the feedback. Closing as this was fixed in 9.3.1
