### ISSUE TITLE
Insomnia installation does not create shortcuts

### ISSUE THREAD

**Issue by kylepantall** [getinsomnia/insomnia#7793]
### Expected Behavior

After installing insomnia:
- Start menu shortcut created
- Desktop shortcut created

### Actual Behavior

No shortcuts are created - therefore you cannot search for the app after installation.

### Reproduction Steps

1. Fresh installation of Insomnia on a Windows machine.
2. Search for insomnia from search, or desktop.
3. Should not be found.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.3 Build: 2024.07.31

### What operating system are you using?

Windows

### Operating System Version

22631.3958

### Installation method

download from insomnia

**Comment by subnetmarco** [comment]
@filfreire to take a look

**Comment by lmorganl** [comment]
i always have installation crash on Windows since a lot of version too :(

**Comment by filfreire** [comment]
@kylepantall do you have Administrator permissions to install an App on your Windows PC?

Also can you share the contents of the following log file: `C:\Users\<replace-with-your-username>\AppData\Local\SquirrelTemp\SquirrelSetup.log` ?

**Comment by kylepantall** [comment]
I've masked my username with `[username]`. 
This is the log file created on the date I raised the issue.

```
2024-08-01 12:12:35> Program: Starting Squirrel Updater: --install .
2024-08-01 12:12:35> Program: Starting install, writing to C:\Users\[username]\AppData\Local\SquirrelTemp
2024-08-01 12:12:35> Program: About to install to: C:\Users\[username]\AppData\Local\insomnia
2024-08-01 12:12:35> Program: Install path C:\Users\[username]\AppData\Local\insomnia already exists, burning it to the ground
2024-08-01 12:12:36> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\[username]\AppData\Local\insomnia\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2024-08-01 12:12:36> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\[username]\AppData\Local\insomnia\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2024-08-01 12:12:36> CheckForUpdateImpl: Reading RELEASES file from C:\Users\[username]\AppData\Local\SquirrelTemp
2024-08-01 12:12:36> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2024-08-01 12:12:37> ApplyReleasesImpl: Writing files to app directory: C:\Users\[username]\AppData\Local\insomnia\app-9.3.3
2024-08-01 12:12:44> LogHost: Rigging execution stub for Insomnia_ExecutionStub.exe to C:\Users\[username]\AppData\Local\insomnia\Insomnia.exe
2024-08-01 12:12:51> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\[username]\AppData\Local\insomnia\app-9.3.3\Insomnia.exe]
2024-08-01 12:13:07> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\[username]\AppData\Local\insomnia\app-9.3.3\Insomnia.exe: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClass11_0.<InvokeProcessAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2024-08-01 12:13:08> ApplyReleasesImpl: Starting fixPinnedExecutables
2024-08-01 12:13:08> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2024-08-01 12:13:08> ApplyReleasesImpl: Examining Pin: Microsoft Edge.lnk
2024-08-01 12:13:08> ApplyReleasesImpl: Examining Pin: Spotify.lnk
2024-08-01 12:13:08> ApplyReleasesImpl: Fixing up tray icons
2024-08-01 12:13:08> ApplyReleasesImpl: cleanDeadVersions: for version 9.3.3
2024-08-01 12:13:08> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-9.3.3
2024-08-01 12:14:21> Program: Starting Squirrel Updater: --install .
2024-08-01 12:14:21> Program: Starting install, writing to C:\Users\[username]\AppData\Local\SquirrelTemp
2024-08-01 12:14:21> Program: About to install to: C:\Users\[username]\AppData\Local\insomnia
2024-08-01 12:14:21> Program: Install path C:\Users\[username]\AppData\Local\insomnia already exists, burning it to the ground
2024-08-01 12:14:21> IEnableLogger: : System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.Kill()
   at Squirrel.UpdateManager.InstallHelperImpl.<>c__DisplayClass6_1.<KillAllProcessesBelongingToPackage>b__2()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
2024-08-01 12:14:21> IEnableLogger: : System.ArgumentException: Process with an Id of 24036 is not running.
   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   at System.Diagnostics.Process.GetProcessById(Int32 processId)
   at Squirrel.UpdateManager.InstallHelperImpl.<>c__DisplayClass6_1.<KillAllProcessesBelongingToPackage>b__2()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
2024-08-01 12:14:22> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\[username]\AppData\Local\insomnia\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2024-08-01 12:14:22> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\[username]\AppData\Local\insomnia\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2024-08-01 12:14:22> CheckForUpdateImpl: Reading RELEASES file from C:\Users\[username]\AppData\Local\SquirrelTemp
2024-08-01 12:14:22> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2024-08-01 12:14:23> ApplyReleasesImpl: Writing files to app directory: C:\Users\[username]\AppData\Local\insomnia\app-9.3.3
2024-08-01 12:14:27> LogHost: Rigging execution stub for Insomnia_ExecutionStub.exe to C:\Users\[username]\AppData\Local\insomnia\Insomnia.exe
2024-08-01 12:14:32> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\[username]\AppData\Local\insomnia\app-9.3.3\Insomnia.exe]
2024-08-01 12:14:48> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\[username]\AppData\Local\insomnia\app-9.3.3\Insomnia.exe: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClass11_0.<InvokeProcessAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2024-08-01 12:14:48> ApplyReleasesImpl: Starting fixPinnedExecutables
2024-08-01 12:14:48> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2024-08-01 12:14:48> ApplyReleasesImpl: Examining Pin: Microsoft Edge.lnk
2024-08-01 12:14:48> ApplyReleasesImpl: Examining Pin: Spotify.lnk
2024-08-01 12:14:48> ApplyReleasesImpl: Fixing up tray icons
2024-08-01 12:14:48> ApplyReleasesImpl: cleanDeadVersions: for version 9.3.3
2024-08-01 12:14:48> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-9.3.3
2024-08-01 12:52:48> Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC
2024-08-01 12:52:48> Program: Starting install, writing to C:\Users\[username]\AppData\Local\SquirrelTemp
2024-08-01 12:52:48> Program: About to install to: C:\Users\[username]\AppData\Local\insomnia
2024-08-01 12:52:48> Program: Install path C:\Users\[username]\AppData\Local\insomnia already exists, burning it to the ground
2024-08-01 12:52:48> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\[username]\AppData\Local\insomnia\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2024-08-01 12:52:48> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\[username]\AppData\Local\insomnia\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2024-08-01 12:52:48> CheckForUpdateImpl: Reading RELEASES file from C:\Users\[username]\AppData\Local\SquirrelTemp
2024-08-01 12:52:48> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2024-08-01 12:52:50> ApplyReleasesImpl: Writing files to app directory: C:\Users\[username]\AppData\Local\insomnia\app-9.3.3
2024-08-01 12:52:57> LogHost: Rigging execution stub for Insomnia_ExecutionStub.exe to C:\Users\[username]\AppData\Local\insomnia\Insomnia.exe
2024-08-01 12:53:04> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\[username]\AppData\Local\insomnia\app-9.3.3\Insomnia.exe]
2024-08-01 12:53:20> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\[username]\AppData\Local\insomnia\app-9.3.3\Insomnia.exe: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClass11_0.<InvokeProcessAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2024-08-01 12:53:20> ApplyReleasesImpl: Starting fixPinnedExecutables
2024-08-01 12:53:20> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2024-08-01 12:53:20> ApplyReleasesImpl: Examining Pin: Microsoft Edge.lnk
2024-08-01 12:53:20> ApplyReleasesImpl: Examining Pin: Spotify.lnk
2024-08-01 12:53:20> ApplyReleasesImpl: Fixing up tray icons
2024-08-01 12:53:20> ApplyReleasesImpl: cleanDeadVersions: for version 9.3.3
2024-08-01 12:53:20> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-9.3.3
```

**Comment by robwent** [comment]
I'm getting this after tha last update.

Updated, old taskbar shortcut no longer worked.
Deleted the shortcut.
Searched for insomnia in the start menu and started it up.
Pinned the new icon in the taskbar.
Closed insomnia.
The newly pinned shortcut is now broken.

**Comment by DST-UPPERSOLUTIONS** [comment]
The issue described by @robwent is still happening in the latest version.
Are there any updates on this?

**Comment by robwent** [comment]
@davidsandoz I found a bit of a workaround for this.
Off the top of my head, I had to go to my users roaming folder
C:\Users\UserName\AppData\Roaming
Find the insomnia folder, which had several versions in it.
Open the latest version, right click the exe file and pin it to the taskbar.
