### ISSUE TITLE
Insomnia in Ubuntu Focal fresh install raises an error:  GLIBC_2.32

### ISSUE THREAD

**Issue by lucassimon** [getinsomnia/insomnia#7867]
### Expected Behavior

Insomnia could not started, when I ran it in terminal via command line the error above appears

### Actual Behavior

Follow the steps

``` 
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
``` 

```
$ node --version
v22.7.0
``` 

```
$ python
Python 3.11.0 (main, Aug 19 2024, 12:41:49) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more informatio
``` 

``` 
$ /opt/Insomnia/insomnia                       
]A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.org.chromium.Chromium.hrNaqC)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:13801)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```

### Reproduction Steps

1. https://insomnia.rest/download
2. Download Insomnia for ubuntu
3. sudo dpkg -i Insomnia.Core-9.3.3.deb

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

``` 
$ ./Insomnia.Core-9.3.4-beta.1.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.org.chromium.Chromium.fnSDir)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:13801)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/tmp/.mount_Insomn0JBTvp/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
``` 

### Insomnia Version

9.3.3

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu focal

### Installation method

download and install via dpkg -i

**Comment by valdinei-fretebras** [comment]
Any answer :(

**Comment by filfreire** [comment]
@valdinei-fretebras @lucassimon  if you remove the `.deb` installation and try to use the [latest snapcraft install](https://github.com/Kong/insomnia/releases/download/core%4010.1.0-beta.2/Insomnia.Core-10.1.0-beta.2.snap), it should work.

This is happening because you are using an older Ubuntu (20.04) than the one we've compiled Insomnia on (22.04), and from past experiences this means your .deb and Appimage installations won't work well.

We suggest in this case installing the`.snap`.

You can do so by installing through the [Snapcraft Store](https://snapcraft.io/insomnia) 

Or by downloading [latest snapcraft install](https://github.com/Kong/insomnia/releases/download/core%4010.1.0-beta.2/Insomnia.Core-10.1.0-beta.2.snap), and then running

```
sudo snap install Insomnia.Core-10.1.0-beta.2.snap --dangerous
```

**Comment by jackkav** [comment]
The pace that electron updates requires us to follow their lead regarding OS support, although we have tried hard to get insomnia working on older versions we have hit a wall as shown in this comment https://github.com/Kong/insomnia/pull/7868#issuecomment-2309504645

This means building with older versions of ubuntu would impact snapcraft builds so we're at an impass. (We also periodaclly lose support for older version of windows and macos, as you can see in https://www.electronjs.org/blog/electron-33-0#removed-macos-1015-support)
