### ISSUE TITLE
Insomnia working very slow after upgrade to 10

### ISSUE THREAD

**Issue by shubhendu-enable** [getinsomnia/insomnia#7946]
### Expected Behavior

We are using git sync for insomnia , after upgrading to version 10 it should work seamless as before, 

### Actual Behavior

Getting following error when trying to click folders in document 

TypeError: Cannot destructure property 'activeRequest' of '$(...)' as it is undefined.
    at Wc (file:///Applications/Insomnia.app/Contents/Resources/app.asar/debug-BKonWNXc.js:45:11262)
    at Nh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DV0jvs_A.js:43:18469)
    at cj (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DV0jvs_A.js:45:3395)
    at Vk (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DV0jvs_A.js:45:47812)
    at Uk (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DV0jvs_A.js:45:42469)
    at Tk (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DV0jvs_A.js:45:42399)
    at Ik (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DV0jvs_A.js:45:42252)
    at Nk (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DV0jvs_A.js:45:38395)
    at Gk (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DV0jvs_A.js:45:37273)
    at Tt (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DV0jvs_A.js:30:1726)
    at Immediate.zt [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DV0jvs_A.js:30:2135)
    at process.processImmediate (node:internal/timers:483:21)

### Reproduction Steps

Create Document with multiple nested folders 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.0.0

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.6.1

### Installation method

download from insomnia website

### Last Known Working Insomnia version

9.3.3

**Comment by hmundle** [comment]
Same for me and my colleagues: Insomnia working very slow after upgrade to 10.
- we use git sync for insomnia
- we use sub-folders intensively

**Comment by sdernbach-ionos** [comment]
Same here, it is so slow in updating the UI. Environments do not even update only after executing the call the display is updated. Sometimes switching requests have no effect and does not update the display / respond to the click. Had to downgrade to 9.3.3 again.

**Comment by subnetmarco** [comment]
@gatzjames @CurryYangxx to take a look.

**Comment by CurryYangxx** [comment]
@shubhendu-enable Are there any scenes that are significantly slower than before,  or most of scenes?

**Comment by shubhendu-enable** [comment]
most of the scenes, I can see a constant loader on the git branch label.
Every time I try to open any folder and even type something it's non-responsive

**Comment by subnetmarco** [comment]
@shubhendu-enable do you think it would be possible to record a quick screenshare to see exactly what you are experiencing?

**Comment by subnetmarco** [comment]
I believe @CurryYangxx found a culprit for this issue. If validated, the fix will ship in the next 10.1 in a couple of weeks.

**Comment by CurryYangxx** [comment]
I have found the cause of the issue and I will fix it as soon as possible.

**Comment by CurryYangxx** [comment]
A new beta version has been released to optimize performance. You can download here: https://github.com/Kong/insomnia/releases/tag/core%4010.1.0-beta.0.

**Comment by shubhendu-enable** [comment]
@CurryYangxx  Still not working , i had tried with https://github.com/Kong/insomnia/releases/tag/core%4010.1.0-beta.0. release
    
    getting below error
    
    TypeError: Cannot destructure property 'activeRequest' of '$(...)' as it is undefined.
    at Zc (file:///Applications/Insomnia.app/Contents/Resources/app.asar/debug-BKpA79J6.js:45:11262)
    at Nh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-BuwHlDLI.js:43:18469)
    at cj (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-BuwHlDLI.js:45:3395)
    at Vk (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-BuwHlDLI.js:45:47812)
    at Uk (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-BuwHlDLI.js:45:42469)
    at Tk (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-BuwHlDLI.js:45:42399)
    at Ik (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-BuwHlDLI.js:45:42252)
    at Nk (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-BuwHlDLI.js:45:38395)
    at Gk (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-BuwHlDLI.js:45:37273)
    at Ct (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-BuwHlDLI.js:30:1726)
    at Immediate.zt [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-BuwHlDLI.js:30:2135)
    at process.processImmediate (node:internal/timers:483:21)

**Comment by shubhendu-enable** [comment]
to reproduce this, when you send api request from collection, then after few api calls this starts to load continuously
<img width="441" alt="image" src="https://github.com/user-attachments/assets/b5a7d4b9-662d-40b9-8019-0062552d671b">

and after trying to click other API's.  it's non-responsive and getting error as mentioned in above chat

**Comment by CurryYangxx** [comment]
@shubhendu-enable Thanks for your feedback.I will continue to investigate to solve this issue.

**Comment by CurryYangxx** [comment]
@shubhendu-enable Hi, we further optimize in #7989, you can download the pr artifacts to experience through the link below. If it is ok, we plan to release a new beta this week. Thanks!
https://github.com/Kong/insomnia/actions/runs/10992005627?pr=7989

**Comment by notjaywu** [comment]
@hmundle @shubhendu-enable @sdernbach-ionos We just released a new beta version `10.1.0-beta.1`, could you verify if it resolves the performance issue? Thanks!

**Comment by sdernbach-ionos** [comment]
@notjaywu @CurryYangxx sorry I was on vacation, thanks for fixing it! For me it looks good and worked like expected

**Comment by CurryYangxx** [comment]
Thanks for your feedback, our team will continue working on further optimization. Thanks for your patience.

**Comment by hmundle** [comment]
I tested Insomnia.Core-10.1.0-beta.2.exe, it is working smooth again, thanks.
When do you release version 10.1.0. I would like to give this version to my colleagues...

**Comment by subnetmarco** [comment]
Most likely next week.
