### ISSUE TITLE
Uncaught error: cannot find module

### ISSUE THREAD

**Issue by BakirRabiaSalma** [getinsomnia/insomnia#832]
- Insomnia Version: ___
- Operating System: ___linux

## Details
I would run another electron application from the code source of insomia.
i add a link and i open a new window that will load the electron app 
i execute npm install to add all the dependencies but when i try to open the link  i get this error;
module.js:472 Uncaught Error: Cannot find module './config'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/salma_bakir/Bureau/insomnia-dev/packages/insomnia-app/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
I would understand that if it's possible to load an electron app in new window from insomia 
and how to fix this probleme

**Comment by BakirRabiaSalma** [comment]
when i run the electron app  it works without any problem but when i try to run it from the link i get error

**Comment by gschier** [comment]
I'm not really sure what you are trying to do. Can you provide some code?

**Comment by BakirRabiaSalma** [comment]
from insomia i would run another electron app so i add a link to open it  in new window

**Comment by BakirRabiaSalma** [comment]
I would load an electron application in the new window

**Comment by BakirRabiaSalma** [comment]
`module.js:472 Uncaught Error: Cannot find module './config'
    at Module._resolveFilename (module.js:470)
    at Function.Module._resolveFilename (/home/salma_bakir/Bureau/insomnia-dev/packages/insomnia-app/node_modules/electron/dist/resources/el…:35)
    at Function.Module._load (module.js:418)
    at Module.require (module.js:498)
    at require (internal/module.js:20)
    at main.js:4`

**Comment by gschier** [comment]
What does your link look like? Please provide a real code example
