### ISSUE TITLE
[Bug] Doesn't work in Ubuntu 18.04

### ISSUE THREAD

**Issue by luispabon** [getinsomnia/insomnia#878]
- Insomnia Version: 5.15.0-1953 from insomnia repo
- Operating System: Ubuntu 18.04

## Details
Insomnia fails to start in Ubuntu 18.04 with the following:

```
~ insomnia
 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /tmp/.org.chromium.Chromium.8hNBjb)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/storage-ext/opt/Insomnia/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:29)
    at Object.<anonymous> (/storage-ext/opt/Insomnia/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:280:3)
```

This is due to Ubuntu shipping with libcurl4 only. Manually installing libcurl3 fixes insomnia startup. Should probably add as a dependence on the .deb?

**Comment by gschier** [comment]
See #805

**Comment by gschier** [comment]
Currently working on providing a statically linked version of libcurl to the linux builds so a dependency isn't needed.
