### ISSUE TITLE
[Bug] Missing libnghttp2

### ISSUE THREAD

**Issue by cassiobock** [getinsomnia/insomnia#920]
- Insomnia Version: Version 5.16.1
- Operating System: Ubuntu 16.04 LTS

## Details

After updating Insomnia with the apt update, I had problems to start the app again. Running on the terminal, it showed the following error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libnghttp2.so.14: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:29)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:280:3)
```

I fixed it installing `libnghttp2-dev`. Does anyone knows if this is an isolated issue or the update didn't install the required library?

**Comment by gschier** [comment]
Ya, this is an artifact of trying to statically link `libcurl` (and all the libraries it uses) into the Insomnia build in order to remove any dependency requirement. Looks like I missed `libnghttp2` didn't get linked properly.

**Comment by gschier** [comment]
Alright, I was able to reproduce this on a fresh 16.04 install. Will try and get a fix out today

**Comment by voxsoftware** [comment]
Just now I installed, and bug still present

**Comment by gschier** [comment]
@voxsoftware can you post your OS version and Insomnia version?

**Comment by apierri** [comment]
Exact same error here! Ubuntu 17.10, Insomnia 5.16.2
